### PR TITLE
Support creating symlinks outside elevated sessions

### PR DESCRIPTION
**Pull request by dscho**
This Pull Request is intended to supersede https://github.com/git-for-windows/git/pull/1184.

The main difference is that I fixed a rather serious bug (the return value was declared incorrectly, possibly fooling Git into believing that it could create a symbolic link when it really failed, and that really happened here during my tests), and that the file/directory flags are modified only once. I also use the `GetVersion()` API instead of the POSIX-y `uname()`.

### CODE REVIEW

**Comment by dscho** [comment]
Oh, and I also decided to test for the build number of the first Insider build that supported the flag...

**Comment by ralish** [comment]
Looks good to me and nice pick-up on the return type of `CreateSymbolicLinkW`!

Only comment is I think it'd be nice to preserve the `#ifndef`s corresponding to the `CreateSymbolicLinkW` flags for readability in the absence of importing the actual header. Otherwise we do end-up with a fair few magic numbers that are going to be potentially quite non-obvious to others. A minor point for sure, but in general I think the less magic numbers the better.

**Comment by dscho** [comment]
> in general I think the less magic numbers the better.

I agree. However, the header files available in Git for Windows' SDK do not even have that flag yet. So even if we bumped `_WINNT_VER` to `0x600` (i.e. *require* Windows Vista or later, which leads to all kinds of unrelated compile errors e.g. because of the `pollfd` declarations), we would not be able to include the header and use the symbol.

As to `#define`'ing it, we also have to consider Git's pretty strict formatting rules: 80 columns per line, no more. And that symbol is *really* long (I thought only Germans use stupidly long names, but apparently I was wrong).

As the symbol's name has been mentioned in the code comment above, I am a bit less concerned about the magic-ness of the `2`, too ;-)

Thanks for the look-over!

**Comment by ralish** [comment]
Excellent, thanks for the explanation as to the rationale. As for the missing flag, I addressed that in a separate [patch](https://github.com/mirror/mingw-w64/commit/3db7068379db62a5eb8c8fc12fc0a8f4cf2de2ee) a few days ago to the Mingw-w64 developers so it should be available in a future release (though doesn't solve the 80 columns per line issue, but indicating anyway just for reference).

Thanks for merging. Looking forward to finally having 100% usable symlinks on Windows in Git!

**Comment by dscho** [comment]
> Looking forward to finally having 100% usable symlinks on Windows in Git!

Yesss! And thanks for all your help!

**Pull request merged**
