### PR TITLE
Replace argv_array with strvec

### PR DESCRIPTION
**Pull request by derrickstolee**
The upstream branch jk/strvec was introduced shortly after v2.28.0. This rewrites an important "string vector" library to not be named so closely to arguments of a subcommand. There were a few interesting conflicts in the Git for Windows history:

    gpg-interface.c:
    b464b38f6 (Unbreak interactive GPG prompt upon signing, 2016-09-06)
    
    transport-helper.c:
    7c7ef40b4 (transport-helper: prefer Git's builtins over dashed form, 2017-07-19)
    43184f4ce (transport-helper: add trailing --, 2010-08-28)

Bringing this into Git for Windows a little early will prevent contributions during the v2.29.0 cycle from colliding when rebasing onto that (future) version.

Cc: @peff

### CODE REVIEW

**Comment by dscho** [comment]
> gpg-interface.c:
> b464b38f6 (Unbreak interactive GPG prompt upon signing, 2016-09-06)

Did it help to compare to the rebased commit in `shears/seen` (https://github.com/git-for-windows/git/commit/24179d42bbd8fef8ff608830eed8e277a1049821)?

**Comment by dscho** [comment]
@derrickstolee could you replace the `???` in `fixup???` by `fixup!` in the two tip commits? That way, I won't have to remember during the next merging-rebase... Other than that, I think this PR is good to go.

**Comment by derrickstolee** [comment]
> > gpg-interface.c:
> > [b464b38](https://github.com/git-for-windows/git/commit/b464b38f629ef6c6b223397d506e1a57b6832e02) (Unbreak interactive GPG prompt upon signing, 2016-09-06)
> 
> Did it help to compare to the rebased commit in `shears/seen` ([24179d4](https://github.com/git-for-windows/git/commit/24179d42bbd8fef8ff608830eed8e277a1049821))?

Since that wasn't a `fixup???` I didn't cherry-pick it. However, I can create a `fixup!` myself.

**Comment by peff** [comment]
Sorry for creating work. I tried to cover all of the topics in flight, but of course I just looked in `git/git`. :wink: I'm not sure if there's a way to make this easier in the future (I also rebase personal topics and had to deal with some fallout), but let me know if you have suggestions.

**Comment by derrickstolee** [comment]
> Sorry for creating work.

I don't think there is any way around this to some extent. This is work we would need to do around release time, anyway, and it's not the worst we've seen. I'm taking it early because there are multiple topics in flight that I've wanted to apply to git-for-windows/git and microsoft/git for testing. (Examples include maintenance builtin and parallel checkout.)

**Comment by dscho** [comment]
I concur, there is nothing you could have done to make that easier, @peff. Refactorings frequently require refactorings downstream, and that's that.

I'm just glad that I hit those types of issues early now, with the `shears/*` branches being rebased onto the upstream integration branches in an Azure Pipeline. That way, I can investigate somewhat at leisure, and put `fixup???` commits on top of, say, `shears/seen`.

**Comment by peff** [comment]
Well, I could have _not_ refactored. I always wonder if these sorts of tree-wide refactorings and their fallout are worth it for something as small as a name change. But on the other hand, things like bad API names are papercuts, and they add up.  At any rate, it sounds like nobody is too mad. :)

**Pull request merged**
