### PR TITLE
RFC: mingw/linux build

### PR DESCRIPTION
**Pull request by max630**
Hi.

This is list of hacks I had to do to make the git crosscompile with mingw in Linux. I am not suggesting to merge it yet, just asking to discuss which of them are wrong and should be done differently and which could be added, and how to do it without breaking other platforms.

The head is built succesfully for win32 (so far it's my primary platform). The make command was:

    make -j2 CC=i686-w64-mingw32-gcc uname_S=MINGW MSYSTEM=MINGW32 \
     uname_R=2.0 NO_OPENSSL=1 NO_ICONV=1 ZLIB_PATH=$(LOCAL_ZLIB32) \
     NO_CURL=1 NO_GETTEXT=1 USE_LIBPCRE= \
     WINDRES=i686-w64-mingw32-windres RANLIB=i686-w64-mingw32-ranlib \
     AR=i686-w64-mingw32-ar NEEDS_LIBICONV=

I have not run tests yet (need to find out how to do it)

### CODE REVIEW

**Comment by dscho** [comment]
Thank you for your contribution! All in all, it is a good first version of a Pull Request. I offered advice and comments to improve it so it can be integrated into Git for Windows. IMO the most important part would be to make the commit messages a bit clearer, pointing out e.g. which environment you used (OS, package versions, etc), but nothing I read here (except the command line used for building) is really specific to Linux. So I would call it "Support cross-compiling Git for Windows" instead.

Looking forward to the next iteration of this Pull Request!

**Comment by max630** [comment]
Thank you. I'm cleaning it up and doing some more checks against different mingw versions I have around.

I think for convenience I should make a make variable (currently I name it MINGW_TARGET=w32 or w64) to trigger the cross compilation and put everything else into `config.mak.uname`. Does this sound good?

About build instructions: where do you think I should put them so others can see them? README.md does not seem to be correct place - it contains only short hello and a few links. INSTALL is very generic and does not seem to be a good place for copypastable command lines. If there were specific documentation about building for windows I would add it there, but I cannot find it in the sources.

**Comment by dscho** [comment]
> README.md does not seem to be correct place - it contains only short hello and a few links.

Maybe it would be a good idea to add a Wiki page about cross-compiling and link to that from the `README`? That way, people seeking information can find their way from the README but said file is not cluttered with information most people won't need, either.

**Comment by dscho** [comment]
@max630 any news?

**Comment by max630** [comment]
I'm progressing slowly. So far I'm here:

https://github.com/max630/git/commits/ea7dc93b3047fde4d949df9aa63b5a18ac851219

Still to investigate couple of options, then there are several failures in tests. I think it will take some more time.

**Comment by dscho** [comment]
Nice progress! There is no rush with this issue, as long as it is moving along smoothly, I am happy to keep the Pull Request open and assist as I can.

**Comment by max630** [comment]
Something like this.

The only unresolved problem is libiconv support. It is also missed from mingw64/linux, so originally I disabled it. But then some tests revealed that git actually behaves incorrectly without iconv. So now I'm balancing between fixind libiconv linking and adding a stub which uses native Win32 functions. It seems trivial to do but looks like win32 does not provide a way to get "codepage" from the encoding name, so I would have to hardcode it.

Meanwhile add warning for missing iconv because git behaves incorrectly and user should be informed about it.

**Comment by dscho** [comment]
I commented a bit, hopefully we can resolve this PR soon!

**Comment by tkelman** [comment]
> How certain are we that the OpenSSL libraries are unavailable for cross compilation? Same for cURL and PCRE.

I don't know of any sources where those are available as cross-compiled binaries from Debian or Ubuntu. However cross-compiled mingw-w64 binaries of these libraries are available on Fedora or openSUSE.

**Comment by max630** [comment]
I have found some ubuntu ppc with lots of libraries compiled, I think I should try to use that one.

**Comment by dscho** [comment]
@max630 Any progress?

**Comment by max630** [comment]
Hi. I've been trying different approaches and looks like this PR is not going to go anywhere. Even if I find all required libraries they probably will not be compatible with the ones shipped with official Git for Windows, and this would make deployment much harder. You can close this one then.

**Comment by dscho** [comment]
Thanks for confirming.

**Pull request closed without merging**
