### PR TITLE
Create CustomerCapInfo

### PR DESCRIPTION
**Pull request by Sphinx373**
Thanks for taking the time to contribute to Git!

Those seeking to contribute to the Git for Windows fork should see
http://gitforwindows.org/#contribute on how to contribute Windows specific
enhancements.

If your contribution is for the core Git functions and documentation
please be aware that the Git community does not use the github.com issues
or pull request mechanism for their contributions.

Instead, we use the Git mailing list (git@vger.kernel.org) for code and
documenatation submissions, code reviews, and bug reports. The
mailing list is plain text only (anything with HTML is sent directly
to the spam folder).

Nevertheless, you can use GitGitGadget (https://gitgitgadget.github.io/)
to conveniently send your Pull Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by PhilipOakley** [comment]
This does appear to be any way relevant to Git.

**Comment by Sphinx373** [comment]
Sorry, new with git, still working on learning it.

**Comment by PhilipOakley** [comment]
> Sorry, new with git, still working on learning it.

No Problems. It looked too like a bit of random spam...

**Comment by PhilipOakley** [comment]
> Sorry, new with git, still working on learning it.

No Problems. It looked too like a bit of random spam...

**Pull request closed without merging**
