### PR TITLE
git-gui: fix GIT_DIR handling for submodules.

### PR DESCRIPTION
**Pull request by oldium**
When dealing with submodule, the GIT_DIR might not be set. If it is not set
before, it cannot be unset and the execution ends with error:

  can't unset "env(GIT_DIR)": no such element in array

Fix this by checking if GIT_DIR can be unset.

### CODE REVIEW

**Comment by dscho** [comment]
This PR looks good to me, but in the meantime Git GUI has an active maintainer again, so may I ask you to rebase this and open a GitGitGadget PR? I.e.

1. `git remote add gitgitgadget https://github.com/gitgitgadget/git`
2. `git fetch gitgitgadget git-gui/master`
3. `git branch --set-upstream-to=gitgitgadget/git-gui/master`
4. `git rebase --onto @{u} HEAD^`
5. force-push
6. open a PR at https://github.com/gitgitgadget/git
7. ping me (or other active people) in the PR to get permission to use GitGitGadget
8. add a single comment `/submit` to send the patch off to the Git mailing list, Cc:ing the Git GUI maintainer

**Comment by oldium** [comment]
Git for Windows has different code for Git GUI, so this fix is specifically for Git for Windows. The main difference is commit ca2f9322876b7d3633ff3e8d03af9d43bf43b164, which is not present in mainline Git (and I actually do not understand why it is there).

**Comment by dscho** [comment]
> Git for Windows has different code for Git GUI, so this fix is specifically for Git for Windows. The main difference is commit [ca2f932](https://github.com/git-for-windows/git/commit/ca2f9322876b7d3633ff3e8d03af9d43bf43b164), which is not present in mainline Git

Oh, that's a good point!

> (and I actually do not understand why it is there).

Right. I did stumble over it a couple times, and once I tried to figure out what was the rationale, but also failed.

Maybe we should just revert the revert instead, i.e. drop it from Git for Windows' patches?

**Comment by oldium** [comment]
Yes, drop ca2f9322876b7d3633ff3e8d03af9d43bf43b164 together with a9af64ee54c9ff70508c848809b3edb9db4caf48.

**Comment by dscho** [comment]
> Yes, drop [ca2f932](https://github.com/git-for-windows/git/commit/ca2f9322876b7d3633ff3e8d03af9d43bf43b164) together with [a9af64e](https://github.com/git-for-windows/git/commit/a9af64ee54c9ff70508c848809b3edb9db4caf48).

I found the reason for ca2f932! Look at https://groups.google.com/d/msg/msysgit/FkdTopndAes/RXF_h8eAgW4J

**Comment by dscho** [comment]
Apparently, this failed (in a worktree with an initialized submodule):

> git gui
> # the following instructions are for clicking
> * Tools->Add...
> Enter Name: submodule update
> Enter Command: git submodule update
> * Add
> * Tools->submodule update
> 
> Error message is:
> "fatal: reference is not a tree: 543f8d61eb235820aecefde6e46ec90e9803a6d8
> "Unable to checkout '543f8d61eb235820aecefde6e46ec90e9803a6d8' in submodule path 'doc/git/html'"

@oldium you probably have a worktree with initialized submodule(s), right? Could you try whether the indicated bug is still there after reverting a9af64e and ca2f932?

**Comment by oldium** [comment]
Yes, I do. I will play with this a little bit.

**Comment by dscho** [comment]
@oldium thank you.

I dug a little further, and it seems that https://groups.google.com/d/msg/msysgit/FkdTopndAes/BRVBc95idk8J was intended to (quote:) "fix this properly", and that patch made it into Git's `master` via the merge bd08ecc487f3b515196cc4096094799a02de6ae3 (the patch in question is 74ae14199dfb4b3b22a10d3dcecb62b457245564).

So yes, it should be possible for us to just drop those two commits.

If your testing confirms this, would you terribly mind updating this here PR accordingly? It is unfortunately too late for v2.25.0-rc1 (which is already in the process of being released), but it will make it into -rc2 at least.

**Comment by oldium** [comment]
I tried the following which I found in the mailing list:

```bash
git clone git://repo.or.cz/msysgit.git
cd msysgit
git submodule update --init
git gui
# the following instructions are for clicking
* Tools->Add...
Enter Name: submodule update
Enter Command: git submodule update
* Add
* Tools->submodule update
```

Result: 
image

**Comment by dscho** [comment]
Perfect! So we can drop this revert after slightly less than 10 years ;-)

**Comment by oldium** [comment]
Updated PR.

**Comment by dscho** [comment]
Thank you @oldium!

**Comment by oldium** [comment]
You are welcome, @dscho!

**Pull request merged**
