### PR TITLE
Clean up Git for Windows' branch thicket

### PR DESCRIPTION
**Pull request by dscho**
I tried to make future rebases easier by merging `main` into v2.40.1.windows.1 in #4412, but that didn't work.

So let's clean up the branch thicket. with the result being intentionally tree-same to `main`. This _will_ help with the upcoming v2.41.0-rc0 rebase.

### CODE REVIEW

**Comment by dscho** [comment]
<details><summary>Range-diff</summary>



* 2:  a0e22dec5ce5 =   1:  b9a5d65d5e43 windows: ignore empty `PATH` elements
* 3:  6c34e04a8ecb =   2:  35c23c2c0fec is_Cygwin: avoid `exec`ing anything
* 4:  c72f6566f71a =   3:  38fdcb8492d2 Move is_<platform> functions to the beginning
* 5:  ca4bb2dc82d8 =   4:  0958d0b73d65 Move the `_which` function (almost) to the top
* 6:  7a3c99084c7c =   5:  ad32e34e5fbe Work around Tcl's default `PATH` lookup
* 7:  7f7c0569ed99 =   6:  31ff02639550 gitk(Windows): avoid inadvertently calling executables in the worktree
* 8:  830a396acec8 =   7:  1167bf963002 t9350: point out that refs are not updated correctly
* 9:  0f83634588a5 =   8:  6100b2887e0a transport-helper: add trailing --
* 10:  22622fd1006c =   9:  c37adfedf91e remote-helper: check helper status after import/export
* 11:  1394407ef2e8 =  10:  d91acc4bdb5c mingw: demonstrate a problem with certain absolute paths
* 12:  03defea911ba =  11:  c81e790218a5 Always auto-gc after calling a fast-import transport
* 15:  0275003fad25 =  12:  8c8613674f88 mingw: allow absolute paths without drive prefix
* 18:  a78531732b98 =  13:  ab1cad2ab9b3 mingw: include the Python parts in the build
* 19:  bea444fafb60 =  14:  ce4f4eea3ca8 win32/pthread: avoid name clashes with winpthread
* 13:  b689710ec69e =  15:  1ee40d0073d7 gitk: prevent overly long command lines
* 14:  1a68b75b0ba7 =  16:  6b63ca6d6b11 clean: do not traverse mount points
* 20:  eb2fdee3dcda =  17:  60db7e3fa469 git-compat-util: avoid redeclaring _DEFAULT_SOURCE
* 16:  774d1e0f9ad7 =  18:  a14bbecd695b mingw: change core.fsyncObjectFiles = 1 by default
* 17:  9fce603582cc =  19:  7c6a87241fe8 gitk: Escape file paths before piping to git log
* 21:  3f370402674e =  20:  04aadf60d859 clean: remove mount points when possible
* 22:  37f1e221947a =  21:  7cc201e66d3c Import the source code of mimalloc v2.0.9
* 23:  55ab49408b7f =  22:  1aab3274f361 mimalloc: adjust for building inside Git
* 24:  7f98ea0add29 =  23:  2b983259cf8c mimalloc: offer a build-time option to enable it
* 25:  baabcde44a31 =  24:  e3504711757f mingw: use mimalloc
* 26:  5495ccea4f43 =  25:  5166a354e437 Config option to disable side-band-64k for transport
* 27:  b7ea10f42d9c =  26:  bb3100bf168f mingw: make sure `errno` is set correctly when socket operations fail
* 28:  7977c3321d35 =  27:  041cc54e9423 mingw: do resolve symlinks in `getcwd()`
* 33:  1ee8a210c6ef =  28:  c72a078d600a mingw: ensure valid CTYPE
* 29:  87107d2aec2e =  29:  5eaf62c7e9d6 mingw: demonstrate a `git add` issue with NTFS junctions
* 34:  af7e91fcf6eb =  30:  6473b0267fc6 mingw: allow `git.exe` to be used instead of the "Git wrapper"
* 32:  b311ee0d5994 =  31:  2d3f35f5f128 strbuf_realpath(): use platform-dependent API if available
* 36:  70b589816213 =  32:  474e846a1865 mingw: ignore HOMEDRIVE/HOMEPATH if it points to Windows' system directory
* 30:  8bed97801efe =  33:  1477e6d2656f mingw: fix fatal error working on mapped network drives on Windows
* 31:  42f7c21f91c7 =  34:  640a3ac90728 clink.pl: fix MSVC compile script to handle libcurl-d.lib
* 113:  77546445c6e8 =  35:  28ac23eeb441 mingw: implement a platform-specific `strbuf_realpath()`
* 35:  72e17edf985f =  36:  f7a89625fc1f vcxproj: unclash project directories with build outputs
* 38:  c36a89b54512 =  37:  9f0b0ac4600a t5505/t5516: allow running without `.git/branches/` in the templates
* 39:  862f3732ef2c =  38:  cf9ae060709f t5505/t5516: fix white-space around redirectors
* 37:  eb5311f957d6 =  39:  10009a675180 http: use new "best effort" strategy for Secure Channel revoke checking
* 40:  ad6c5f4804af =  40:  f8a705f4307c t3701: verify that we can add *lots* of files interactively
* 41:  0322b7467576 =  41:  9233143ef973 git add -i: handle CR/LF line endings in the interactive input
* 42:  de411a4d706f =  42:  1a0385febdea commit: accept "scissors" with CR/LF line endings
* 45:  b9947017a95d =  43:  c070cd7df95f clink.pl: fix libexpatd.lib link error when using MSVC
* 46:  59bccc1a14ca =  44:  90d65f9c1120 Makefile: clean up .ilk files when MSVC=1
* 47:  5a6ca20dff63 =  45:  7efa088e7810 vcbuild: add support for compiling Windows resource files
* 43:  295fb80008e5 =  46:  b6581ef200d6 t0014: fix indentation
* 44:  8f0ed3a1c0b9 =  47:  f0c210dea431 git-gui: accommodate for intent-to-add files
* 48:  c6b92ee91638 =  48:  cf8b82dd3607 config.mak.uname: add git.rc to MSVC builds
* 49:  049222b08780 =  49:  25f10a8e9a6e clink.pl: ignore no-stack-protector arg on MSVC=1 builds
* 50:  f77f5f8b13d3 =  50:  523d6de2d602 clink.pl: move default linker options for MSVC=1 builds
* 51:  b3aa5c86eb52 =  51:  0a93e0e8ee78 buildsystems: remove duplicate clause
* 52:  d63057988d84 =  52:  96e076f08226 vcxproj: handle resource files, too
* 53:  0208060a62eb =  53:  429726d86733 vcxproj: ignore -fno-stack-protector and -fno-common
* 54:  485bd0c65bf9 =  54:  b9da02a5f720 vcxproj: handle GUI programs, too
* 55:  2e930a26051b =  55:  10035c39f080 win32: add a helper to run `git.exe` without a foreground window
* 56:  cce1f4c17044 =  56:  5efc1e28132c git maintenance: avoid console window in scheduled tasks on Windows
* 57:  3713cc091f2c =  57:  80a6511c42ed vcpkg_install: detect lack of Git
* 60:  1fd14710bcf3 =  58:  b0d817b0463c cmake: install headless-git.
* 58:  42bc22e3ddf4 =  59:  d2d0bbae0bc4 vcpkg_install: add comment regarding slow network connections
* 59:  a34af56bcb68 =  60:  adff1270083b vcxproj: support building Windows/ARM64 binaries
* 61:  df20ce0d34c4 =  61:  966ec6f7664a vcbuild: install ARM64 dependencies when building ARM64 binaries
* 62:  7f32b22e6597 =  62:  1907233b381e vcbuild: add an option to install individual 'features'
* 63:  e2dabc3432e8 =  63:  f5ab0fb8719c cmake: allow building for Windows/ARM64
* 64:  b6f98ca7aa2d =  64:  313880e6c2cf ci(vs-build) also build Windows/ARM64 artifacts
* 65:  0c5ef90d0e0c =  65:  85d3ebf2d654 Add schannel to curl installation
* 66:  463a941f61f5 =  66:  f5d61ba1d032 cmake(): allow setting HOST_CPU for cross-compilation
* 67:  c1f283c0e1ad =  67:  1b12c938042a ci(vs-build): download the vcpkg artifacts using a dedicated Action
* 68:  3a6f9e11cda7 =  68:  00b01b976140 mingw: allow for longer paths in `parse_interpreter()`
* 71:  6dfd5bc1050f =  69:  8fc3ab6e6c29 CMake: default Visual Studio generator has changed
* 72:  2939bf1aad3c =  70:  d8c2962c3940 .gitignore: add Visual Studio CMakeSetting.json file
* 73:  5ff027b4fafd =  71:  70695181554a subtree: update `contrib/subtree` `test` target
* 74:  d53454636d34 =  72:  439f794ea426 CMakeLists: add default "x64-windows" arch for Visual Studio
* 69:  0a8f9f3cbc36 =  73:  7848fd6a74ce compat/vcbuild: document preferred way to build in Visual Studio
* 70:  9b98888adef0 =  74:  b439980dad30 http: optionally send SSL client certificate
* 75:  9874ea9db97c =  75:  16dcf3fd602c ci: run `contrib/subtree` tests in CI builds
* 77:  f48b4282435e =  76:  b5f4b9cc173d CMake: show Win32 and Generator_platform build-option values
* 76:  cc2bc763bd74 =  77:  7af78e314404 hash-object: demonstrate a >4GB/LLP64 problem
* 80:  6f400ce31476 =  78:  7e0c0a657a17 hash_object_file_literally(): use size_t
* 81:  75d5cc5e91a5 =  79:  4aadf89e465b object-file.c: use size_t for header lengths
* 82:  947b24a321ac =  80:  18d2b20f6589 hash algorithms: use size_t for section lengths
* 83:  dbcb524bcff4 =  81:  f4c97bf930bc hash-object --stdin: verify that it works with >4GB/LLP64
* 84:  69e78c099aa1 =  82:  244c76d3a672 hash-object: add another >4GB/LLP64 test case
* 78:  1f2569b48024 =  83:  9d12be73488e init: do parse _all_ core.* settings early
* 79:  09acd1989de3 =  84:  554131511d16 Enable the built-in FSMonitor as an experimental feature
* 85:  355bdd8dcf1c =  85:  96a961cc84ce hash-object: add a >4GB/LLP64 test case using filtered input
* 90:  41da73ac341e =  86:  a5ec11ce9788 vcxproj: allow building with `NO_PERL` again
* 86:  67957436dba5 =  87:  af9e01f2cd4e setup: properly use "%(prefix)/" when in WSL
* 91:  e12c22cb3744 =  88:  8326b8c98769 vcxproj: require C11
* 87:  c05c8d5bd001 =  89:  33db4e6be8a6 compat/mingw.c: do not warn when failing to get owner
* 88:  ee21727082f7 =  90:  4341636aae19 mingw: $env:TERM="xterm-256color" for newer OSes
* 89:  9c927f8aa61c =  91:  6dd773f9f6af winansi: check result and Buffer before using Name
* 93:  387c146acd93 =  92:  091d9578aab6 Add config option `windows.appendAtomically`
* 92:  3f89b6b9b581 =  93:  19442a4e4f6d vcxproj: ignore the `-pedantic` option
* 94:  bcaca04417a1 =  94:  b05c68895257 vcxproj: include reftable when committing `.vcxproj` files
* 95:  940e45feb1b6 =  95:  fb108dfd0e56 vcxproj: handle libreftable_test, too
* 96:  1356b7e8675d =  96:  0c115263e406 vcxproj: avoid escaping double quotes in the defines
* 97:  ab8970b68715 =  97:  1f262f1cb6ab ci: adjust Azure Pipeline for `runs_on_pool`
* 98:  74360c6b50ee =  98:  820d5271b44e ci: stop linking the `prove` cache
* 99:  7ff2836f1c5f =  99:  e43e7a28c784 ci: reinstate Azure Pipelines support
* 100:  3c1d84633402 = 100:  42285c9af8d3 azure-pipeline: drop the `GETTEXT_POISON` job
* 101:  8acdee348489 = 101:  2bef2f76030e azure-pipeline: stop hard-coding `apt-get` calls
* 102:  7a0a5c8701ed = 102:  c28ddf6a072e azure-pipeline: drop the code to write to/read from a file share
* 103:  56c4e458337c = 103:  9e1a847b2e4d azure-pipeline: use partial clone/parallel checkout to initialize minimal-sdk
* 104:  3c019aea2245 = 104:  cfe5be0e34ae azure-pipeline: downcase the job name of the `Linux32` job
* 105:  a948d83ea4eb = 105:  975c604a6e13 azure-pipeline: run static-analysis on jammy
* 106:  1d4f7adedc7a = 106:  d17d7ff7035b bswap.h: add support for built-in bswap functions
* 107:  b0e70a9cf066 = 107:  0bb8af23fb9a config.mak.uname: add support for clangarm64
* 108:  7af2eadafe49 = 108:  f7c3a3f3efe6 MinGW: link as terminal server aware
* 109:  4e2c17c2c2d3 = 109:  7f31c276a218 Fix Windows version resources
* 110:  6b1a1254c197 = 110:  1e24e7b82be9 ci: create clangarm64-build.yml
* 111:  f8e90133236f = 111:  a08522c5786c status: fix for old-style submodules with commondir
* 112:  c8737b0d3aba = 112:  545a87518088 windows: skip linking `git-<command>` for built-ins
* 1:  2540183a7947 = 113:  e56e77b0f184 windows: fix Repository>Explore Working Copy
* 114:  086b76dbf6d9 = 114:  8f9dc6c48a6d Win32: make FILETIME conversion functions public
* 115:  7a1af9eafa9b = 115:  0e04dcb0f536 Win32: dirent.c: Move opendir down
* 116:  74347a2e4836 = 116:  a6b0b6837982 mingw: make the dirent implementation pluggable
* 117:  7a8f1c4849ee = 117:  72c2f34950c1 Win32: make the lstat implementation pluggable
* 118:  0fd950a95c13 = 118:  a79319a783b7 add infrastructure for read-only file system level caches
* 119:  60c30a5a4ce2 = 119:  4b28491c446f mingw: add a cache below mingw's lstat and dirent implementations
* 120:  0b571cfca4b8 = 120:  1ae5754f16ab fscache: load directories only once
* 121:  b5c4e7a0c151 = 121:  9e9af78fe339 fscache: add key for GIT_TRACE_FSCACHE
* 122:  8418318f978b = 122:  d36a790c6eb2 fscache: remember not-found directories
* 123:  1a275846e7ec = 123:  e22aea23cbd2 fscache: add a test for the dir-not-found optimization
* 124:  fba7669f5f82 = 124:  13014cb92de9 add: use preload-index and fscache for performance
* 125:  71473241b87e = 125:  de4ccaf8ca3d dir.c: make add_excludes aware of fscache during status
* 126:  923873ec857a = 126:  a143a5784f86 fscache: make fscache_enabled() public
* 127:  a23a7e0c6571 = 127:  60b79ac9013b dir.c: regression fix for add_excludes with fscache
* 128:  da341dfc76e2 = 128:  03cef85da536 fetch-pack.c: enable fscache for stats under .git/objects
* 129:  a74abe962854 = 129:  a27a96c1e330 checkout.c: enable fscache for checkout again
* 130:  6b8678679026 = 130:  7f4b4f08377f Enable the filesystem cache (fscache) in refresh_index().
* 131:  c58d8a5405d3 = 131:  b4a96edd38d7 fscache: use FindFirstFileExW to avoid retrieving the short name
* 132:  3b4c5c9ceeeb = 132:  6735873d2e36 status: disable and free fscache at the end of the status command
* 133:  ed5e0a34bba8 = 133:  dcd6f4bb1053 fscache: add GIT_TEST_FSCACHE support
* 134:  f362f2081cb0 = 134:  4b26f76f416d fscache: add fscache hit statistics
* 135:  90ca12490409 = 135:  17ae1bb856b6 mem_pool: add GIT_TRACE_MEMPOOL support
* 136:  eb683d090881 = 136:  9f16da2e8390 fscache: fscache takes an initial size
* 137:  484c3384e15d = 137:  4938b3036f60 fscache: update fscache to be thread specific instead of global
* 138:  08caca68bd13 = 138:  cec323a33171 fscache: teach fscache to use mempool
* 139:  11249e31112e = 139:  008243861016 fscache: make fscache_enable() thread safe
* 140:  462e0cea68c4 = 140:  b3cebf7b84bd fscache: teach fscache to use NtQueryDirectoryFile
* 141:  f4ba6f166476 = 141:  8563c901699b unpack-trees: enable fscache for sparse-checkout
* 142:  a56096282434 = 142:  36193fc7e73d fscache: remember the reparse tag for each entry
* 143:  fd2f21c059db = 143:  0adf61214b79 fscache: implement an FSCache-aware is_mount_point()
* 144:  ed884ea5da19 = 144:  9b6d2531dfb3 git-gui: provide question helper for retry fallback on Windows
* 145:  688e38097b80 = 145:  e518e9173fbf clean: make use of FSCache
* 146:  aa6677cce338 = 146:  0c0972f89b41 git gui: set GIT_ASKPASS=git-gui--askpass if not set yet
* 151:  9315e8299755 = 147:  aa1f4432a52a gitk: Unicode file name support
* 147:  801ff2f0fe0e = 148:  790164795644 git-gui--askyesno: fix funny text wrapping
* 152:  351952780608 = 149:  d31f3c33538e gitk: Use an external icon file on Windows
* 148:  b60b6b955312 = 150:  276784689a85 git-gui--askyesno: allow overriding the window title
* 153:  8c3e46a8af12 = 151:  3fd74e9f1b68 gitk: fix arrow keys in input fields with Tcl/Tk >= 8.6
* 149:  2a1f2aaedd2f = 152:  ea2f2ab3a527 respect core.hooksPath, falling back to .git/hooks
* 150:  c283520dd6ee = 153:  cb7d92da80fa git-gui--askyesno (mingw): use Git for Windows' icon, if available
* 154:  f820eb44a635 = 154:  c00f6b575323 gitk: make the "list references" default window width wider
* 155:  7f38830df111 = 155:  c971f81cb1e1 pack-objects (mingw): demonstrate a segmentation fault with large deltas
* 156:  9f326e02c7d5 = 156:  290ea3f8633b mingw: support long paths
* 157:  540e7682772e = 157:  444022170714 Win32: fix 'lstat("dir/")' with long paths
* 158:  ba55fb24a4fa = 158:  cddb9d4a094d compat/fsmonitor/fsm-*-win32: support long paths
* 159:  51d438a6f330 = 159:  41325bddb97b mingw: Support `git_terminal_prompt` with more terminals
* 160:  741db8f516df = 160:  3d1e091d850f compat/terminal.c: only use the Windows console if bash 'read -r' fails
* 161:  1cbf16ff11c4 = 161:  b7928ec42e31 mingw (git_terminal_prompt): do fall back to CONIN$/CONOUT$ method
* 162:  98afeb04906c = 162:  868346a89327 Unbreak interactive GPG prompt upon signing
* 164:  5afd91cde002 = 163:  02051fa9d9ed strbuf_readlink: don't call readlink twice if hint is the exact link size
* 165:  868226279ba1 = 164:  86e6b085735d strbuf_readlink: support link targets that exceed PATH_MAX
* 166:  1766e8d88d08 = 165:  b1c51db413fe lockfile.c: use is_dir_sep() instead of hardcoded '/' checks
* 163:  aee203723c0c = 166:  6d21a0e8661f clean: suggest using `core.longPaths` if paths are too long to remove
* 167:  c044872b3436 = 167:  072d6fefb4b6 Win32: don't call GetFileAttributes twice in mingw_lstat()
* 168:  7d4c278e6e06 = 168:  40c66f292584 Win32: implement stat() with symlink support
* 169:  7681e24331f2 = 169:  ed776b0cac97 Win32: remove separate do_lstat() function
* 170:  dd2114e7d029 = 170:  50a3e1b6ff96 Win32: let mingw_lstat() error early upon problems with reparse points
* 171:  ba36f8ea8845 = 171:  5cc6300cd236 mingw: teach fscache and dirent about symlinks
* 172:  cccfe0ad60df = 172:  c7fbb579ed5c Win32: lstat(): return adequate stat.st_size for symlinks
* 173:  9b68495d6d9e = 173:  d4368ffbfe05 Win32: factor out retry logic
* 174:  6fd5b32cee1e = 174:  c7b8068e80ed Win32: change default of 'core.symlinks' to false
* 175:  2559b5f920fe = 175:  d79da6c2b8da Win32: add symlink-specific error codes
* 176:  432e95e9303c = 176:  20bd6d6eb4bb Win32: mingw_unlink: support symlinks to directories
* 177:  865520d2774e = 177:  df59e6aad371 Win32: mingw_rename: support renaming symlinks
* 178:  7e5b9b6ad774 = 178:  63873b6a9ce6 Win32: mingw_chdir: change to symlink-resolved directory
* 179:  202af30b1919 = 179:  66494a8b791e Win32: implement readlink()
* 180:  a106b3f58893 = 180:  3fc1d4a8c1e8 mingw: lstat: compute correct size for symlinks
* 181:  df3c8416e6a8 = 181:  6042601e7a08 Win32: implement basic symlink() functionality (file symlinks only)
* 182:  fe14d7d5a32c = 182:  5f68cce434d3 Win32: symlink: add support for symlinks to directories
* 183:  6eae24511cd5 = 183:  5e22f758acfa mingw: try to create symlinks without elevated permissions
* 184:  5bb4c6411552 = 184:  63117f18f69f mingw: emulate stat() a little more faithfully
* 185:  c7cf66a40a2b = 185:  c71ae46fc7de mingw: special-case index entries for symlinks with buggy size
* 186:  8d37cf651bc8 = 186:  3eed1d8eab24 mingw: introduce code to detect whether we're inside a Windows container
* 187:  261590bbba7b = 187:  0457c6c5fcde mingw: when running in a Windows container, try to rename() harder
* 188:  4a531cb30cb7 = 188:  e3ba9a9a3f47 mingw: move the file_attr_to_st_mode() function definition
* 190:  e820900faab3 = 189:  f5cf1d6fd9a3 Win32: symlink: move phantom symlink creation to a separate function
* 189:  6f8b38cb8cd1 = 190:  c7efea1ce00d mingw: Windows Docker volumes are *not* symbolic links
* 191:  f4a211f39f97 = 191:  db7a151594f9 Introduce helper to create symlinks that knows about index_state
* 192:  0fa2f7f927d3 = 192:  18fb1ca756b3 mingw: allow to specify the symlink type in .gitattributes
* 193:  f1fe3e1342c6 = 193:  8c7936209d6d Win32: symlink: add test for `symlink` attribute
* 194:  783ac9d2bda5 = 194:  814089e5d834 mingw: explicitly specify with which cmd to prefix the cmdline
* 195:  2da822e532d1 = 195:  7fff42fc5c2f mingw: when path_lookup() failed, try BusyBox
* 196:  7814c71fa72c = 196:  1e3b12b1be1c test-lib: avoid unnecessary Perl invocation
* 197:  57e44db17841 = 197:  9158eccfc3d4 test-tool: learn to act as a drop-in replacement for `iconv`
* 198:  2318a0388b5c = 198:  bc000aebd8c4 tests(mingw): if `iconv` is unavailable, use `test-helper --iconv`
* 199:  14f286960973 = 199:  5b940bc265ca gitattributes: mark .png files as binary
* 200:  94b180ce247e = 200:  a7dcbe475932 tests: move test PNGs into t/lib-diff/
* 201:  7b31f8d8188b = 201:  096f7234ca78 tests: only override sort & find if there are usable ones in /usr/bin/
* 202:  de3782956880 = 202:  91cc32ded8fd tests: use the correct path separator with BusyBox
* 203:  9cafe11badc6 = 203:  93a658cc9957 mingw: only use Bash-ism `builtin pwd -W` when available
* 204:  8c80d34b9c27 = 204:  9f71981e973b tests (mingw): remove Bash-specific pwd option
* 205:  ba387198054a = 205:  8cdfde906af5 test-lib: add BUSYBOX prerequisite
* 206:  715e0fe0071d = 206:  43c97b662ac2 t5003: use binary file from t/lib-diff/
* 207:  638408e79a87 = 207:  4d396719437b t5532: workaround for BusyBox on Windows
* 208:  7dbcc26b0ed6 = 208:  7025fd804e02 t5605: special-case hardlink test for BusyBox-w32
* 209:  fd4298c080a1 = 209:  a7626e732ec1 t5813: allow for $PWD to be a Windows path
* 210:  97edb5e37732 = 210:  7cb189fc26dd t9200: skip tests when $PWD contains a colon
* 211:  410862550ff7 = 211:  69c4d06a2869 mingw: add a Makefile target to copy test artifacts
* 212:  729d809a1664 = 212:  b970b6f5fd26 mingw: kill child processes in a gentler way
* 213:  66e0377318f1 = 213:  938aafbff447 mingw: do not call xutftowcs_path in mingw_mktemp
* 214:  061cae560196 = 214:  b8e9e4034407 mingw: really handle SIGINT
* 215:  a7d8dc6f6aa7 = 215:  edd9e6d4ee2b Partially un-revert "editor: save and reset terminal after calling EDITOR"
* 219:  1744ca1875d2 = 216:  1ce742060758 Describe Git for Windows' architecture [no ci]
* 220:  b945aa208ba1 = 217:  4b09adb8325d Modify the Code of Conduct for Git for Windows
* 221:  5ae39ab4d362 = 218:  13541e323a43 CONTRIBUTING.md: add guide for first-time contributors
* 222:  f2c43a0a8825 = 219:  3d206ed03fef README.md: Add a Windows-specific preamble
* 223:  180980998142 = 220:  e33c9f93cff9 Add an issue template
* 216:  c7fdd31e3e70 = 221:  355bc19cde6f reset: reinstate support for the deprecated --stdin option
* 217:  591f3a520e47 <   -:  ------------ mingw: deprecate old-style runtime-prefix handling in interpolate_path()
* 218:  4acff703f6f5 = 222:  3237c56caf93 fsmonitor: reintroduce core.useBuiltinFSMonitor
* 224:  bab7843d4a12 = 223:  f05e41621080 Add a GitHub workflow to monitor component updates
* 225:  0ad36fcf19bd = 224:  1d87f670dd2a Modify the GitHub Pull Request template (to reflect Git for Windows)
* 226:  d889cb9d86cf = 225:  3a24d4fc9030 .github: Add configuration for the Sentiment Bot
* 227:  ec4b42ff8ece = 226:  069fa4c3b157 Document how $HOME is set on Windows
* 228:  2c49e512ee98 = 227:  0db8d08d543a SECURITY.md: document Git for Windows' policies
* 229:  8ee41615ed54 <   -:  ------------ Drop the old-style runtime-prefix handling in interpolate_path()

</details>

**Review by jeffhostetler — APPROVED** [review]
rubberstamping this since we are tree-same.  let me know if you want a more detailed review.

**Comment by dscho** [comment]
> rubberstamping this since we are tree-same. let me know if you want a more detailed review.

Thank you!

I am comfortable enough with the range-diff that I'll go forward and merge this. The rush with merging this comes from the fact that 1) this coming Monday is -rc0 day, and 2) I need a [snapshot](https://wingit.blob.core.windows.net/files/index.html) with the new MSYS2 runtime world order (where `git-sdk-32` has `msys2-runtime-3.3` installed, deviating from `git-sdk-64`, which has `msys2-runtime` that I just upgraded to v3.4.6).

**Comment by dscho** [comment]
Darn, I should have pushed directly, not hit the Merge button :-(

**Comment by dscho** [comment]
> Darn, I should have pushed directly, not hit the Merge button :-(

Fixed it, by doing _another_ clean-up and pushing a02883fa26d13fdbbc96e50ab163e1a21dfa0476 directly.

**Pull request merged**
