### PR TITLE
Better MSys PTY detection

### PR DESCRIPTION
**Pull request by kblees**
This fixes issue #85 and part of issue #74

### CODE REVIEW

**Comment by dscho** [comment]
Sorry about the amount of comments, but I am pretty jazzed about your approach: it makes much more sense than my original code.

**Comment by dscho** [comment]
See https://github.com/git-for-windows/git/compare/master...dscho:kb/msys-tty for my suggested changes.

@kblees don't worry if you do not have time to review or comment, I'll just go with what I have, perform a merging rebase onto 2.3.6 and then we'll take it from there, okay?

**Comment by kblees** [comment]
> don't worry if you do not have time to review or comment, I'll just go with what I have

@dscho Thanks, I've been AFK for the past two weeks, still working off the backlog...

**Comment by dscho** [comment]
No worries! Hope you had a good time.

**Pull request merged**
