### PR TITLE
Switching out undocumented NtQueryObject for GetFileInformationByHandleEx

### PR DESCRIPTION
**Pull request by assarbad**
- Switching out undocumented (NT native) function `NtQueryObject()` for
  the documented Win32 alternative `GetFileInformationByHandleEx()`.
- Does not fix the stalls with `git push` for `git://`-protocol servers
  on Windows, but it's an improvement nevertheless because it avoids
  an undocumented function in favor for a documented one.

This is mostly meant to draw the attention to what I've tried so far ... unfortunately the underlying issue persists even with this change.

xref #2376

### CODE REVIEW

**Comment by dscho** [comment]
@assarbad what's your take on this PR, should it be left open, still?

**Comment by assarbad** [comment]
If you like, I can update it to match the current state of the code. I haven't looked at it in at least 2 years.

Otherwise, if you don't find it desirable to use the official Win32 API, that's also fine with me and it can be closed.

**Comment by dscho** [comment]
Wasn't the original idea to improve performance? If so, I suspect that the (undocumented) call provides better performance.

**Comment by dscho** [comment]
@assarbad are you planning on working on this any further?

**Comment by assarbad** [comment]
> Wasn't the original idea to improve performance? If so, I suspect that the (undocumented) call provides better performance.

Technically, that may even be the case. But again, it'd be the documented alternative on which you can rely going forward (and it's a fairly shallow wrapper around the native function in this case, unlike some other Win32 API functions).

> @assarbad are you planning on working on this any further?

@dscho Since you seem to prefer the existing use of the NT native function, I guess there's nothing left to do here.

It doesn't resolve the blocking pipes issue #2376 either way 😑

**Comment by dscho** [comment]
Thank you for explaining your thinking, and I agree that we can leave this closed.

**Pull request closed without merging**
