### PR TITLE
Rebase to v2.47.0-rc1

### PR DESCRIPTION
**Pull request by dscho**
<details><summary>Range-diff relative to </summary>

* 1:  42c72f6692e2 =   1:  f4a21be1ed9a gitk(Windows): avoid inadvertently calling executables in the worktree
* 2:  75259a3bb5ee =   2:  4d1fa2f4130e t9350: point out that refs are not updated correctly
* 3:  29502049d595 =   3:  9c8ddeb5019a transport-helper: add trailing --
* 4:  f6a108767c32 =   4:  0388e0f48983 remote-helper: check helper status after import/export
* 5:  f577d4f797ee =   5:  a2fc5f4becdb mingw: demonstrate a problem with certain absolute paths
* 8:  3f57ab8cbd36 =   6:  19e2851cb280 Always auto-gc after calling a fast-import transport
* 9:  4b660c29ee13 =   7:  591248d76c79 mingw: allow absolute paths without drive prefix
* 7:  bc5dcde831d6 =   8:  241c1dfcbc55 mingw: include the Python parts in the build
* 6:  932c431c2ff8 =   9:  a6c8bed98c3d clean: do not traverse mount points
* 11:  61f646546168 =  10:  dff182e19839 win32/pthread: avoid name clashes with winpthread
* 10:  0c35494084a5 =  11:  39566c5d6476 clean: remove mount points when possible
* 12:  a55ffbd51fd5 =  12:  34ba44beadf0 git-compat-util: avoid redeclaring _DEFAULT_SOURCE
* 13:  be7959fcf4a6 =  13:  f603a03fb10d Import the source code of mimalloc v2.1.2
* 14:  89248e766ba1 =  14:  25f63e8b667e mimalloc: adjust for building inside Git
* 15:  c9ca7517ad89 =  15:  f699fdae2dc9 mimalloc: offer a build-time option to enable it
* 16:  b3e07b980fe6 =  16:  cac17949c120 mimalloc: use "weak" random seed when statically linked
* 17:  260111b11213 =  17:  6021bfb4b890 mingw: use mimalloc
* 18:  6965bc6be627 =  18:  8eeb5a09b3e0 transport: optionally disable side-band-64k
* 20:  8984fef3ae8e =  19:  228a2bafaeaa mingw: make sure `errno` is set correctly when socket operations fail
* 21:  53d32aee0336 =  20:  65bfabdf9192 mingw: do resolve symlinks in `getcwd()`
* 22:  7fb700bbce30 =  21:  c08df1433a47 mingw: fix fatal error working on mapped network drives on Windows
* 19:  82899905d3ab =  22:  e78152909142 mingw: demonstrate a `git add` issue with NTFS junctions
* 23:  b4fa6a6777db =  23:  c78ac595c3a4 clink.pl: fix MSVC compile script to handle libcurl-d.lib
* 24:  89be22f8df80 =  24:  64b04e8d3c2c mingw: ensure valid CTYPE
* 26:  977e2f0412e6 =  25:  ae71902018fb strbuf_realpath(): use platform-dependent API if available
* 25:  cbbb7f633d69 =  26:  40e207d8772d mingw: allow `git.exe` to be used instead of the "Git wrapper"
* 28:  c9852612b9b8 =  27:  b680f09a453a mingw: implement a platform-specific `strbuf_realpath()`
* 29:  10567fe2caf5 =  28:  1b42afc27ee5 vcxproj: unclash project directories with build outputs
* 27:  c5ffba691b09 =  29:  2e0c2aba89a6 mingw: ignore HOMEDRIVE/HOMEPATH if it points to Windows' system directory
* 32:  0a7c0299743f =  30:  cfcc09909ef5 http: use new "best effort" strategy for Secure Channel revoke checking
* 30:  cf6faf0c52df =  31:  f1f23e45b7db t5505/t5516: allow running without `.git/branches/` in the templates
* 31:  6a868130747f =  32:  dd2a52565b6e t5505/t5516: fix white-space around redirectors
* 33:  6525eb868133 =  33:  72487ea853be t3701: verify that we can add *lots* of files interactively
* 34:  d79c6250ea83 =  34:  6288c4db79f7 git add -i: handle CR/LF line endings in the interactive input
* 35:  04466982ca30 =  35:  4958dbf9ecdc commit: accept "scissors" with CR/LF line endings
* 36:  5b5e5de3cd4a =  36:  abfefcfea750 t0014: fix indentation
* 37:  1ca48edd5324 =  37:  64d500c9e1a8 git-gui: accommodate for intent-to-add files
* 38:  0756a77a3725 =  38:  526a67e27c29 clink.pl: fix libexpatd.lib link error when using MSVC
* 39:  5f048eba15d0 =  39:  980c640d4ee2 Makefile: clean up .ilk files when MSVC=1
* 40:  6b9547e3dbf1 =  40:  b3909cb24f9c vcbuild: add support for compiling Windows resource files
* 41:  c9c34c382b7e =  41:  991b6bc03c4b config.mak.uname: add git.rc to MSVC builds
* 42:  84fd96a13e1c =  42:  dd1e6782eabd clink.pl: ignore no-stack-protector arg on MSVC=1 builds
* 43:  3a4cc66f5169 =  43:  048c378a22cc clink.pl: move default linker options for MSVC=1 builds
* 44:  79964ea45da6 =  44:  af990b72be5c buildsystems: remove duplicate clause
* 45:  455cd8027047 =  45:  c11788b63bc1 vcxproj: handle resource files, too
* 46:  2f1c159fd038 =  46:  d9a9273a3648 vcxproj: ignore -fno-stack-protector and -fno-common
* 47:  c4431a6a1095 =  47:  76ca105db8d1 vcxproj: handle GUI programs, too
* 48:  22103744ec2c =  48:  e24174df893a vcpkg_install: detect lack of Git
* 50:  19199f299109 =  49:  c848dd0ae469 vcpkg_install: add comment regarding slow network connections
* 51:  820f045c251b =  50:  673ea43e5a4e vcxproj: support building Windows/ARM64 binaries
* 52:  182255b75bfa =  51:  d7299cb9ca05 vcbuild: install ARM64 dependencies when building ARM64 binaries
* 49:  ead04e0aefe9 =  52:  e581b8fc91bb cmake: install headless-git.
* 53:  06e20e7bdfa1 =  53:  a35125a9194e vcbuild: add an option to install individual 'features'
* 54:  b3b633470722 =  54:  a048ca2ea6bf cmake: allow building for Windows/ARM64
* 55:  8be66695d365 =  55:  e3e5c93f9039 ci(vs-build) also build Windows/ARM64 artifacts
* 56:  4b9eb75906f5 =  56:  4ee690347430 Add schannel to curl installation
* 57:  f015e725a5c8 =  57:  33191e93961a cmake(): allow setting HOST_CPU for cross-compilation
* 58:  c4da4b2a2e3e =  58:  589c2ed7cd7c mingw: allow for longer paths in `parse_interpreter()`
* 63:  97bfd92e7514 =  59:  17271def4267 subtree: update `contrib/subtree` `test` target
* 59:  31c45b22eaaa =  60:  1d39b88873b5 compat/vcbuild: document preferred way to build in Visual Studio
* 60:  742530337929 =  61:  f3a8521d44e1 http: optionally send SSL client certificate
* 65:  d05283980e6d =  62:  bd5a61ac2f72 ci: run `contrib/subtree` tests in CI builds
* 61:  9b96cc16ff8b =  63:  3821d7480a4a CMake: default Visual Studio generator has changed
* 62:  0d7a5dfcc0ff =  64:  6c8207ba1b47 .gitignore: add Visual Studio CMakeSetting.json file
* 64:  e19671a328e4 =  65:  f3bd85151772 CMakeLists: add default "x64-windows" arch for Visual Studio
* 66:  c80fe5041e36 =  66:  134d2adc0b93 CMake: show Win32 and Generator_platform build-option values
* 70:  f36590186699 =  67:  45da5f1c668a init: do parse _all_ core.* settings early
* 67:  51f2c96627e2 =  68:  a559944d9f1e hash-object: demonstrate a >4GB/LLP64 problem
* 68:  26250d780237 =  69:  7d65d1357936 write_object_file_literally(): use size_t
* 69:  0e2f16494ce7 !  70:  22c171e1e40e object-file.c: use size_t for header lengths

   ``````diff
   @@ object-file.c: static void write_object_file_prepare(const struct git_hash_algo
     {
     	git_hash_ctx c;
     
   -@@ object-file.c: int finalize_object_file(const char *tmpfile, const char *filename)
   +@@ object-file.c: int finalize_object_file_flags(const char *tmpfile, const char *filename,
     }
     
     static void hash_object_file_literally(const struct git_hash_algo *algo,
   ``````

* 72:  166007889608 !  71:  18a1d9e8ad28 hash algorithms: use size_t for section lengths

   ``````diff
   @@ sha1dc_git.h: void git_SHA1DCInit(SHA1_CTX *);
    +void git_SHA1DCUpdate(SHA1_CTX *ctx, const void *data, size_t len);
     
     #define platform_SHA_IS_SHA1DC /* used by "test-tool sha1-is-sha1dc" */
   - #define platform_SHA_CTX SHA1_CTX
   + 
    
     ## t/t1007-hash-object.sh ##
    @@ t/t1007-hash-object.sh: test_expect_success '--stdin outside of repository (uses SHA-1)' '
   ``````

* 71:  8c54e26a40e2 =  72:  bc167c8aa7b4 Enable the built-in FSMonitor as an experimental feature
* 73:  c6506c2365be =  73:  010e219757f3 hash-object --stdin: verify that it works with >4GB/LLP64
* 74:  1df41f8fa2ce =  74:  5fd555606424 hash-object: add another >4GB/LLP64 test case
* 75:  385fcc40d663 =  75:  eae89665706f setup: properly use "%(prefix)/" when in WSL
* 76:  b6d1f32cd3ec =  76:  5c00a2341faa hash-object: add a >4GB/LLP64 test case using filtered input
* 77:  a4d299511367 =  77:  64dc42ce8e29 compat/mingw.c: do not warn when failing to get owner
* 80:  b18d10783e2f =  78:  748639684da0 Add config option `windows.appendAtomically`
* 78:  8f16ccbbd5d4 =  79:  fe66c70f4789 mingw: $env:TERM="xterm-256color" for newer OSes
* 79:  f9b0c4971c40 =  80:  278e73713eec winansi: check result and Buffer before using Name
* 81:  a850019d0f0a =  81:  cbd02d41d0ff mingw: change core.fsyncObjectFiles = 1 by default
* 82:  37bc4907d634 =  82:  72a3cfde6857 vcxproj: allow building with `NO_PERL` again
* 83:  4b37b415d1ff =  83:  c7f6953a29e4 vcxproj: require C11
* 84:  4f98a72d8cb3 =  84:  e68175701097 vcxproj: ignore the `-pedantic` option
* 85:  12432c616143 =  85:  69460875d000 vcxproj: include reftable when committing `.vcxproj` files
* 86:  6503c8222aa8 =  86:  caceb1529eb1 vcxproj: handle libreftable_test, too
* 87:  44cd22c8f21b =  87:  42435818a26d vcxproj: avoid escaping double quotes in the defines
* 88:  accc435bda0a =  88:  6c18069a427c ci: adjust Azure Pipeline for `runs_on_pool`
* 89:  240dd56e406c =  89:  e095e4cbf067 ci: stop linking the `prove` cache
* 90:  f50e8b0def52 =  90:  a981ae8ef0e6 ci: reinstate Azure Pipelines support
* 91:  62700f3a53a2 =  91:  727d2686c940 azure-pipeline: drop the `GETTEXT_POISON` job
* 92:  2976f8adf41d =  92:  ecc368ba6134 azure-pipeline: stop hard-coding `apt-get` calls
* 93:  c7a817180ba4 =  93:  ea10516e23ef azure-pipeline: drop the code to write to/read from a file share
* 94:  48622b4794cc =  94:  190832c1836d azure-pipeline: use partial clone/parallel checkout to initialize minimal-sdk
* 95:  09e3a1b287e1 =  95:  7d81f0b56b49 azure-pipeline: downcase the job name of the `Linux32` job
* 96:  998692fa97d7 =  96:  28d78a2cfe5d azure-pipeline: run static-analysis on jammy
* 97:  106ae5e2e788 =  97:  c9f66c4b5352 bswap.h: add support for built-in bswap functions
* 99:  e05606d2ddb9 =  98:  6c1b6051567c config.mak.uname: add support for clangarm64
* 98:  574765701d5f =  99:  86c3000e5275 MinGW: link as terminal server aware
* 100:  874decc117f9 = 100:  a36a76ccc80b Fix Windows version resources
* 102:  6f04ab6dbeff = 101:  a99ced1eec37 ci: create clangarm64-build.yml
* 103:  06e72a43456b = 102:  da2c993a59a3 status: fix for old-style submodules with commondir
* 101:  1bbe8cf835ad = 103:  630c9ff526d8 http: optionally load libcurl lazily
* 106:  0850d0fb8278 = 104:  f0ba8a260060 http: support lazy-loading libcurl also on Windows
* 107:  9d0520d54c05 = 105:  1cc64e9d5fc7 http: when loading libcurl lazily, allow for multiple SSL backends
* 104:  413fcfef8f09 = 106:  b81567e0b6f1 windows: skip linking `git-<command>` for built-ins
* 105:  6559f8c9c129 = 107:  3106f5fffc13 windows: fix Repository>Explore Working Copy
* 108:  126c8548c8e2 = 108:  09bef5a82ebc mingw: do load libcurl dynamically by default
* 109:  abde14fb4425 = 109:  93c275dcb940 Add a GitHub workflow to verify that Git/Scalar work in Nano Server
* 110:  162c2ec04e9e = 110:  5ac3aeb95be8 mingw: suggest `windows.appendAtomically` in more cases
* 111:  b7739dd96a29 = 111:  11c77e4fe65a win32: use native ANSI sequence processing, if possible
* 112:  dcb5075744ee = 112:  1687e53df205 git.rc: include winuser.h
* 113:  baafe37ebecd = 113:  a53393715f4d common-main.c: fflush stdout buffer upon exit
* 114:  0373585542b0 ! 114:  b01d5cbf43e3 t5601/t7406(mingw): do run tests with symlink support

   ``````diff
   @@ t/t5601-clone.sh: export GIT_TEST_DEFAULT_INITIAL_BRANCH_NAME
    
     ## t/t7406-submodule-update.sh ##
    @@ t/t7406-submodule-update.sh: export GIT_TEST_DEFAULT_INITIAL_BRANCH_NAME
   - 
   + TEST_PASSES_SANITIZE_LEAK=true
     . ./test-lib.sh
     
    +# This test script contains test cases that need to create symbolic links. To
   ``````

* 115:  f8426a97d6bd = 115:  26ba963f7daf ci: work around a problem with HTTP/2 vs libcurl v8.10.0
* 118:  0ef4a4e4340d = 116:  6ed5f629fdb9 pack-objects: add --full-name-hash option
* 116:  74a7247811c8 = 117:  ddf961b5bf82 win32: ensure that `localtime_r()` is declared even in i686 builds
* 117:  bc4548533315 = 118:  aaf6d53a5792 Fallback to AppData if XDG_CONFIG_HOME is unset
* 139:  6ed4dbe930b8 = 119:  744273059d17 run-command: be helpful with Git LFS fails on Windows 7
* 119:  3f794119440a = 120:  5cc3464a360e repack: test --full-name-hash option
* 120:  e05e2cdfe7af = 121:  221be0ea675d pack-objects: add GIT_TEST_FULL_NAME_HASH
* 121:  c5297f25b77b = 122:  78dbc402052b git-repack: update usage to match docs
* 122:  a9be1553f5da = 123:  4a37ccb7353a p5313: add size comparison test
* 123:  385283b195a4 = 124:  18686eb04a36 test-tool: add helper for name-hash values
* 124:  bd5a2db13043 = 125:  82bb044f88d4 repack/pack-objects: mark `--full-name-hash` as experimental
* 125:  e5c11f5a56f6 = 126:  41e90b42f170 path-walk: introduce an object walk by path
* 126:  017e36a8b864 = 127:  65b5595a4880 t6601: add helper for testing path-walk API
* 127:  328926290298 = 128:  73ba4a8336b3 path-walk: allow consumer to specify object types
* 128:  a5f2805f72c6 = 129:  35d4207d11be path-walk: allow visiting tags
* 129:  b6785fd55f03 = 130:  1b04296ef658 revision: create mark_trees_uninteresting_dense()
* 130:  d1e895f4d778 = 131:  9ce5da585ad2 path-walk: add prune_all_uninteresting option
* 131:  8a73f5125f46 = 132:  aeae574c94a5 pack-objects: extract should_attempt_deltas()
* 132:  bb182d97a98b = 133:  6f5880bf25f9 pack-objects: add --path-walk option
* 133:  f403cae4d11d = 134:  310e324be9dd pack-objects: introduce GIT_TEST_PACK_PATH_WALK
* 134:  0aa782087d76 = 135:  18e3a5557fe2 repack: add --path-walk option
* 135:  a004ba9cde80 = 136:  a10bc416ae99 pack-objects: enable --path-walk via config
* 136:  674904544d87 = 137:  5b2135e9651d scalar: enable path-walk during push via config
* 137:  3c063bb6e83a = 138:  d832880695fa pack-objects: refactor path-walk delta phase
* 138:  c599014f0c5e = 139:  f49d804e8486 pack-objects: thread the path-based compression
* 140:  30b5cf770f7a = 140:  067a6ef259bb backfill: add builtin boilerplate
* 141:  19cbfed8645c = 141:  17e488ee904d backfill: basic functionality and tests
* 142:  34b077a32656 = 142:  56d80aaeb2e0 backfill: add --batch-size=<n> option
* 143:  a05ddaa05653 = 143:  13ea665bcf04 backfill: add --sparse option
* 144:  65ea334fa0cc = 144:  fa6bb8cd56ab backfill: assume --sparse when sparse-checkout is enabled
* 145:  f3d90f904f53 = 145:  8984fa74dd46 backfill: mark it as experimental
* 146:  c162f25ef69d = 146:  d1c3b613c77c survey: stub in new experimental 'git-survey' command
* 147:  25da3979d675 = 147:  f7b61d1b0c12 survey: add command line opts to select references
* 148:  30f822be86fc = 148:  bcccf3d0c56f survey: start pretty printing data in table form
* 149:  0c4bec0b1e1d = 149:  7d969b7d03ef survey: add object count summary
* 150:  45bdbf053546 = 150:  0e8de6dd6474 survey: summarize total sizes by object type
* 151:  6be511833a90 = 151:  f7d3e9553454 survey: show progress during object walk
* 152:  62548a9a21da = 152:  d701fb9a3cd9 survey: add ability to track prioritized lists
* 153:  545bf8c12092 = 153:  a279cfcdba5f survey: add report of "largest" paths
* 154:  afc60cfb5737 = 154:  35aee9317723 survey: add --top=<N> option and config
* 155:  bb6ebd1fbd2d = 155:  9df90e87eeb6 survey: clearly note the experimental nature in the output
* 156:  69522daeada7 = 156:  1bc2027ff7d6 Win32: make FILETIME conversion functions public
* 157:  5b0c984ff833 = 157:  190ad5fc751a Win32: dirent.c: Move opendir down
* 158:  f1662b8095dd = 158:  906efb13af5b mingw: make the dirent implementation pluggable
* 159:  7b4a13ff19f7 = 159:  f587985f380d Win32: make the lstat implementation pluggable
* 160:  8a07e6c78eb7 = 160:  e1f72b83c1dd mingw: add infrastructure for read-only file system level caches
* 161:  7aa84256c6ad = 161:  1710b328b2de mingw: add a cache below mingw's lstat and dirent implementations
* 162:  cf70e90f3ea7 = 162:  bd64e8a73e2d fscache: load directories only once
* 163:  c4473a9700d6 = 163:  abfa5b8b3d5c fscache: add key for GIT_TRACE_FSCACHE
* 164:  1b4f46245ff3 = 164:  dfa162b829e1 fscache: remember not-found directories
* 165:  eb911305c87f = 165:  969a7fa48752 fscache: add a test for the dir-not-found optimization
* 166:  617c2d1b1dd2 = 166:  bb144d70bb98 add: use preload-index and fscache for performance
* 167:  7678e5c60557 = 167:  d86ddce71e09 dir.c: make add_excludes aware of fscache during status
* 168:  4b39ba5df49c = 168:  3cbe5eb90b0b fscache: make fscache_enabled() public
* 169:  6ef3cc7104b4 = 169:  5ddee4180b08 dir.c: regression fix for add_excludes with fscache
* 170:  6346624c2102 = 170:  cd2cc2c94784 fetch-pack.c: enable fscache for stats under .git/objects
* 171:  c97a8ddde48d = 171:  6f9a6ac64dc1 checkout.c: enable fscache for checkout again
* 172:  4c3505cbcac5 = 172:  bff685b5680f Enable the filesystem cache (fscache) in refresh_index().
* 173:  62a9ebc86dcd = 173:  5f6841b671f2 fscache: use FindFirstFileExW to avoid retrieving the short name
* 174:  8b379b1943a6 = 174:  7c2407a549a8 status: disable and free fscache at the end of the status command
* 175:  7dfd5d4904ca = 175:  6ccfc7f6e93c fscache: add GIT_TEST_FSCACHE support
* 176:  9f0398df2ed8 = 176:  4129718ca250 fscache: add fscache hit statistics
* 177:  898a7b0f47ea = 177:  61908a615d99 mem_pool: add GIT_TRACE_MEMPOOL support
* 178:  be72b305fd47 = 178:  d199d45f2654 fscache: fscache takes an initial size
* 179:  6325d207f401 = 179:  57c3489f8874 fscache: update fscache to be thread specific instead of global
* 180:  34fe22cf298a = 180:  4be363e7073e fscache: teach fscache to use mempool
* 181:  f085223b43a6 = 181:  5ab04fb09988 fscache: make fscache_enable() thread safe
* 182:  1dda695dd1e7 = 182:  2ce4c07126af fscache: teach fscache to use NtQueryDirectoryFile
* 183:  c2ff9e32f466 = 183:  16991c8ff8aa unpack-trees: enable fscache for sparse-checkout
* 184:  752e62518d81 = 184:  3c1023bffd0c fscache: remember the reparse tag for each entry
* 185:  5effe018f708 = 185:  66de6234f195 fscache: implement an FSCache-aware is_mount_point()
* 187:  ab364043ae40 = 186:  91786537f63d git-gui: provide question helper for retry fallback on Windows
* 186:  7335e91f3b21 = 187:  b924477ecde6 clean: make use of FSCache
* 188:  f9bcdc78fe13 = 188:  9d9e902d9493 git gui: set GIT_ASKPASS=git-gui--askpass if not set yet
* 189:  8134f3ddfec5 = 189:  a0ac891178d2 git-gui--askyesno: fix funny text wrapping
* 191:  18c726ed1549 = 190:  d375ea2761ec gitk: Unicode file name support
* 190:  8694acfd357b = 191:  c7a807876820 git-gui--askyesno: allow overriding the window title
* 193:  b897abc8e6a2 = 192:  8be786c2cf91 gitk: Use an external icon file on Windows
* 192:  9a4a9e27ec4b = 193:  121ae0e58947 git-gui--askyesno (mingw): use Git for Windows' icon, if available
* 194:  fd6437dcfbec = 194:  831062c815d2 gitk: fix arrow keys in input fields with Tcl/Tk >= 8.6
* 195:  2fabe46e8c5b = 195:  6be9636975ff gitk: make the "list references" default window width wider
* 196:  f970a6fbe07a = 196:  2094052a34c4 pack-objects (mingw): demonstrate a segmentation fault with large deltas
* 197:  e91062d5e3be = 197:  5085003d4b76 mingw: support long paths
* 198:  f6d060b35625 = 198:  b5c8307c23e0 Win32: fix 'lstat("dir/")' with long paths
* 199:  a78e081ac8f8 = 199:  6680255dc7f4 win32(long path support): leave drive-less absolute paths intact
* 202:  d8d09abc43c8 = 200:  39c0088432db mingw: Support `git_terminal_prompt` with more terminals
* 203:  13aad84813a2 = 201:  9f8bee968627 compat/terminal.c: only use the Windows console if bash 'read -r' fails
* 204:  b32df1ee1510 = 202:  00da3d069cb7 mingw (git_terminal_prompt): do fall back to CONIN$/CONOUT$ method
* 200:  42a535ef8bb3 = 203:  e752356c75ce compat/fsmonitor/fsm-*-win32: support long paths
* 201:  057f6d4bcfa2 = 204:  1dec1c41ce75 clean: suggest using `core.longPaths` if paths are too long to remove
* 205:  d792ed350daa = 205:  e971106e0d5d strbuf_readlink: don't call readlink twice if hint is the exact link size
* 206:  a15c613899ad = 206:  f5b42d4ab4e2 strbuf_readlink: support link targets that exceed PATH_MAX
* 207:  62753908e5f3 = 207:  759618ed2f82 lockfile.c: use is_dir_sep() instead of hardcoded '/' checks
* 208:  768c262aa3a3 = 208:  3d51e3d51e16 Win32: don't call GetFileAttributes twice in mingw_lstat()
* 209:  86f1eaeeaae1 = 209:  31297772f36a Win32: implement stat() with symlink support
* 210:  22bf97f8d2c1 = 210:  dc29e1acaac4 Win32: remove separate do_lstat() function
* 211:  adc69e9672e5 = 211:  a38a3d37cf48 Win32: let mingw_lstat() error early upon problems with reparse points
* 212:  49cc90146eef = 212:  9be9c3ade9df mingw: teach fscache and dirent about symlinks
* 213:  9c27ec781e30 = 213:  00c33cf1eb2f Win32: lstat(): return adequate stat.st_size for symlinks
* 214:  e943c582251d = 214:  cdbefd8ba95f Win32: factor out retry logic
* 215:  b105378b8e7c = 215:  b76865b8be14 Win32: change default of 'core.symlinks' to false
* 216:  f0f022d5d58e = 216:  0aab789068eb Win32: add symlink-specific error codes
* 217:  faa04b5c4568 = 217:  1b5d98d29158 Win32: mingw_unlink: support symlinks to directories
* 218:  8e50d253e8ea = 218:  13f00f9dd7bb Win32: mingw_rename: support renaming symlinks
* 219:  c720d21c3133 = 219:  fbd9aac1987d Win32: mingw_chdir: change to symlink-resolved directory
* 220:  a9938d0a933d = 220:  ee29c5ab7c90 Win32: implement readlink()
* 221:  92f6f6ca5258 = 221:  08418431b508 mingw: lstat: compute correct size for symlinks
* 222:  f372e9966954 = 222:  4ba730dd49e2 Win32: implement basic symlink() functionality (file symlinks only)
* 223:  fd7535da0c58 = 223:  7872b88fb07d Win32: symlink: add support for symlinks to directories
* 224:  6203204deac1 = 224:  510badc927a5 mingw: try to create symlinks without elevated permissions
* 225:  fcef52a93166 = 225:  6c890387b46e mingw: emulate stat() a little more faithfully
* 226:  1917acde48fd = 226:  14617f34965a mingw: special-case index entries for symlinks with buggy size
* 227:  f9e8663b0f96 = 227:  d756acbf850c mingw: introduce code to detect whether we're inside a Windows container
* 228:  ae7ce1bb40f2 = 228:  842578592858 mingw: when running in a Windows container, try to rename() harder
* 229:  e4d85ddd8b9f = 229:  b05e984c87c0 mingw: move the file_attr_to_st_mode() function definition
* 230:  8a7b14fb66ca = 230:  744ce6d1a62e mingw: Windows Docker volumes are *not* symbolic links
* 231:  2191e908cc80 = 231:  dc6ba0164291 mingw: work around rename() failing on a read-only file
* 232:  7a5d26511eff = 232:  12f0ea308649 Win32: symlink: move phantom symlink creation to a separate function
* 233:  2c414caae557 = 233:  47c427ad4afc Introduce helper to create symlinks that knows about index_state
* 234:  880d387eae62 = 234:  e66f01abb70c mingw: allow to specify the symlink type in .gitattributes
* 235:  c30acd3c9210 = 235:  2c62c09b7a14 Win32: symlink: add test for `symlink` attribute
* 236:  bf3bbc3cb820 = 236:  93ea9b9a424a mingw: explicitly specify with which cmd to prefix the cmdline
* 237:  b8dc8ab93c75 = 237:  f40f3f512aff mingw: when path_lookup() failed, try BusyBox
* 238:  bf25de0a1b6a = 238:  260a12d0fab5 test-lib: avoid unnecessary Perl invocation
* 239:  49ea6d627dd4 = 239:  de5a684928ad test-tool: learn to act as a drop-in replacement for `iconv`
* 240:  0656ea5ed548 = 240:  385ae19fcfb2 tests(mingw): if `iconv` is unavailable, use `test-helper --iconv`
* 241:  cfebe5d077a5 = 241:  55c8c6f09ae9 gitattributes: mark .png files as binary
* 242:  eb3d3e675b0f = 242:  aa1e44577948 tests: move test PNGs into t/lib-diff/
* 243:  e9e724bc0e05 = 243:  c9284450e76d tests: only override sort & find if there are usable ones in /usr/bin/
* 244:  2fcd9d99177f = 244:  747d1afde2f0 tests: use the correct path separator with BusyBox
* 245:  4e9c7a208fc9 = 245:  54f6687f9503 mingw: only use Bash-ism `builtin pwd -W` when available
* 246:  3a0450ec6f08 = 246:  9fd3a3766fe1 tests (mingw): remove Bash-specific pwd option
* 247:  f3d15bb2d2fd = 247:  46b9fa7c54da test-lib: add BUSYBOX prerequisite
* 248:  522f574ca9ea = 248:  31354e8c28e0 t5003: use binary file from t/lib-diff/
* 249:  709c8bc91947 = 249:  bd5ca8b66e5b t5532: workaround for BusyBox on Windows
* 250:  80230b32573a = 250:  5fe6b0f4ed8a t5605: special-case hardlink test for BusyBox-w32
* 251:  dcd9dd41ecf9 = 251:  6a4bb555a271 t5813: allow for $PWD to be a Windows path
* 252:  da3aba03d2d4 = 252:  25bdb8208326 t9200: skip tests when $PWD contains a colon
* 253:  4826cd4704dd = 253:  cb336113a907 mingw: add a Makefile target to copy test artifacts
* 254:  ce3085aab398 = 254:  066af3c3689d mingw: kill child processes in a gentler way
* 255:  6b8ce47ad50b = 255:  2990afe518aa mingw: optionally enable wsl compability file mode bits
* 257:  b04f22e1bef5 = 256:  e0b23e78e449 mingw: really handle SIGINT
* 256:  b95b626e5d42 = 257:  3881185b42dc mingw: do not call xutftowcs_path in mingw_mktemp
* 258:  09a052652910 = 258:  28c3e4334d54 Partially un-revert "editor: save and reset terminal after calling EDITOR"
* 259:  35dcdd940681 = 259:  75885faf2114 Add a GitHub workflow to monitor component updates
* 260:  eab4d9d83521 = 260:  ff41d3b2af5c reset: reinstate support for the deprecated --stdin option
* 261:  c10b13c121f9 = 261:  334012272d3f fsmonitor: reintroduce core.useBuiltinFSMonitor
* 262:  c5ea12599b81 = 262:  147203ef9cf9 dependabot: help keeping GitHub Actions versions up to date
* 263:  1e3450ace5df = 263:  9e6a0910a1e7 Describe Git for Windows' architecture [no ci]
* 264:  2aebbedaca2e = 264:  e155e4716325 Modify the Code of Conduct for Git for Windows
* 265:  84263026bc03 = 265:  034b75ae6ff5 CONTRIBUTING.md: add guide for first-time contributors
* 266:  f6204b6eef9e = 266:  9db70a577862 README.md: Add a Windows-specific preamble
* 267:  03bc8338d2c2 = 267:  93ffaafd5938 Add an issue template
* 268:  cccb602e7739 = 268:  ecf272b7f9cc Modify the GitHub Pull Request template (to reflect Git for Windows)
* 269:  d08120457781 = 269:  1f01e8aeb270 .github: Add configuration for the Sentiment Bot
* 270:  bbd23b4909a5 = 270:  c35f255bf975 Document how $HOME is set on Windows
* 271:  418a02d45838 = 271:  a73435966b03 SECURITY.md: document Git for Windows' policies

</details>

Only diff context changes this time around.

### CODE REVIEW

**Comment by dscho** [comment]
So... A couple of changes needed on top:

- I fixed the DCO failures by adjusting the authorships of several commits (neither Stolee nor Jeff are at GitHub any longer).
- I dropped https://github.com/git-for-windows/git/commit/8c54e26a40e2d0c9a0ca606fa38c864b295e42e4 because
  1. FSMonitor has not been experimental for a very long time
  2. The patch caused merge conflicts with https://github.com/git-for-windows/git/commit/a004ba9cde8004f9ce426ff6d11ea385a2fb64f6

I have those changes locally, but unfortunately there is a serious new problem: t0610.47(ref transaction: many concurrent writers) consistently fails on Windows. I'll have to spend time figuring out how to address this.

**Review by derrickstolee — APPROVED** [review]
While you work on the test failures, I will approve this version of the rebase. Looking forward to seeing what you discover about the concurrent write failures.

**Comment by rimrul** [comment]
> The issue on Win32 is different: we cannot commit the "tables.list" lock via rename(3P) because the target file may be open for reading by a concurrent process. I guess that Cygwin has proper POSIX semantics for rename(3P) and thus doesn't hit the same issue. We already try to emulate POSIX semantics somewhat in `mingw_rename()` by using a retry-loop when we hit `ERROR_ACCESS_DENIED`, which is what we get when the target file is open in another process. But that seemingly isn't enough when there is a lot of contention around a file. So I'm currently investigating whether we can adopt something similar to what Cygwin is doing for Win32, as well. I assume that they use `FILE_RENAME_INFORMATION_EX` with `FILE_RENAME_POSIX_SEMANTICS`, which should give us what we're looking for. […] But my guess was correct: they do use `FILE_RENAME_POSIX_SEMANTICS`. The catch is that this flag only exists in Windows 10 and newer. But that should be a fine compromise.

https://lore.kernel.org/git/Zv-HbT8qrM6IYKb4@pks.im/T/#m702741a2ccb1cddb45a5410ac762d236c1566b27

**Comment by dscho** [comment]
@rimrul great find, thanks! I wasn't able to keep up with the Git mailing list.

**Comment by dscho** [comment]
> I finally figured out how to work around the t0610.47(ref transaction: many concurrent writers) problem: [3903e5d](https://github.com/git-for-windows/git/commit/3903e5d9d537b4a3564cf43ea9fa1e1a8f18cc67)

Apparently not quite: [win+VS test (6) still fails](https://github.com/git-for-windows/git/actions/runs/11177274881/job/31072617091?pr=5187#step:5:1598):

> `fatal: update_ref failed for ref 'refs/heads/branch-61': reftable: transaction failure: I/O error`

**Comment by dscho** [comment]
> Apparently not quite: [win+VS test (6) still fails](https://github.com/git-for-windows/git/actions/runs/11177274881/job/31072617091?pr=5187#step:5:1598):
> 
> > `fatal: update_ref failed for ref 'refs/heads/branch-61': reftable: transaction failure: I/O error`

And [win test (6) fails, too](https://github.com/git-for-windows/git/actions/runs/11177274881/job/31072657373?pr=5187#step:5:1441), with the same symptom.

**Pull request merged**
