### PR TITLE
Teach Git to handle huge files in smudge/clean

### PR DESCRIPTION
**Pull request by vtbassmatt**
On platforms like Windows, where `unsigned long` is 32 bits, Git can only deal with files up to 4GB. This is fine for normal objects, since no one should commit such large files to Git. However, even external solutions like Git LFS are subject to the limitation, since smudge/clean also make use of `unsigned long`.

This patch series introduces a test case exposing the problem, then makes the minimum changes necessary for the test to pass on such platforms.

### CODE REVIEW

**Comment by KuDeSnik33ra** [comment]
Sorry for the importunity, but this problem has been plaguing many for a long time. Do I understand correctly that now LFS can normally work with files of any size? Pull, Commit, Push? Installer 2.34, available here https://git-scm.com/ does not have these changes?

**Comment by dscho** [comment]
> Sorry for the importunity, but this problem has been plaguing many for a long time. Do I understand correctly that now LFS can normally work with files of any size (on Windows)? Pull, Commit, Push? Installer 2.34, available here https://git-scm.com/ does not have these changes?

This PR was merged, and its improvements are part of Git for Windows v2.34.0 (but not Git v2.34.0). Git LFS can work with files of any size, provided that there are no limits on the hosting side.

If you still have problems, I encourage you to [open a proper bug report](https://github.com/git-for-windows/git/issues/new), filling out the bug reporting template diligently.

**Comment by KuDeSnik33ra** [comment]
I've installed the https://github.com/git-for-windows/git/tree/v2.34.0.windows.1 and cloned our repo with 3 lfs files greater than 4gb. It looks like they are cloned correctly, but I still have such warning in the console:
Encountered 3 file(s) that may not have been copied correctly on Windows:
        terrain/normals/lod0/data.uts
        terrain/masks/lod0/data.uts
        terrain/heights/lod0/data.uts
Is it OK?

**Comment by vtbassmatt** [comment]
> Encountered 3 file(s) that may not have been copied correctly on Windows

I believed that message comes from LFS and can be safely ignored. If the files are the correct size, then you're definitely good.

**Comment by dscho** [comment]
Right. And Git LFS' developers [are aware](https://github.com/git-lfs/git-lfs/issues/2434#issuecomment-972962559).

**Pull request merged**
