### PR TITLE
Include Windows-specific maintenance and headless-git

### PR DESCRIPTION
**Pull request by derrickstolee**
These six patches complete the background maintenance story for Git for Windows.

The first four patches were recently merged into `next` in upstream. These update the platform-specific background maintenance to use `schtasks` on Windows.

The last two patches create a `headless-git.exe` that uses a `winmain()` instead of a `main()` to allow the background maintenance to not create a console window with focus in front of a user.

### CODE REVIEW

**Comment by dscho** [comment]
Don't we need dc86de5357bca8780d5829878b3521402a7ebbb6 to let the test suite pass?

**Comment by dscho** [comment]
Should we also do something about https://github.com/gitgitgadget/git/pull/776#discussion_r554520248?

**Comment by derrickstolee** [comment]
> Should we also do something about [gitgitgadget#776 (comment)](https://github.com/gitgitgadget/git/pull/776#discussion_r554520248)?

I'm hoping that this doesn't result in a re-roll, but let's wait and see.

**Comment by dscho** [comment]
> > Should we also do something about [gitgitgadget#776 (comment)](https://github.com/gitgitgadget/git/pull/776#discussion_r554520248)?
> 
> I'm hoping that this doesn't result in a re-roll, but let's wait and see.

In any case, I think we can already merge this, as it is a commit message-only change (which will easily be "rebased away" if it hits upstream).

**Pull request merged**
