### PR TITLE
Fix clone within a directory whose parent isn't readable by the current user

### PR DESCRIPTION
**Pull request by dscho**
Even if the patch looks like it has nothing to do with cloning (or for that matter, with creating leading directories), this fixes https://github.com/git-for-windows/git/issues/2531.

### CODE REVIEW

**Comment by dscho** [comment]
@danthe1st @byNoobiYT could you test this?

**Comment by dscho** [comment]
Oh well, I guess I'll merge it before v2.26.0-rc0 ([which _should_ have happened](https://tinyurl.com/gitCal), but got delayed for some reason).

**Comment by danthe1st** [comment]
Should we still test it? If so, is it possible to test it without Visual Studio?

**Comment by dscho** [comment]
@danthe1st yes, please test it.

You won't be able to compile it with Visual Studio unless you get the entire Git for Windows SDK, which far outweighs Visual Studio.

But we do have snapshot builds for `master`.

Unfortunately, the [build failed](https://dev.azure.com/Git-for-Windows/git/_build/results?buildId=51645&view=results), but the [next build](https://dev.azure.com/Git-for-Windows/git/_build/results?buildId=51653&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=70b92200-87db-50c8-35f9-975ba5f9e5b7) hopefully won't, and you should be able to test the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html).

**Comment by dscho** [comment]
There you go: https://wingit.blob.core.windows.net/files/index.html.

**Comment by danthe1st** [comment]
I tested it with that snapshot and I get a different error (with a better error message) prompting me for username and password. When entering the credentials correctly, I get the following error:

> C:\parent\child>C:\PRGM\git-snapshot\bin\git.exe clone https://github.com/octocat/HelloWorld.git
Cloning into 'HelloWorld'...
fatal: UnauthorizedAccessException encountered.
   Der Zugriff auf den Pfad "C:\parent" wurde verweigert.
Username for 'https://github.com': danthe1st
Password for 'https://danthe1st@github.com':
remote: Repository not found.
fatal: repository 'https://github.com/octocat/HelloWorld.git/' not found

(`Der Zugriff auf den Pfad "C:\parent" wurde verweigert.` means `Access denied for path "C:\parent"`)

If I enter incorrect credentials, I get a normal `Authentication failed` error.

**Comment by dscho** [comment]
@danthe1st hmm. Can you [build Git for Windows from source](https://github.com/git-for-windows/git/wiki/Building-Git)? If so, could you start the command in the debugger and set a breakpoint at the location changed by this PR and investigate further?

**Comment by danthe1st** [comment]
I got a Bluescreen(actually a greenscreen) while compiling git for windows(master for now) saying `SYSTEM_SERVICE_EXCEPTION`. I will try to do it again...

**Comment by danthe1st** [comment]
I successfully compiled it but when cloning the repository(not even in the `parent/child` directory), I get the following error: 
> $ ./git.exe clone https://github.com/octocat/Hello-World.git
Cloning into 'Hello-World'...
warning: templates not found in C:/PRGM/git-sdk/usr/src/share/git-core/templates
git: 'remote-https' ist kein Git-Befehl. Siehe 'git --help'.

(`ist kein Git-Befehl` means `is not a git command`)
It seems like it might take a while until I get git from souurce to work.

**Comment by danthe1st** [comment]
After adding the `git` directory to the `PATH` manually, it works in the SDK git bash:

> main user@hostname MINGW64 /c/parent/child
$ git clone https://github.com/octocat/Hello-World.git
Cloning into 'Hello-World'...
warning: templates not found in C:/PRGM/git-sdk/usr/src/share/git-core/templates
git: 'credential-manager' is not a git command. See 'git --help'.
git: 'credential-manager' is not a git command. See 'git --help'.
remote: Enumerating objects: 13, done.
remote: Total 13 (delta 0), reused 0 (delta 0), pack-reused 13
Unpacking objects: 100% (13/13), 1.53 KiB | 7.00 KiB/s, done.

**Comment by dscho** [comment]
Hmm. That's strange.

As to running in-place, yes, the common way is to use `bin-wrappers/git [...]`.

**Comment by dscho** [comment]
> git: 'credential-manager' is not a git command. See 'git --help'.

Oh! I think I could imagine that Git Credential-Manager might be the culprit. Because...

> fatal: UnauthorizedAccessException encountered.
> Der Zugriff auf den Pfad "C:\parent" wurde verweigert.
> Username for 'https://github.com': danthe1st
> Password for 'https://danthe1st@github.com':
> remote: Repository not found.

This seems to not be coming from Git directly, but from the Git Credential Manager! (I was wondering about that exception, we do not use exceptions in core Git...)

Maybe you can try again in the SDK, after _appending_ `/mingw64/libexec/git-core` to the `PATH`?

**Comment by danthe1st** [comment]
It does work even if `credential-manager` is not there.

**Comment by dscho** [comment]
> It does work even if `credential-manager` is not there.

What I meant to say, I think that you see the failures _because_ `git-credential-manager.exe` is configured.

In other words, if you run `git -c credential.helper= clone https://github.com/octocat/Hello-World.git`, it should work.

However, I am really curious now: why does that Credential Helper come into play, anyway? It's not like the Hello-World.git repository is a private one. It does not need you to authenticate.

Strange. _Really_ strange.

**Comment by danthe1st** [comment]
Yes, it does work with the option without a warning. It worked before (without the option) with showing the warning.

**Comment by danthe1st** [comment]
But note that it works when I compiled it from `master`.

**Comment by dscho** [comment]
The difference is that the snapshot version configures `credential.helper` in the system config. The SDK does not.

**Comment by danthe1st** [comment]
Yes, it works without the `credential.helper` in the snapshot version:

> C:\parent\child>git -c credential.helper= clone https://github.com/octocat/Hello-World.git
Cloning into 'Hello-World'...
remote: Enumerating objects: 13, done.
remote: Total 13 (delta 0), reused 0 (delta 0), pack-reused 13
Unpacking objects: 100% (13/13), 1.53 KiB | 9.00 KiB/s, done.

**Comment by dscho** [comment]
Okay, so our work here is done, eh? :-)

**Pull request merged**
