### PR TITLE
Enable fscache for ls-files (speeds up programs like TortoiseGit)

### PR DESCRIPTION
**Pull request by mehrdadn**

### CODE REVIEW

**Comment by dscho** [comment]
@mehrdadn thank you for your contribution!

Could you maybe include a little more information in the commit message about timing? Like, best-of-5 runs before and after this patch on some well-known repository such as git.git, or if you want to use a larger repository maybe kotlin (or any other repository mentioned in https://github.com/git-for-windows/git/blob/master/CONTRIBUTING.md#performance-tests).

Also, as per [core Git's requirements](https://github.com/git/git/blob/v2.16.2/Documentation/SubmittingPatches#L278-L336), could you please [use your real name in the "Signed-off-by:" footer"](https://github.com/git/git/blob/ffa952497288d29d94b16675c6789ef83850def3/Documentation/SubmittingPatches#L334-L336)?

**Comment by mehrdadn** [comment]
I added a benchmark. My real name is already in the sign-off message though?

**Comment by kostix** [comment]
@mehrdadn, `<nobody@example.com>` does not appear as a likely real e-mail address ;-)

This bit is important in fact: the code will be a part of Git, and should some issue regarding copyright/copyleft arise, there may be the need to contact all the authors contributed
to some part of the code to seek their consent/opinion on the issue.

**Comment by mehrdadn** [comment]
What do I do if I'm not inclined to share my email address? :\

**Comment by dscho** [comment]
> My real name is already in the sign-off message though?

@mehrdadn Is Mehrdad your full name (your handle suggests that there is at least a trailing "n" missing)?

Remember, the Signed-off-by: line is kind of a legally binding statement that you are entitled to contribute this patch under the GPLv2 license. If your employer is not okay with you contributing patches under that license, and you did this on company time or your company does not allow you to contribute code outside of work, then this would be a problem.

In this case, the patch is pretty trivial (and obvious, therefore it would probably not be copyright'able in the first place), so it might not matter, but I would love to accept future contributions from you, too...

As to the email address: there are a couple of bogus email addresses to be found in the Git log. It would help, of course, if your address was available, or some verifiable way to contact you in case of problems with the patch, but I think we can do without it. But we really would like to have your real real name, in the original spelling, in the commit. (There is precedent, for example, for Japanese names using Japanese characters.)

If you are uncomfortable with disclosing your real name, that's fine, too, but then I would probably have to redo your patch (I already stopped looking at it, using just the information that `cmd_ls_files()` would need a similar patch to 5200492683ae259dcfcea39c9ff65a7837493a39).

**Comment by mehrdadn** [comment]
By "real name" you mean "full name"? I'm not using a fake name, I'm just only putting my, but it's very real.

> We really would like to have your real real name, in the original spelling, in the commit. (There is precedent, for example, for Japanese names using Japanese characters.)

...*"original spelling"*? Sorry, but this is becoming unreasonable. I put my legal, daily, real, genuine, actual, etc. first name. If my first name having been potentially originally spelled in a different alphabet makes it invalid then (a) I really have to question the motives (clearly this is no longer due to legal reasons) and (b) I really have wouldn't have any more interest in contributing.

> Remember, the Signed-off-by: line is kind of a legally binding statement that you are entitled to contribute this patch under the GPLv2 license. If your employer is not okay with you contributing patches under that license, and you did this on company time or your company does not allow you to contribute code outside of work, then this would be a problem. In this case, the patch is pretty trivial (and obvious, therefore it would probably not be copyright'able in the first place), so it might not matter, but I would love to accept future contributions from you, too...

No, I don't think my employer would have any issues here, but I would worry about future contributions when/if they come ;) as you said, this one is simple enough that it's irrelevant here. Happy to discuss it offline though if that helps.

> As to the email address: there are a couple of bogus email addresses to be found in the Git log. It would help, of course, if your address was available, or some verifiable way to contact you in case of problems with the patch, but I think we can do without it. 

If it helps, I'm happy to email you offline too. I just don't wish to inject my email into public databases/repos (and ask that you wouldn't subsequently do that if I do contact you).

> If you are uncomfortable with disclosing your real name, that's fine, too, too, but then I would probably have to redo your patch (I already stopped looking at it, using just the information that cmd_ls_files() would need a similar patch to `5200492`).

If you mean my _full_ name (again, what I provided _is_ already my real first name), I'm not uncomfortable "disclosing" per se (again, I'm happy to contact you privately), just uncomfortable having it injected into a permanent, globally-public repository with little to gain on my end.

**Comment by mehrdadn** [comment]
my first name* typo

**Comment by dscho** [comment]
> I just don't wish to inject my email into public databases/repos (and ask that you wouldn't subsequently do that if I do contact you).

That's perfectly understandable.

At the same time, it is what core Git's contributing rules would require. So I think we should probably just close this PR, and I will make a similar change whenever I find the time.

> > If you are uncomfortable with disclosing your real name, that's fine, too, too, but then I would probably have to redo your patch (I already stopped looking at it, using just the information that cmd_ls_files() would need a similar patch to 5200492).
> 
> If you mean my full name (again, what I provided is already my real first name)

Yes, the core Git team requires your full, real name. A name by which you can be found and contacted in case some questions arise over your changes. This is not anything out of malice, it is standard practice in actively-developed Open Source projects, as there are almost always unforeseen consequences, or follow-up questions that sometimes take years before somebody thinks of asking them.

> I'm not uncomfortable "disclosing" per se (again, I'm happy to contact you privately), just uncomfortable having it injected into a permanent, globally-public repository with little to gain on my end.

Right, your gain would be that people could reach you to pester you about your contributions. Again, I understand that you don't want that. It is something that takes a lot of time, and I sometimes (rarely) rue being subject to it. But this is the deal in the Git project (and other long-running Open Source projects): you gotta be able to reach out to the contributors who submitted a given patch, so that you can continue the original conversation.

So: closing time?

**Comment by mehrdadn** [comment]
Yup, sure.

**Comment by dscho** [comment]
FWIW I am *really* sorry to see you leave. It was a pleasure interacting with you.

But there is nothing I can do to change the rules of core Git. 😦

**Comment by mehrdadn** [comment]
Thanks, yeah, same here as well. It's unfortunate that both open- and closed-source software have to come with extra social baggage... I wish I could just make a contribution and disappear. I can probably still continue to post issues though (at least as long as I see them resulting in improvements); I just won't be submitting PRs I guess. As long as improvements are making it into the code somehow it doesn't really matter to me how it happens... I just want software to work well. :-)

**Comment by mehrdadn** [comment]
This does make me wonder though... out of curiosity, to clarify, is the reason that you need to follow the rules of core Git the idea that the changes might be pushed upstream some point, and that won't be allowed as long as there is a single commit without author contact information? Or is it something else?

**Comment by dscho** [comment]
> is the reason that you need to follow the rules of core Git the idea that the changes might be pushed upstream some point, and that won't be allowed as long as there is a single commit without author contact information?

Yes, exactly. We currently have ~550 patches in ~70 topic branches on top of core ("upstream") Git, but that is not intended to stay that way. Git for Windows serves as a test-bed for Windows-specific patches, and when they have proved to be stable, the idea is to get them into core Git (which used to suffer from a shortage of Windows-based developers).

> I wish I could just make a contribution and disappear.

:-)

I would like to invite you to stick around, your comments on this bug tracker have been really helpful. And whenever you have an idea how to improve some code, please do feel at liberty to just throw the ideas out there, maybe even with patches (if you're comfortable to transfer ownership of the patches to me so I can submit them to core Git, that's totally cool by me).

The interactions I had with you so far were truly enjoyable, and I'd *love* to have more of the same.

**Comment by mehrdadn** [comment]
Sounds good, thanks! Will do! =)

**Pull request closed without merging**
