### PR TITLE
Correct fscanf formatting string for I64u values

### PR DESCRIPTION
**Pull request by weakcamel**
Signed-off-by: Waldek Maleska <w.maleska@gmail.com>

### CODE REVIEW

**Comment by weakcamel** [comment]
As discussed at https://github.com/git-for-windows/git/issues/52#issuecomment-88178493

**Comment by dscho** [comment]
@weakcamel are you still interested in this issue? If so, I would be very interested in your opinion about my suggestion.

**Comment by weakcamel** [comment]
I am and yes, I like the idea.
At first I wondered if defining those constants wouldn't interfere with including `inttypes.h` *after* someone includes the `git-compat-utils.h` or `mingw.h`
The former already requires the standard header - so no problem there.
The latter being mingw/windows specific, I can't imagine someone to include it otherwise.

**Comment by dscho** [comment]
To be sure, I did not suggest including any header there, just introducing a block

```c
#ifndef SCNuMAX
#define SCNuMAX PRIuMAX
#endif`
```

not anything more...

**Comment by weakcamel** [comment]
Done (finally!). Thank you for you patience.
Let me know if I should squash it or of course if you see ny problems.

**Comment by dscho** [comment]
Thanks! I added a comment with a question and would like to request a squash and rebase followed by a force-push to finalize this Pull Request.

**Comment by dscho** [comment]
> Checked and it's not enough - the warnings are back - SCNuMAX is back at "llu". Can't yet tell where it comes from, I just had a moment to look into it

You can check by inserting `#define SCNuMAX PRIuMAX` right before https://github.com/weakcamel/git/commit/4b096a083ce1304d65909ed9f2be8d93cf82ac3b#diff-29b0a2def034550470a8eb7e8b673403L225 and compiling (gcc will complain that the constant has been redefined and tell you where the original definition came from).

**Comment by weakcamel** [comment]
Thank you!

Well, the definition comes from .. `git-compat-utils.h`
So either we should include mingw.h before the, or repeat the OS-specific magic in it.
What do you think?

**Comment by dscho** [comment]
Hmm. I wonder why it works for `PRIuMAX`, but not `SCNuMAX`: after all, we `#define PRIuMAX` in `compat/mingw.h` and `git-compat-util.h` sees that and does not redefine it. In my mind, at that stage, `SCNuMAX` should not yet be `#define`d, but `PRIuMAX` should be, correctly, so it *should* work. I guess I'll need to dig into this myself...

**Comment by weakcamel** [comment]
They're both at 'llu'. I've added `#pragma message` in `git-compat-utils.h` and in general, without loading definitions from `<inttypes.h>` they're wrong on 32-bits.

```
$ rm builtin/gc.o && make builtin/gc.o
    CC builtin/gc.o
In file included from ./builtin.h:4:0,
                 from builtin/gc.c:13:
./git-compat-util.h:263:9: note: #pragma message: llullu
 #pragma message PRIuMAX SCNuMAX
         ^
...
```

**Comment by dscho** [comment]
In my tests, the `SCNuMAX` constant was actually defined correctly if I skipped the change to `compat/mingw.h`, so I mangled your patch. Hopefully you do not mind!

**Comment by weakcamel** [comment]
I do not mind and all. I'm glad you did. Thank you!

**Pull request merged**
