### PR TITLE
apply: ignore any text after "/dev/null"

### PR DESCRIPTION
**Pull request by tkrasnukha**
Fix issue #1489.

### CODE REVIEW

**Comment by dscho** [comment]
Thank you! I ran out of time today, and will try to have a look tomorrow. Wednesday at the latest!

**Comment by dscho** [comment]
Submitted here: https://public-inbox.org/git/cover.1518654532.git.johannes.schindelin@gmx.de/T/#t

**Comment by tkrasnukha** [comment]
Thank you for testing and submitting!

**Comment by dscho** [comment]
@tkrasnukha I just realized that I did not describe just *how excited* I am about your contribution. It really made my day!

**Comment by tkrasnukha** [comment]
Thank you, I'm glad you like it)

**Comment by dscho** [comment]
Woot! From https://public-inbox.org/git/xmqq1shdyidz.fsf@gitster-ct.c.googlers.com/:

```
* tk/apply-dev-null-verify-name-fix (2018-02-15) 2 commits
  (merged to 'next' on 2018-02-21 at dab449203b)
 + apply: handle Subversion diffs with /dev/null gracefully
 + apply: demonstrate a problem applying svn diffs

 Many places in "git apply" knew that "/dev/null" that signals
 "there is no such file on this side of the diff" can be followed by
 whitespace and garbage when parsing a patch, except for one, which
 made an otherwise valid patch (e.g. ones from subversion) rejected.

 Will merge to 'master'.
```

**Comment by tkrasnukha** [comment]
> Woot! From https://public-inbox.org/git/xmqq1shdyidz.fsf@gitster-ct.c.googlers.com/:
 ...

Great!

**Comment by dscho** [comment]
And it was merged to master: e454ad4becff73588b1b3cc24dba3a0e740c7f7c

**Comment by dscho** [comment]
FYI @tkrasnukha this means that v2.17.0 will have your fix. Do you want it early? I can cherry-pick it to Git for Windows' `master` branch, too, so that whatever version comes next will have the fix (Git v2.17.0 [is slated for March 30th 2018](https://tinyurl.com/gitCal)).

**Comment by tkrasnukha** [comment]
> Do you want it early?

No, thank you, there's no big rush.

**Pull request closed without merging**
