### PR TITLE
Gitk f5 filenametoolong

### LINKED ISSUE #1987: gitk pops up Error: couldn't execute "git": filename too long
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.20.1.windows.1
cpu: x86_64
built from commit: 7c9fbc07db0e2939b36095df45864b8cda19b64f
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```

gitk

```
 - What did you expect to occur after running these commands?

I expected to see a history of commits

 - What actually happened instead?

Error message appears:  "Error: couldn't execute "git": filename too long"

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

private repo

### PR DESCRIPTION
**Pull request by max630**
This should fix #1987

### CODE REVIEW

**Comment by max630** [comment]
* I thought it could work in line with f2c696f706d
* these negavite patterns are there to limit work for `git log`. It some are missing it would just fetch some already known commits. I believe, it should not make a big harm except maybe performance degradation. I have not verified it though.

I'll try to implement it as you described.

**Comment by dscho** [comment]
>     * I thought it could work in line with [f2c696f](https://github.com/git-for-windows/git/commit/f2c696f706d5a19c558f0479d1db7efc0ef42aac)

Right. I thought that that patch would come back to haunt us. It is totally not upstreamable, not only because it uses that hard-coded approach that I don't think would be accepted by Paul Mackerras (who is still the gitk maintainer AFAICT), but also because of the intentionally fake author.

>     * these negavite patterns are there to limit work for `git log`. It some are missing it would just fetch some already known commits. I believe, it should not make a big harm except maybe performance degradation. I have not verified it though.

Good point, but I think that we would want the `--stdin` method in general because it might *not* be purely a performance issue in other, similar cases. And if we can come up with a general fix, I'd much prefer that one.

> I'll try to implement it as you described.

Thank you!

**Comment by max630** [comment]
I'm struggling to find a way to make 2-way redirection in tcl. It looks like [combination of chan and exec](https://wiki.tcl-lang.org/page/exec#19505ac0164a4b4edddd8f4570711583f3512f6f3539d536fb6013cafe8f7c82) could work, but manual for `exec` says that redirectiondo not work in Tk/Windows. Maybe it's outdated (why wouldn't it?), needs some protoing.

another way would be to use a real temporary file but it feels like a drawback.

**Comment by mfriedrich74** [comment]
Redirection works in Linux and in Windows, but exec is very limited regarding this. You could try pipes using open "|...".

If you refer to:
> Note: stdout and stderr are not available in Windows when Tcl is invoked as wish, because Windows does not support stdio for GUI apps.
This is wrong. It is supported, but not visible until a console window is attached to the process. The process can do that using [AttachConsole](https://docs.microsoft.com/en-us/windows/console/attachconsole). Or you find a way to redirect the output to a text window.

**Comment by max630** [comment]
> If you refer to:

it was rather [this](https://www.tcl.tk/man/tcl/TclCmd/exec.htm#M24):

> The Tk console text widget does not provide real standard IO capabilities. Under Tk, when redirecting from standard input, all applications will see an immediate end-of-file; information redirected to standard output or standard error will be discarded.

I tried [this](https://gist.github.com/max630/049bd8acd9d1d07cbe088e5c40715370) example, it seems working. Though maybe I should have tried also starting it as wish. Will see.

**Comment by lostindark** [comment]
I tried this fix locally and it doesn't fix the error I saw. Let me know if you need any logs.

**Comment by dscho** [comment]
> Let me know if you need any logs.

I don't think that it will work if you put the burden of driving your issue forward on others...

**Comment by max630** [comment]
It looks like there is a problem. Apparently `git log --stdin` does not support passing `--not`, it fails with message "fatal: options not supported in --stdin mode". And it is the hashes after "--not" which was causing the issue. Trying to pass "--not" in command line does not seem to help as well, the commits are treated as positive selection.

**Comment by max630** [comment]
Otherwise, the implementation is simple. This diff should be applied to the first commit (second is not needed). It seems working if I still pass args through command line and only files through stdin. It would not protect from too long commandline then, of course.

```
diff --git a/gitk-git/gitk b/gitk-git/gitk
index 0a1cd00511..4ee19329b3 100755
--- a/gitk-git/gitk
+++ b/gitk-git/gitk
@@ -503,8 +503,21 @@ proc getcommits {selid} {
 proc updatecommits_command {args view} {
     global show_notes vfilelimit
 
-    return [concat | git log --no-color -z --pretty=raw $show_notes \
-		   --parents --boundary $args "--" $vfilelimit($view)]
+    set pIn [chan pipe]
+    set pOut [chan pipe]
+    set child [exec sh -c [concat git log --no-color -z --pretty=raw $show_notes --parents --boundary --stdin] <@ [lindex $pIn 0] >@ [lindex $pOut 1] &]
+    close [lindex $pIn 0]
+    close [lindex $pOut 1]
+    foreach arg [concat $args "--" $vfilelimit($view)] {
+        if {[string first "\n" $arg] > -1} {
+            puts "oops: newlines in arguments not supported"
+        } else {
+            puts [lindex $pIn 1] $arg
+        }
+    }
+    close [lindex $pIn 1]
+
+    return [lindex $pOut 0]
 }
 
 proc updatecommits {} {
@@ -566,7 +579,7 @@ proc updatecommits {} {
 	set args $vorigargs($view)
     }
     if {[catch {
-	set fd [open [updatecommits_command $args $view] r]
+	set fd [updatecommits_command $args $view]
     } err]} {
 	error_popup "[mc "Error executing git log:"] $err"
 	return
```

**Comment by max630** [comment]
well maybe the subsequent arguments may prepended with `^`

**Comment by max630** [comment]
@dscho it is rewritten now to use stdin as you have requested

**Comment by max630** [comment]
Fixed syntax error

**Comment by dscho** [comment]
> It looks like there is a problem. Apparently `git log --stdin` does not support passing `--not`, it fails with message "fatal: options not supported in --stdin mode". And it is the hashes after "--not" which was causing the issue. Trying to pass "--not" in command line does not seem to help as well, the commits are treated as positive selection.

Hmm. I tried running this:

```tcl
set input "HEAD^\n--not\nHEAD^^^"
set fd [open [concat | git log -s --stdin <<$input]]
set data [read $fd]
puts "data: $data"
if {[catch {close $fd} err]} {
	puts "ls command failed: $err"
}
```

... and it gave me the expected output: the first two of the latest three commits...

**Comment by dscho** [comment]
> ... and it gave me the expected output: the first two of the latest three commits...

Oh never mind, the `<<$input` is concatenated, so the whitespace means that only the first component of `$input` is used as stdin...

**Comment by dscho** [comment]
>  the `<<$input` is concatenated, so the whitespace means that only the first component of `$input` is used as stdin...

Hah! If I construct `input` by appending values with the `\\n` separator, it is used as `stdin` in its entirety, *and* those `\\n` are translated into newlines, as desired.

Together with replacing the `--not` flag by the `^` prefix, I think we have a way forward here.

**Comment by dscho** [comment]
@max630 thank you for your hard work on this PR. The issue would not have been fixed (in #2170) without you.

**Pull request closed without merging**
