### PR TITLE
Additional error checks for issuing the windows.appendAtomically warning

### PR DESCRIPTION
**Pull request by dsl101**
Check for EBADF as well as EINVAL, as APFS-mounted filesystem returns that errno when atomic append is enabled.

### CODE REVIEW

**Comment by dscho** [comment]
And that read-only flag flipping is no longer required?

**Comment by dscho** [comment]
> No, the read only issue is separate. I commented at the end of the other PR. I thought it had already been merged?

No, the PR has been [closed by you](https://github.com/git-for-windows/git/pull/4484#event-9754368610), probably [by accidentally force-pushing `main`'s tip commit to the branch](https://github.com/git-for-windows/git/pull/4484#event-9754368726). The commit https://github.com/git-for-windows/git/commit/b959cc5b3fd717901912b28e191a1b84cedf497e is still visible, but not reachable from any branch.

**Comment by dsl101** [comment]
Ok. I’m away for a week now, but what’s the right thing here? Can that one
be fixed, or add it to the other one I created for the atomic append
warning?

**Comment by dsl101** [comment]
OK, I'm looking [here](https://github.com/git-for-windows/git/blob/4a1821dfb0c2160a4fcc85d2845f095c54339578/compat/mingw.c#L2743) and that looks like the read only fix is in the main branch, no? That's what made me think it was already merged. So I _think_ my PR for that can stay closed, but please correct me if I'm wrong on that one.

This PR is to fix a different issue (not actually a bug), where the APFS file system returns EBADF when attempting an atomic append. There is already warning code for this against the EINVAL error, so it just broadens the conditions in which that warning will be issued. Setting the config value as advised fixes the issue.

**Pull request closed without merging**
