### PR TITLE
Rebase to v2.37.3

### PR DESCRIPTION
**Pull request by dscho**
The usual pre-release PR for the benefit of the PR build. Range-diff relative to the current tip of the `main` branch:

```diff
   1:  fac4c0aba67 =   1:  ae86b86df35 t9350: point out that refs are not updated correctly
   3:  db70c646cde =   2:  ab69ea86de1 transport-helper: add trailing --
   6:  6489f6f7c04 =   3:  54396e289f2 remote-helper: check helper status after import/export
  14:  c542ac19717 =   4:  9849ef5890e Always auto-gc after calling a fast-import transport
   7:  41a35662f61 =   5:  f719924f143 mingw: demonstrate a problem with certain absolute paths
   8:  7df821df0bf =   6:  666b55b99f4 archive: replace write_or_die() calls with write_block_or_die()
   9:  6e267dc4c96 =   7:  c7d982dd9c4 gitk: prevent overly long command lines
  10:  8489dd925ac =   8:  9e37910108c clean: do not traverse mount points
  16:  038dcc69bfd =   9:  78295fae1fe mingw: allow absolute paths without drive prefix
  17:  7897960c254 =  10:  5cbc301b51a archive: avoid spawning `gzip`
  18:  09f49eb33f3 =  11:  dbcd36cf93b mingw: change core.fsyncObjectFiles = 1 by default
  19:  134b1b5d9d1 =  12:  1f634b91f2c gitk: Escape file paths before piping to git log
  20:  c9a2ff2c0d3 =  13:  c80f11e8337 clean: remove mount points when possible
   4:  927912372b2 =  14:  f343dd8025b mingw: demonstrate a `git add` issue with NTFS junctions
  21:  12aa9ebc3ba !  15:  11264b0ac80 mingw: include the Python parts in the build
    @@ Commit message
     
      ## config.mak.uname ##
     @@ config.mak.uname: else
    + 		USE_GETTEXT_SCHEME = fallthrough
      		USE_LIBPCRE = YesPlease
    - 		NO_CURL =
      		USE_NED_ALLOCATOR = YesPlease
     +		NO_PYTHON =
      		ifeq (/mingw64,$(subst 32,64,$(prefix)))
  22:  c7050ac5829 =  16:  b30468002c7 Config option to disable side-band-64k for transport
  23:  12bedeac8c4 =  17:  d711bd2316b mingw: make sure `errno` is set correctly when socket operations fail
  24:  b9671e2cc09 =  18:  1d10cc432f3 mingw: do resolve symlinks in `getcwd()`
  25:  3bc07677407 =  19:  0038219d9e5 mingw: fix fatal error working on mapped network drives on Windows
  26:  cf6155049e0 =  20:  f51dca19002 clink.pl: fix MSVC compile script to handle libcurl-d.lib
  12:  6821dfcd60f =  21:  ef31fd2696a vcxproj: unclash project directories with build outputs
   2:  373edb47012 =  22:  a05f73311f0 mingw: ensure valid CTYPE
  33:  590459ac7ef =  23:  5eed0857578 t5505/t5516: allow running without `.git/branches/` in the templates
   5:  f3f647d3c13 =  24:  beb3082b1c4 mingw: allow `git.exe` to be used instead of the "Git wrapper"
  11:  0c427c10e50 =  25:  1c305cf1a7d strbuf_realpath(): use platform-dependent API if available
  66:  3a201093682 =  26:  0588767a31f Allow `add -p` and `add -i` with a large number of files
  35:  35ea69555cb =  27:  12a00d1032f t5505/t5516: fix white-space around redirectors
  13:  02d5a1a84c4 =  28:  7e7190c00e5 mingw: ignore HOMEDRIVE/HOMEPATH if it points to Windows' system directory
  15:  51d02b04788 =  29:  cb3b22c6bec http: use new "best effort" strategy for Secure Channel revoke checking
  27:  51c6069ce8a =  30:  c98beec8123 mingw: implement a platform-specific `strbuf_realpath()`
  71:  913ce9c6f7f =  31:  783307fce53 t3701: verify that we can add *lots* of files interactively
  72:  82bdf39ba73 =  32:  58d581bf506 git add -i: handle CR/LF line endings in the interactive input
  73:  6d8ede6bf74 =  33:  6322afcb340 commit: accept "scissors" with CR/LF line endings
  74:  1c0c9c88a67 =  34:  b7ee7309861 t0014: fix indentation
  75:  14ec20efbbe =  35:  64bedae27f1 git-gui: accommodate for intent-to-add files
  38:  e94e702b5fb =  36:  746f5892f92 clink.pl: fix libexpatd.lib link error when using MSVC
  40:  075fe4d1401 =  37:  7ad85bd32b2 Makefile: clean up .ilk files when MSVC=1
  42:  9bfaefae246 =  38:  5b3754877f4 vcbuild: add support for compiling Windows resource files
  45:  0e33326fd30 =  39:  7001ed03db6 config.mak.uname: add git.rc to MSVC builds
  48:  be0746c3998 =  40:  4229e71c73c clink.pl: ignore no-stack-protector arg on MSVC=1 builds
  51:  8f7dc4c0f8e =  41:  7bc5f6b4acd clink.pl: move default linker options for MSVC=1 builds
  54:  8119d8f3d28 =  42:  c49614d0aa1 buildsystems: remove duplicate clause
  57:  cdc043d8cf2 =  43:  15e8d38565f vcxproj: handle resource files, too
  60:  5c92e223a14 =  44:  920266a51d9 vcxproj: ignore -fno-stack-protector and -fno-common
  63:  3bef61c135b =  45:  90f1b5b4471 vcxproj: handle GUI programs, too
  67:  bb6352ba579 =  46:  788496e7d8e win32: add a helper to run `git.exe` without a foreground window
  43:  b1c462ea4a9 =  47:  1f8748ba1ce vcpkg_install: detect lack of Git
  76:  bbd27e0910b =  48:  27ced5b2203 git maintenance: avoid console window in scheduled tasks on Windows
  28:  de128a5c4bf =  49:  3ece0a66fe5 Add a GitHub workflow to generate Git for Windows' Pacman package
  46:  df6b4a047df =  50:  26f3562d514 vcpkg_install: add comment regarding slow network connections
  29:  cb16fef7a8b =  51:  95bd756bfd6 git-artifacts: if GPG secrets are available, use them
  49:  c9db36c16b4 =  52:  10370480f8b vcxproj: support building Windows/ARM64 binaries
  30:  32d28e76c38 =  53:  f94fd9e6168 git-artifacts: also code-sign, if configured via the secrets
  52:  20f57cb5a31 =  54:  38b7c5da5b9 vcbuild: install ARM64 dependencies when building ARM64 binaries
  31:  8c2a60e3d35 =  55:  63e63ae6361 git-artifacts: also build the installer
  55:  18bdadfcd71 =  56:  64f83e8bfdf vcbuild: add an option to install individual 'features'
  32:  bb345f37d2a =  57:  1f9c4f654a8 git-artifacts: also build portable, mingit and mingit-busybox
  58:  902e3442b9c =  58:  98cd770653d cmake: allow building for Windows/ARM64
  34:  8794f063297 =  59:  88c830115a0 git-artifacts: also build 32-bit versions
  61:  ca0fd964b1c =  60:  97b7164d83b ci(vs-build) also build Windows/ARM64 artifacts
  36:  b15d985ab3f =  61:  5e65e9a85f5 git-artifacts: also build the nuget package
  64:  8a879915603 =  62:  1efd586da8f Add schannel to curl installation
  37:  328be50d39c =  63:  706e147a0a3 git-artifacts: allow restricting which artifacts are built
  39:  508ebd56c3e =  64:  845e9252851 git-artifacts: allow specifying repo/ref via workflow_dispatch
  41:  c6c0d5369a7 =  65:  5c68e3e0f31 git-artifacts: cache the build-installers artifact
  44:  4a48a898309 =  66:  47a09632d3d git-artifacts: use the cached build-installers instead of makepkg-git
  47:  307085d62ef =  67:  214ba164b05 git-artifacts: add ARM64 artifacts
  50:  194e1990556 =  68:  cc1428164cd git-artifacts(arm64): avoid hard-linking the dashed built-ins
  53:  70a58bbe6e6 =  69:  938ebc6840b git-artifacts: use a narrower `PATH`
  56:  2eea7ca5ed8 =  70:  d78aee8d4d3 git-artifacts: fix BUILD_ONLY handling for ARM64
  59:  ffa3be6e6a3 =  71:  52da5f1d74b git-artifacts: extend the `SKIP` logic to handle `pkg` and `build-arm64`
  62:  4e646324979 =  72:  ef41657e1d3 git-artifacts: mark all inputs as "not required"
  65:  2a10102c0e3 =  73:  92a6d811ba0 git-artifacts(build-arm64): build artifacts using the intended Git revision
  68:  fd8c1da29ea =  74:  1bde85d7573 git-artifacts: add workaround for GCM Core on ARM64
  69:  1abb28bc31c =  75:  c8bd5242fc4 cmake(): allow setting HOST_CPU for cross-compilation
  70:  48b9e7ff8eb =  76:  db263be09b9 git-artifacts: use the `setup-git-for-windows-sdk` Action
  79:  ea0c4ca0efa =  77:  586e4400087 ci(): add HOST_CPU to CMake command
  86:  c9bf8d863a5 =  78:  d2c03174690 subtree: update `contrib/subtree` `test` target
  92:  7a4acd282b0 =  79:  021caaf2c40 ci(vs-build): download the vcpkg artifacts using a dedicated Action
  93:  e8b37371b37 =  80:  912211cc801 mingw: allow for longer paths in `parse_interpreter()`
  94:  b7890b8b3ad =  81:  ef3e53d7cca compat/vcbuild: document preferred way to build in Visual Studio
  95:  bf35cd0bc1c =  82:  bbaf1f83d40 http: optionally send SSL client certificate
  81:  880bd884322 =  83:  b771d3ad5c3 CMake: default Visual Studio generator has changed
  83:  209d32971d9 =  84:  801018cbc61 .gitignore: add Visual Studio CMakeSetting.json file
  77:  e7725dfc137 =  85:  f15f1574cf1 hash-object: demonstrate a >4GB/LLP64 problem
  87:  5871ae8ce45 =  86:  8b603fbc837 CMakeLists: add default "x64-windows" arch for Visual Studio
  88:  1b07ea74e79 =  87:  820a1f011a2 fsmonitor: reintroduce core.useBuiltinFSMonitor
  78:  1beda0bf058 =  88:  7f159738803 hash_object_file_literally(): use size_t
  96:  d7615cbc653 =  89:  63e22957b03 ci: run `contrib/subtree` tests in CI builds
  97:  aea3d61fcf5 =  90:  f43728f3177 CMake: show Win32 and Generator_platform build-option values
  98:  7b10cc49b0a =  91:  dc9c250f66e init: do parse _all_ core.* settings early
  99:  22b5083adc0 =  92:  8bd0baddd24 Enable the built-in FSMonitor as an experimental feature
  80:  ae5c0f331a0 =  93:  5eec758eb9a object-file.c: use size_t for header lengths
  82:  3c59d92ddef =  94:  c017889e511 hash algorithms: use size_t for section lengths
  84:  98f33cc258e =  95:  12853da8d31 hash-object --stdin: verify that it works with >4GB/LLP64
- 85:  4a593a01ca8 <   -:  ----------- Allow debugging unsafe directories' ownership
  89:  02c0eff434d =  96:  5ce7cff4c57 hash-object: add another >4GB/LLP64 test case
- 90:  06534c4d4fa (upstream: 3f7207e2ea9) <   -:  ----------- mingw: handle a file owned by the Administrators group correctly
 100:  21073ff8926 =  97:  7fe1eb7c4b2 hash-object: add a >4GB/LLP64 test case using filtered input
  91:  1c22e644ea2 !  98:  5879eb5ca3c setup: properly use "%(prefix)/" when in WSL
    @@ setup.c: const char *setup_git_directory_gently(int *nongit_ok)
     +			struct strbuf prequoted = STRBUF_INIT;
      			struct strbuf quoted = STRBUF_INIT;
      
    + 			strbuf_complete(&report, '\n');
     -			sq_quote_buf_pretty(&quoted, dir.buf);
    ++
     +#ifdef __MINGW32__
     +			if (dir.buf[0] == '/')
     +				strbuf_addstr(&prequoted, "%(prefix)/");
    @@ setup.c: const char *setup_git_directory_gently(int *nongit_ok)
     +			sq_quote_buf_pretty(&quoted, prequoted.buf);
     +
      			die(_("detected dubious ownership in repository at '%s'\n"
    + 			      "%s"
      			      "To add an exception for this directory, call:\n"
    - 			      "\n"
-101:  024af913649 (upstream: 7c83470e64e) <   -:  ----------- mingw: be more informative when ownership check fails on FAT32
 102:  28131b9e06e !  99:  c4af75a48ee compat/mingw.c: do not warn when failing to get owner
    @@ Commit message
         Signed-off-by: Derrick Stolee <derrickstolee@github.com>
     
      ## compat/mingw.c ##
    -@@ compat/mingw.c: int is_path_owned_by_current_sid(const char *path)
    +@@ compat/mingw.c: int is_path_owned_by_current_sid(const char *path, struct strbuf *report)
      				    DACL_SECURITY_INFORMATION,
      				    &sid, NULL, NULL, NULL, &descriptor);
      
    @@ compat/mingw.c: int is_path_owned_by_current_sid(const char *path)
     +	if (err == ERROR_SUCCESS && sid && IsValidSid(sid)) {
      		/* Now, verify that the SID matches the current user's */
      		static PSID current_user_sid;
    - 
    + 		BOOL is_member;
 103:  4a58acbb2ef = 100:  dbcf6ec8d9a mingw: $env:TERM="xterm-256color" for newer OSes
-104:  c10cfc81ed5 (upstream: 476e54b1c60) <   -:  ----------- cmake: support local installations of git
 105:  123a7894a5d = 101:  4295ad21a4c winansi: check result and Buffer before using Name
 106:  c011f24925a = 102:  8cd241fd1b4 Add config option `windows.appendAtomically`
 133:  e796f2cd235 = 103:  bab3b669189 git-gui: provide question helper for retry fallback on Windows
 135:  3833e40fc1a = 104:  0334e9ce5de git gui: set GIT_ASKPASS=git-gui--askpass if not set yet
 137:  cff0c901992 = 105:  8fa9f9a16eb git-gui--askyesno: fix funny text wrapping
 139:  5ec6ed87518 = 106:  1776f90ef2d git-gui--askyesno: allow overriding the window title
 141:  0787a03b9ac = 107:  27cfa37d88c respect core.hooksPath, falling back to .git/hooks
 144:  65e72ce6f33 = 108:  571b3c2e2c5 gitk: Unicode file name support
 145:  433cd31c04a = 109:  a2e617a412b gitk: Use an external icon file on Windows
 146:  be688cfbe12 = 110:  1409ef75101 gitk: fix arrow keys in input fields with Tcl/Tk >= 8.6
 142:  8b8caef7a3f = 111:  48f07cd2b3b git-gui--askyesno (mingw): use Git for Windows' icon, if available
 147:  642353ab22b = 112:  791b338b1a2 gitk: make the "list references" default window width wider
 214:  dd48e481b7f = 113:  1084daa7122 reset: reinstate support for the deprecated --stdin option
 215:  cc8bb3d42cf = 114:  86b55ea3b1e mingw: deprecate old-style runtime-prefix handling in interpolate_path()
 204:  2b52d4b14a3 = 115:  3d07d444f2a Modify the Code of Conduct for Git for Windows
 209:  4757d2cb018 = 116:  7f6c6bb4e3a CONTRIBUTING.md: add guide for first-time contributors
 217:  eea7b64a71a ! 117:  84f8d2827ba README.md: Add a Windows-specific preamble
    @@ Metadata
      ## Commit message ##
         README.md: Add a Windows-specific preamble
     
    -    Includes touch-ups by Philip Oakley.
    +    Includes touch-ups by 마누엘, Philip Oakley and 孙卓识.
     
         Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>
     
    @@ README.md
     +Git for Windows
     +===============
     +
    -+[![Open in Visual Studio Code](https://open.vscode.dev/badges/open-in-vscode.svg)](https://open.vscode.dev/git-for-windows/git)
    ++[![Open in Visual Studio Code](https://img.shields.io/static/v1?logo=visualstudiocode&label=&message=Open%20in%20Visual%20Studio%20Code&labelColor=2c2c32&color=007acc&logoColor=007acc)](https://open.vscode.dev/git-for-windows/git)
     +[![Build status](https://github.com/git-for-windows/git/workflows/CI/badge.svg)](https://github.com/git-for-windows/git/actions?query=branch%3Amain+event%3Apush)
     +[![Join the chat at https://gitter.im/git-for-windows/git](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/git-for-windows/git?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
     +
 218:  ad70e7b970a = 118:  862fffb4b99 Add an issue template
 219:  acb3d371a7f = 119:  1d4ef51ec0e Modify the GitHub Pull Request template (to reflect Git for Windows)
 220:  eda823d111a = 120:  1545bcb6100 .github: Add configuration for the Sentiment Bot
 221:  0e1570dd776 = 121:  22cd55b1980 Document how $HOME is set on Windows
 216:  8aa6f51e6dc = 122:  ea0b08f3cce Add a GitHub workflow to monitor component updates
 222:  c7ae93a259f = 123:  396169cf481 SECURITY.md: document Git for Windows' policies
 238:  76e14bd64fb = 124:  761788867b2 MinGW: link as terminal server aware
 223:  a4c481e5d9d = 125:  9ea42113054 vcxproj: allow building with `NO_PERL` again
 224:  549fe1193d7 = 126:  02da463e988 vcxproj: require C11
 225:  9aff3cd80a0 = 127:  c628fe3770d vcxproj: ignore the `-pedantic` option
 226:  01156b8644f = 128:  4ce1741cdad vcxproj: include reftable when committing `.vcxproj` files
 227:  6ad821133a1 = 129:  9ee72897ac4 vcxproj: handle libreftable_test, too
 228:  536f80dea5f = 130:  54fd462a31a vcxproj: avoid escaping double quotes in the defines
 229:  a5b218a81cb = 131:  8603412690a ci: adjust Azure Pipeline for `runs_on_pool`
 230:  59af6af7e10 = 132:  2b79cfef48e ci: stop linking the `prove` cache
 231:  6fdd48e9896 = 133:  cb4cc3d7862 ci: reinstate Azure Pipelines support
 232:  f4a700bff3f = 134:  14895fc5ba0 azure-pipeline: drop the `GETTEXT_POISON` job
 233:  45bfc918939 = 135:  34e2791b6b9 azure-pipeline: stop hard-coding `apt-get` calls
 234:  6288010aac8 = 136:  39dbdd8cf87 azure-pipeline: drop the code to write to/read from a file share
 235:  29b6046641c = 137:  c99c1ee06b8 azure-pipeline: use partial clone/parallel checkout to initialize minimal-sdk
 236:  d9ad0b81cc5 = 138:  9dd6cc67da8 azure-pipeline: downcase the job name of the `Linux32` job
 237:  03ca5c00f5b = 139:  ac363dd379c azure-pipeline: run static-analysis on bionic
 107:  0020768ece7 = 140:  14bb1e7decd Win32: make FILETIME conversion functions public
 108:  acdf2a9386e = 141:  1a0db9dd80b Win32: dirent.c: Move opendir down
 109:  d5d8220fc86 = 142:  2a6031ebff8 mingw: make the dirent implementation pluggable
 110:  14f083ad8ec = 143:  5ed1165b2c7 Win32: make the lstat implementation pluggable
 111:  e2c5f7282ae = 144:  4c7a0e8ccf3 add infrastructure for read-only file system level caches
 112:  28687653237 = 145:  04f0eea085d mingw: add a cache below mingw's lstat and dirent implementations
 113:  ef70d295248 = 146:  7732cba03b7 fscache: load directories only once
 114:  c0095f864ca = 147:  2423add5f77 fscache: add key for GIT_TRACE_FSCACHE
 115:  42437186165 = 148:  9efa26d3b0b fscache: remember not-found directories
 116:  01e174362bc = 149:  bab6c545645 fscache: add a test for the dir-not-found optimization
 117:  992602ec191 = 150:  07ed04d725a add: use preload-index and fscache for performance
 118:  7193e52e404 = 151:  bb9eda89a99 dir.c: make add_excludes aware of fscache during status
 119:  1ee8e8268f6 = 152:  5481d04547d fscache: make fscache_enabled() public
 120:  231737480fc = 153:  ac0d931a7a0 dir.c: regression fix for add_excludes with fscache
 121:  bb9e2884d03 = 154:  222ea588e10 fetch-pack.c: enable fscache for stats under .git/objects
 122:  66712d64285 = 155:  80834080ca6 checkout.c: enable fscache for checkout again
 123:  a285dfb8b6e = 156:  19fcc4ec097 Enable the filesystem cache (fscache) in refresh_index().
 124:  50b975f745f = 157:  93d17771496 fscache: use FindFirstFileExW to avoid retrieving the short name
 125:  d8afb7b0f92 = 158:  c8d1ef4a9b5 status: disable and free fscache at the end of the status command
 126:  99794df3b3d = 159:  ebd70331444 fscache: add GIT_TEST_FSCACHE support
 127:  b5d16d59bbf = 160:  02785305628 fscache: add fscache hit statistics
 128:  869517f4587 = 161:  c2e5684ccf9 mem_pool: add GIT_TRACE_MEMPOOL support
 129:  c82bf0511e0 = 162:  6e64932f97b fscache: fscache takes an initial size
 130:  36b92882417 = 163:  b69b01ccb22 fscache: update fscache to be thread specific instead of global
 131:  47508fc68f4 = 164:  63cd434900d fscache: teach fscache to use mempool
 132:  8dbcf0c41e7 = 165:  7e70584fe00 fscache: make fscache_enable() thread safe
 134:  064cf60e5f8 = 166:  88ec3190d73 fscache: teach fscache to use NtQueryDirectoryFile
 136:  b5bab5b6152 = 167:  9f5d680b1d5 unpack-trees: enable fscache for sparse-checkout
 138:  d71360ee791 = 168:  20e9add836b fscache: remember the reparse tag for each entry
 140:  e481cd66f69 = 169:  11d4c65cc9d fscache: implement an FSCache-aware is_mount_point()
 143:  6d92ef1395b = 170:  9ccebb8258b clean: make use of FSCache
 148:  43f5e272c93 = 171:  88a98531bbc pack-objects (mingw): demonstrate a segmentation fault with large deltas
 149:  7568824164a ! 172:  d8c246277fa mingw: support long paths
    @@ compat/mingw.h: typedef _sigset_t sigset_t;
      
      int mingw_core_config(const char *var, const char *value, void *cb);
      #define platform_core_config mingw_core_config
    -@@ compat/mingw.h: int is_path_owned_by_current_sid(const char *path);
    +@@ compat/mingw.h: int is_path_owned_by_current_sid(const char *path, struct strbuf *report);
      int is_valid_win32_path(const char *path, int allow_literal_nul);
      #define is_valid_path(path) is_valid_win32_path(path, 0)
      
 150:  489e100a736 = 173:  3df12f326ff Win32: fix 'lstat("dir/")' with long paths
 151:  2c8d9eba90f = 174:  9a2ae5fab8d mingw: ensure that core.longPaths is handled *always*
 179:  f425b361594 = 175:  f65d8c4849e compat/fsmonitor/fsm-*-win32: support long paths
 152:  8f89b105eff = 176:  070982a9d7b mingw: Support `git_terminal_prompt` with more terminals
 153:  d767f1ac1cd = 177:  54cc64cf76e compat/terminal.c: only use the Windows console if bash 'read -r' fails
 154:  024c8c51ebf = 178:  e397113fd15 mingw (git_terminal_prompt): do fall back to CONIN$/CONOUT$ method
 155:  fbdcca305d5 = 179:  1c71006aaf0 Unbreak interactive GPG prompt upon signing
 156:  578519da826 = 180:  fc800a22ea7 strbuf_readlink: don't call readlink twice if hint is the exact link size
 157:  28674d67b53 = 181:  8fcb007ecad strbuf_readlink: support link targets that exceed PATH_MAX
 158:  7f052b895ba = 182:  a1e07d30aaa lockfile.c: use is_dir_sep() instead of hardcoded '/' checks
 159:  50dfbd74794 = 183:  139aaa127fa Win32: don't call GetFileAttributes twice in mingw_lstat()
 160:  66e8f8ee798 = 184:  0a3cc5502bc Win32: implement stat() with symlink support
 161:  25ebb7b96bd = 185:  928faafa714 Win32: remove separate do_lstat() function
 162:  cae9a13c3ec = 186:  6e15d1aada3 Win32: let mingw_lstat() error early upon problems with reparse points
 180:  cd7b80a8f3c = 187:  845827aef34 clean: suggest using `core.longPaths` if paths are too long to remove
 163:  54a369f4abd = 188:  1b8c2fbf53b mingw: teach fscache and dirent about symlinks
 164:  3f394c5829a = 189:  45d6ec8ffd9 Win32: lstat(): return adequate stat.st_size for symlinks
 165:  cbdc19e983e = 190:  69276cde84d Win32: factor out retry logic
 166:  900825e399c = 191:  a2dd3059f5d Win32: change default of 'core.symlinks' to false
 167:  51cb530c076 = 192:  1c4ec86c0a0 Win32: add symlink-specific error codes
 168:  7417439e300 = 193:  455739b7506 Win32: mingw_unlink: support symlinks to directories
 169:  a8a7d36c760 = 194:  1101585fdf1 Win32: mingw_rename: support renaming symlinks
 170:  c589dd21181 = 195:  8d7f000f425 Win32: mingw_chdir: change to symlink-resolved directory
 171:  f2a59dddb13 = 196:  469d5337935 Win32: implement readlink()
 172:  060ede66bbc = 197:  f918fbcee38 mingw: lstat: compute correct size for symlinks
 173:  a2f0b88e1d1 = 198:  9cbacce1cf7 Win32: implement basic symlink() functionality (file symlinks only)
 174:  df6f666a0ad = 199:  3637e40b5bd Win32: symlink: add support for symlinks to directories
 175:  fae0f6e6f37 = 200:  353df52147a mingw: try to create symlinks without elevated permissions
 176:  ee928f0c2bb = 201:  94fecaef6e1 mingw: emulate stat() a little more faithfully
 177:  1daf2dee73e = 202:  98b32d1b0f9 mingw: special-case index entries for symlinks with buggy size
 181:  93bd88dd002 = 203:  1594420c06b Win32: symlink: move phantom symlink creation to a separate function
 182:  a298859531d = 204:  c8e87f64e7d Introduce helper to create symlinks that knows about index_state
 183:  d8076430601 = 205:  19311326d5a mingw: allow to specify the symlink type in .gitattributes
 184:  7abd4804dfe = 206:  0e12da15ca8 Win32: symlink: add test for `symlink` attribute
 178:  84576ccdaf9 = 207:  ec52e55c50c mingw: introduce code to detect whether we're inside a Windows container
 185:  230fd82c834 = 208:  fe2758ce28f mingw: explicitly specify with which cmd to prefix the cmdline
 202:  c682feb4d34 = 209:  2c6591ec3a6 mingw: when running in a Windows container, try to rename() harder
 186:  560eabba17c = 210:  4dc74b2c631 mingw: when path_lookup() failed, try BusyBox
 205:  a2c7e43c021 = 211:  daa52d95c8a mingw: move the file_attr_to_st_mode() function definition
 187:  b78cc311f43 = 212:  34d54e8bf81 test-lib: avoid unnecessary Perl invocation
 210:  cfefd0193e7 = 213:  9f6d0ac572a mingw: Windows Docker volumes are *not* symbolic links
 188:  32e1e90ab45 = 214:  6c74c6f54eb tests: replace mingw_test_cmp with a helper in C
 189:  1fdbf5fcc98 = 215:  f8300502736 test-tool: learn to act as a drop-in replacement for `iconv`
 190:  295b60a1e78 = 216:  7c340fc2458 tests(mingw): if `iconv` is unavailable, use `test-helper --iconv`
 191:  9aab0fdc841 = 217:  50fceecf070 gitattributes: mark .png files as binary
 192:  452fd5ae021 = 218:  4e2afb46eb3 tests: move test PNGs into t/lib-diff/
 193:  322f02324a3 = 219:  7bf0a3cde2e tests: only override sort & find if there are usable ones in /usr/bin/
 194:  59fa283a153 = 220:  e099c34988b tests: use the correct path separator with BusyBox
 195:  024e9be9f54 = 221:  2275b999b36 mingw: only use Bash-ism `builtin pwd -W` when available
 196:  3c6e0f0a3b5 = 222:  cf7e9516edc tests (mingw): remove Bash-specific pwd option
 197:  66c241adfb8 = 223:  891699c5598 test-lib: add BUSYBOX prerequisite
 198:  f5cc442e00c = 224:  ec883ee7add t0021: use Windows path when appropriate
 199:  3812f966b18 = 225:  2dadb438ce7 t5003: use binary file from t/lib-diff/
 200:  4d517935441 = 226:  a0cdc758536 t5532: workaround for BusyBox on Windows
 201:  bea64becf6f = 227:  e53a418a3c4 t5605: special-case hardlink test for BusyBox-w32
 203:  75a4758739b = 228:  ad63bf49eea t5813: allow for $PWD to be a Windows path
 206:  07c927f5bcc = 229:  06080f01e82 t9200: skip tests when $PWD contains a colon
 207:  3a821fdd40d = 230:  56963d080ba mingw: kill child processes in a gentler way
 208:  56cf0d4dbff = 231:  d3d2f8e38e5 mingw: do not call xutftowcs_path in mingw_mktemp
 211:  e8ab73ce936 ! 232:  4d60df91839 mingw: add a Makefile target to copy test artifacts
    @@ Commit message
     
      ## config.mak.uname ##
     @@ config.mak.uname: else
    - 		NO_CURL = YesPlease
    + 		NO_PYTHON = YesPlease
      	endif
      endif
     +ifeq (i686,$(uname_M))
 212:  04ede4ba6e8 = 233:  f0da0f37841 mingw: really handle SIGINT
 213:  fa6e48f4917 = 234:  d1f6dc35a52 Partially un-revert "editor: save and reset terminal after calling EDITOR"
-239:  ef302c83ea9 (upstream: 82ba1191ffe) <   -:  ----------- lstat(mingw): correctly detect ENOTDIR scenarios
-240:  b3c93a06118 <   -:  ----------- fixup! README.md: Add a Windows-specific preamble
-241:  e049fccb603 <   -:  ----------- amend! README.md: Add a Windows-specific preamble
```

### CODE REVIEW

**Comment by dscho** [comment]
> ```diff
> - 85:  4a593a01ca8 <   -:  ----------- Allow debugging unsafe directories' ownership
> ```

This merits a comment and a link: while I was [contributing the corresponding patch series](https://lore.kernel.org/git/pull.1286.git.1657700238.gitgitgadget@gmail.com/), Junio pointed out [a better way](https://lore.kernel.org/git/xmqqy1wv2x1n.fsf@gitster.g/), I implemented that, and it was accepted upstream and made this here patch obsolete. That's why it is okay that we drop it here.

Some people might be surprised to no longer see the suggestion to set `GIT_TEST_DEBUG_UNSAFE_DIRECTORIES` and to no longer find any mention of it in the source code/the documentation, but it's simply no longer necessary.

**Comment by dscho** [comment]
The [Git artifacts build is running](https://dev.azure.com/git-for-windows/git/_build/results?buildId=105101&view=results).

**Review by vdye — APPROVED** [review]
:shipit:

**Comment by dscho** [comment]
I started [the Release Pipeline](https://dev.azure.com/git-for-windows/git/_releaseProgress?_a=release-pipeline-progress&releaseId=264).

**Pull request merged**
