### PR TITLE
fsmonitor: handle RegisterApplicationRestart() and CTRL_C_EVENT

### PR DESCRIPTION
**Pull request by jeffhostetler**
Teach the fsmonitor--daemon to register itself with Resource Manager
so that the Git for Windows installer can stop and restart them during
an upgrade.  Without this, the installer cannot update the .EXE and
.DLLs that the daemon process is using.

Also teach the fsmonitor--daemon to handle CTRL-C events properly.
The Resource Manager sends a CTRL_C_EVENT to the process to ask it to
shutdown during the upgrade.  (The system also sends this event when
the user types a CTRL-C in the console window.)

NEEDSWORK: The solution here substitutes a trivial `git version`
command instead of the proper command to restart the fsmonitor daemon
because of Windows complications.  We don't really care if the daemon
restarts immediately after the installer finishes or if it is started
later by the first client command.  Our primary goal here is to let
the installer stop running daemons and do the update.

Signed-off-by: Jeff Hostetler <jeffhost@microsoft.com>

### CODE REVIEW

**Comment by jeffhostetler** [comment]
To test this:
[1] I installed v2.31.1.windows.1 in c:\program files\git.
[2] I built this version locally with `make -j32 prefix='c:/program files/git/mingw64'
[3] From an elevated SDK bash, I installed it with `make -j32 prefix='c:/program files/git/mingw64 install'
[4] Using a normal SDK bash, I started the daemon in a workdir using `c:/program files/git/ming64/bin/git.exe fsmonitor--daemon run`  (Don't use the version of bash installed in with v2.31.1 because that causes additional processes to block us.)
[5] I used the installer for v2.32.0-rc1.windows.1 to try to overwrite the EXEs/DLLs in `c:/program files/git/mingw64`.

At this point, the installer should complain that "OPTIONAL" git.exe processes exist. Clicking next/install will send them CTRL_C_EVENTS and they will exit.  The fsmonitor-daemon processes will exit and the installer will continue.

**Comment by dscho** [comment]
Summarizing the private conversation I had with @jeffhostetler:
- it is unclear how to best get rid of the empty console windows when restarting. We could
  - not restart the FSMonitor daemon at all,
  - override the restart by launching the daemons ourselves through `headless-git.exe` using the command-line obtained via [`GetApplicationRestartSettings()`](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getapplicationrestartsettings)
  - add an undocumented option that will hide the console window (this would still flash)
- it might be better to side-step the restart manager API at all, obtaining the command-line of the `git.exe` processes by [reading the process memory](https://stackoverflow.com/questions/6530565/getting-another-process-command-line-in-windows), and
  - either just call `TerminateProcess()` on the `fsmonitor--daemon run` ones, or
  - allocating memory via `VirtualAllocEx()` in the process and then `CreateRemoteThread(... GetProcAddr("GetCurrentDirectoryW")...)` and then `ReadProcessMemory()` to obtain the current working directory so that we can call `git -C <dir> fsmonitor--daemon --stop`
  - or simply annotate the to-be-terminated processes with `(FSMonitor)`.

**Comment by jeffhostetler** [comment]
What if we had each instance of the daemon create a named pipe with a name containing both the git version number and the pid and some prefix to help a FindFirst/FindNext on the NPFS iterate over all of them.  (this would be in addition to the named pipe that clients make requests on.)  then the daemon could also listen for connections on this new pipe and support a few verbs that we need -- like stop or get-command-line or get-workdir or get-version.  the the installer would have enough info to stop and restart them if it wanted to.

alternatively, we could expand the set of verbs on the existing pipe to include them.  we'd have to rename the pipe to this naming scheme for discovery mechanism, and maybe in include a symlink-like file in the .git directory to point to it for clients to use.

this would also let us have a 'git fsmonitor--daemon list-all' and '... kill-all' using the same discovery mechanism.  i'm not sure this is necessary, but it would be useful for me.  and i'm not sure how we'd do it on the other platforms.  on the other hand, it would let the installer delegate a lot of that work to me.

just thinking out loud....

**Comment by dscho** [comment]
@jeffhostetler as promised, I took over during your vacation. Here is a PR implementing what is currently my favorite attempt to address this: https://github.com/git-for-windows/build-extra/pull/353 (in a nutshell, it enumerates the named pipes opened by the FSMonitor daemons, and then stops them via the full path deduced from the pipes' names).

I'll let this sit for a few days (taking the weekend off myself) and probably merge that PR, then close this here PR.

**Comment by dscho** [comment]
As promised, I'll close this PR.

**Pull request closed without merging**
