### PR TITLE
Merge v2.39.1.windows.1

### PR DESCRIPTION
**Pull request by derrickstolee**
This PR takes the embargoed release tag `v2.39.1.windows.1` and merges it into the `main` branch.

It likely that I messed something up in the order of releasing the security release and merging the [security advisory](https://github.com/git-for-windows/git/security/advisories/GHSA-v4px-mx59-w99c).

### CODE REVIEW

**Review by vdye — APPROVED** [review]
This looks good to me. The CI failures seem either transient (the VS build) or a known issue (`linux-musl`).

**Comment by derrickstolee** [comment]
Also making note that the `check-whitespace` job fails on this PR, but it won't cause future PRs to fail because that job checks only the incoming commits.

**Comment by derrickstolee** [comment]
And while some pull request builds are still completing, the push ones are done.  Merging.

**Review by mrizwan-az — COMMENTED** [review]
updating changes included.

**Pull request merged**
