### PR TITLE
Add DEP, ASLR and HE-ASLR support.

### LINKED ISSUE #608: ASLR not enabled for Git for Windows executables
It seems most of the executables of Git for Windows didn't have ASLR enabled, such as git-bash.exe, git-cmd.exe, unins000.exe, bin/bash.exe, bin/git.exe, bin/sh.exe, etc. Are there any reasons for not enabling ASLR for these files?
Version: 2.6.3.windows.1

### PR DESCRIPTION
**Pull request by ismail**
This should fix #608 but I cannot test it.

### CODE REVIEW

**Comment by rimrul** [comment]
Please rework your [commit messages](https://github.com/git-for-windows/git/wiki/Good-commits#commit-messages).

**Comment by ismail** [comment]
@rimrul Thanks for the heads up, I reworked commit messages.

**Comment by dscho** [comment]
@ismail thanks for doing this.

Unfortunately, I get an access violation ("segmentation fault") immediately upon starting `git.exe`. It appears that `libintl-8.dll` is incompatible with ASLR for some reason and causes this, before `git.exe`'s own `main()` is even reached.

**Comment by dscho** [comment]
Turns out that reverting the ASLR^2 patch fixes that segmentation fault...

**Comment by ismail** [comment]
@dscho that is probably because DLL's need some other start address (image base), is there a flag only applied to DLLs?

**Comment by dscho** [comment]
@ismail Please note that I only recompiled Git, not that library... So I fear we will have to do without ASLR^2, at least for now.

In related news, I did revert the last commit of this PR locally and the test suite passes so far (it is almost 50% through, but this is my slow VM because I develop two other things on my main development machine, so both SDKs (and the full CPU) are used to the max). Looking good!

**Comment by ismail** [comment]
Good enough, we can work on ASLR^2 later on :)

**Comment by dscho** [comment]
Thanks!

**Comment by ismail** [comment]
You are very welcome. :)

**Pull request closed without merging**
