### PR TITLE
Allow GIT_PS1_COMPRESSSPARSESTATE to be unset

### PR DESCRIPTION
**Pull request by AnyOldName3**
Resolves https://github.com/git-for-windows/git/issues/2799

### CODE REVIEW

**Comment by AnyOldName3** [comment]
I don't think the CI failure is related - the linker's complaining about `expat.lib` being missing, but I've just edited an unrelated shell script.

**Review by dscho — CHANGES_REQUESTED** [review]
Great find!

Would you mind, though, making the commit message a little bit more stand-alone? I have something along this in mind:

```
prompt: avoid using unset variables

After `set -u` in Bash, [...]

This fixes https://github.com/git-for-windows/git/issues/2799

Signed-off-by: [...]
```

**Comment by dscho** [comment]
Heads-up: @szeder provided a related patch in https://lore.kernel.org/git/20200911131943.GA23146@szeder.dev/t/#u (although it lacks a comprehensive commit message so far).

**Review by dscho — APPROVED** [review]

**Comment by dscho** [comment]
I'll just go ahead and merge this so that we do not lose it (my hope was that this would get combined with @szeder's efforts, but they seem to have stalled).

**Pull request merged**
