### PR TITLE
Symlink support

### PR DESCRIPTION
**Pull request by kblees**
This with https://github.com/git-for-windows/msys2-runtime/pull/10 should fix issue #117

I only tested this as admin with UAC disabled, so feedback from end users with UAC is welcome.

Design goals:

 * Symlinks should be disabled by default (due to the many quirks with Windows symlinks such as permissions, UAC, D/F conflicts, '..' path resolution etc.).
 * Existing functionality should not be affected if symlinks are disabled (i.e. guard symlink-specific code with `if (has_symlinks)`).
 * Minimize changes to core git code and the test suite.
 * Don't try to resolve symlinks manually (i.e. let Windows do the job by opening the symlink and using `Get*ByHandle()`).

To run the test-suite with symlinks enabled:
```
export MSYS=winsymlinks:nativestrict
make test # or prove...
```

### CODE REVIEW

**Comment by dscho** [comment]
Thank you, this looks really good. I set aside some time to review tomorrow.

**Comment by dscho** [comment]
> Thank you, this looks really good. I set aside some time to review tomorrow.

The time I set aside of course got eaten up by unforeseen real life issues. Sorry about that. Reviewing now.

**Comment by dscho** [comment]
This Pull Request is really a pleasant gift, thank you so much! It is non-intrusive (only two test cases are touched, in a well-described manner), exactly as I hoped it would be possible.

Will let my VM run the tests now.

**Comment by kblees** [comment]
Updated the PR with the fixes suggested by @dscho. Previous version (and per-commit discussion) can be found here: https://github.com/kblees/git/commits/kb/symlinks-v0.

**Comment by dscho** [comment]
Thank you so much! My machine is currently building the new msys2-runtime version, which is required for this to work, but I will merge now already lest I forget ;-)

**Comment by dscho** [comment]
msys2-runtime is uploaded.

**Comment by chrisrichard** [comment]
Thanks for doing this. I think it's a really important feature.

It's working well for me except for one little wrinkle that seems to crop up on directory links that were created on *nix. On Windows, git sees the destination path without the trailing slash, which causes it report changes immediately following a clone:

```
diff --git a/public_html/public/wp-content b/public_html/public/wp-content
index 6787298..efcdaa6 120000
--- a/public_html/public/wp-content
+++ b/public_html/public/wp-content
@@ -1 +1 @@
-../content/
+../content
```

**Comment by dscho** [comment]
@chrisrichard could you make a minimal repository demonstrating this?

**Comment by dscho** [comment]
@chrisrichard oh, and it might be a good idea to open a new ticket for this so that other people who share your problem will find it more easily. Thanks.

**Comment by chrisrichard** [comment]
#210

**Comment by jwittner** [comment]
Was this tested with mklink /D symlinks? I can add and commit them just fine, but when cloning the newly created symlink is a file symlink instead of a directory one.

I.E <SYMLINK> instead of <SYMLINKD>

**Comment by dscho** [comment]
@jwittner please make sure that your markup actually shows what you have to say (I enclosed the `<...>` in backticks so they were actually visible).

You did not specify whether the symlink target exists after cloning. If it does not, Git has *no way* to tell whether it is a file or directory symlink. So in that case what you see is expected.

**Comment by jwittner** [comment]
@dscho sorry about that, and thanks for getting back to me here. I gotta say too that I've been perusing this repo a lot today and your effort is an inspiration.

The target is in a submodule so I guess it's existence would depend on whether the recursive clone checks out submodules before or after the main repo. If it's after then that would make sense!

**Comment by dscho** [comment]
> I gotta say too that I've been perusing this repo a lot today and your effort is an inspiration.

Thank you for this lovely feedback!

> The target is in a submodule so I guess it's existence would depend on whether the recursive clone checks out submodules before or after the main repo.

Yes. And the main repo is checked out first (the information which submodules exist, and from where to clone them, is in the worktree of the parent repository, so it has to be that way).

Having said that, the code in Git for Windows should update the symlink type when the target is available. Could you run `git status` and check the symlink type after that?

**Comment by jwittner** [comment]
Right, the order ops re: submodules makes sense, just didn't know if git was doing something fancy. 

I tried running a `git status` but it did not update the symlink. However, if I delete the `SYMLINK` and do a `git checkout -- .` then I get the desired `SYMLINKD`. Maybe there's another command I could run besides `git status` that wold do the update you're thinking of?

If we can't find a simple command to run to re-resolve symlinks post recursive clone, I'm definitely willing to try to work out a potential solution with you and go through the effort to ramp up on the project and try to implement it. Though obviously as a first time contributor to the project that might take me a bit. =)

Thanks again for all your help!

**Comment by jwittner** [comment]
If we run `FOR /f "tokens=*" %a in ('dir /A:L /B /S') DO DEL "%a" && git checkout -- "%a"` in the project folder after recursive clone, the symlinks to submodules will resolve themselves. Is that something we can add to the process?

**Comment by jwittner** [comment]
Should I create and move this discussion to an issue?

**Comment by csware** [comment]
Are these changes going to be submitted upstream to vanilla git?

**Comment by dscho** [comment]
Hopefully at some stage. Too much else to do for the moment. Feel free to help.

**Pull request merged**
