### PR TITLE
Correct fscanf formatting string for I64u values

### PR DESCRIPTION
**Pull request by weakcamel**
Signed-off-by: Waldek Maleska <w.maleska@gmail.com>

### CODE REVIEW

**Comment by dscho** [comment]
Please note that force-pushing (`git push origin +HEAD` or something similar) will update Pull Requests, so you can reuse a Pull Request, once opened, for subsequent revisions of the same topic branch. GitHub really rocks!

**Comment by weakcamel** [comment]
Yeah, probably. Do you have a suggestion how to distunguish when the %llu is supported or not? I thought it was in fact the __USE_MINGW_ANSI_STDIO macro, now I'm a bit confused.

**Comment by dscho** [comment]
> Do you have a suggestion how to distinguish when the `%llu` is supported or not? I thought it was in fact the `__USE_MINGW_ANSI_STDIO` macro, now I'm a bit confused.

Oh, sorry, I should have clarified that I was talking about supporting non-MSys2 setups, too. When we submit patches upstream (i.e. got the Git mailing list) after testing them enough in Git for Windows, they need to compile not only in our development environment, but also on Linux, MacOSX, Solaris, AIX, etc. In those cases, it is possible that `inttypes.h` does not define `PRIuMAX` (or `SCNuMAX`), and in those cases, `mingw.h` will not be included at all.

That is why `git-compat-util.h` has these lines:

```c
#ifndef PRIuMAX
#define PRIuMAX "llu"
#endif
```

This let's Git's source be compiled even in setups where `PRIuMAX` is not `#define`d. Now, I would expect that in environments where `PRIuMAX` is not available, `SCNuMAX` is probably not available, either. Therefore, I would simply add the lines

```c
#ifndef SCNuMAX
#define SCNuMAX PRIuMAX
#endif
```

after the `PRIuMAX` lines. Note that I would suggest to use the `PRIuMAX` constant here, in the off-case that some environment `#define`s the `PRIuMAX` constant but *not* the `SCNuMAX` constant. In those cases, I do not want to risk a skew here, but use the same value as `PRIuMAX`.

Now, we have a conditional definition of the `PRIuMAX` constant even in `mingw.h`, to support build environments where there is either no `inttypes.h` or it does not define that constant (there must be some, otherwise that conditional definition would not be in `mingw.h`). To continue to support those environments, `SCNuMAX` should be defined the same way there, too.

> where should I target my pull requests, the 2.4.0-rc?

The best is still to target `master`. The `update-to-2.4.0-rc` branch is only there because we did not know whether `2.3.5` or `2.4.0` would come out earlier, and target that version. (In the meantime, 2.3.5 came out, so now we will target `2.3.5` in our `master` branch.

**Comment by weakcamel** [comment]
Can't tell you how much I appreciate this explanation. Thank you!
I was under the impression that the code base is too different for porting those changes back to the Unix/Linux, but now I'm completely clear on the subject.

I'll be away (also from my PC) for a few days, but absolutely not gone ;-) and once back, I'll digging through the current small tasks (or this one, if it'll still be around - you guys move really fast).

**Comment by dscho** [comment]
No problem. See you soon... I hope?

**Comment by weakcamel** [comment]
Definitely. How else could I return the warm and patient welcome? :-)

**Pull request closed without merging**
