### PR TITLE
Make `git config --system` work like you think it should on Windows

### PR DESCRIPTION
**Pull request by dscho**
I cannot count how many times the existence of the Git config in ProgramData caused confusion, most recently in https://github.com/git-for-windows/git/issues/2348.

These days and age, it seems to be in fashion to double down on bad ideas rather than admitting mistakes, but I would like to believe that it is better to see a bad decision for what it is and revert it. It took me long enough!

So rather than trying to explain the concept of `C:\ProgramData\Git\config` and keeping Git for Windows' system config out of everybody's sight, yet having a prominent way with `git config --system` to access the latter while not having any intuitive way for the former, it is past time to reconcile both already, into a location that is both intuitive and clarifies the ownership: this is Git for Windows' system config, other Git implementations are free to use it, but not to modify it.

This PR is a small part of what is necessary to fix the mess, the installer will also have to be updated, and there needs to be a big notice in the release notes.

My plan is to merge this PR tomorrow, in time for Git for Windows v2.24.0-rc0.

### CODE REVIEW

**Comment by dscho** [comment]
I canceled the Azure Pipeline because of the pesky `perforce` problem that made the macOS jobs fail (again!). A tentative fix is here: https://github.com/git-for-windows/git/pull/2359. Once merged, I will re-run the Azure Pipeline.

**Comment by ethomson** [comment]
Hmm.  The goal of the `ProgramData` file was that it was actually supposed to be a shared configuration file.  So that you didn't have two applications working in the same git repository with two different ideas of `core.autocrlf` and the like.

What I would like to see is to actually have a truly _system-wide configuration file_.  I agree that having four configuration locations, but only on Windows, is confusing.  But I think that this regresses the already-tenuous compatibility between Git for Windows, Portable Git, and the other implementations.

**Comment by dscho** [comment]
> What I would like to see is to actually have a truly _system-wide configuration file_.

@ethomson If you have a splendid idea where that should go, I want to hear it: the recent security fix for the `C:\ProgramData\Git\config` support indicated rather strongly that it is not a good spot.

Also, I am really happy to scrap support for `C:\ProgramData\Git\config` so that Portable Git finally gets truly portable again. That was pointed out to me multiple times, and I finally acted.

So I could imagine that we _might_ end up with another location instead of `C:\ProgramData\Git\config`, but that would still need to _not_ be heeded by Portable Git, therefore I think that this PR is still addressing an important issue in the right way. My plan for MinGit is to use `[include]path=C:\Program Files\Git\etc\gitconfig` in _its_ system config, and if we end up wanting a shared config (which JGit seems totally fine _not_ to buy into), we should use the same strategy in Git for Windows so that Portable Git remains unaffected.

**Comment by ethomson** [comment]
> Also, I am really happy to scrap support for C:\ProgramData\Git\config so that Portable Git finally gets truly portable again. That was pointed out to me multiple times, and I finally acted.

I'm sorry, I don't understand the motivation here.  People want Portable Git to not read the system configuration file?  What's the rationale?

That's just for curiosity's sake.  I feel like Portable Git being unique and not reading the system configuration location is fine, but there are myriad mechanisms that we can use to accomplish that, and it's really rather orthogonal to this discussion.  (Meaning, you could remove its support for the `ProgramData` location today.)

> My plan for MinGit is to use [include]path=C:\Program Files\Git\etc\gitconfig in its system config

I feel like we could alternately just agree on a system-wide configuration location and not settle for `include`ing the system-wide configuration location in a thing that's called the "system config" but isn't actually system-wide.

I know that this is Weird For Us since Git for Windows is really a distribution of a POSIX-like environment, not just a single application, but I think that instead of looking at that as the environment that we have to live in, we should look at what our users want.  And I don't think that they want to understand that different clients have to read different "system config" files because they're different distributions of POSIX-like environments.

Including the common one is a clever solution, but I feel like we could just agree on where the common one goes in the first place and forget about `$(prefix)/etc` entirely.

**Comment by ethomson** [comment]
Having said that, I suppose that I really don't care _that much_ since libgit2, at least, goes looking for your `etc` directory to read that configuration file.

I am concerned about what this means for libgit2's backward compatibility.  I suppose it's your installer that might deal with the new configuration files?  What do you have planned here?

What if I have stuff in my `ProgramData` config and install the newest version of Git for Windows?  Is that ignored?  Migrated to a different file?

**Comment by dscho** [comment]
> People want Portable Git to not read the system configuration file? What's the rationale?

@ethomson people who use Portable Git want to read the system config _in that Portable Git, and _only_ that one.

Reading from outside of that Portable Git makes it -- by definition -- non-Portable.

> I am concerned about what this means for libgit2's backward compatibility. I suppose it's your installer that might deal with the new configuration files? What do you have planned here?
> 
> What if I have stuff in my `ProgramData` config and install the newest version of Git for Windows? Is that ignored? Migrated to a different file?

My plan is to teach the Git for Windows installer to look for current settings (but only the ones that you can set via the installer) in the system config, and if it is not found in the expected place, go and look at ProgramData (if there is one).

If you have settings in ProgramData, you have to migrate them manually.

Since I expect the number of people who even _know_ about ProgramData to be at most in the double-digit numbers, I don't think this is too serious of a backwards-incompatibility.

**Comment by dscho** [comment]
> Not sure how to get upstream docs to carry G-f-W notes... [maybe a line in the upstream "For additional Git for Windows notes, see https..."]

Well, part of the allure of this PR is that we don't have to Git for Windows-specific notes in https://git-scm.com/docs/git-config...

**Comment by dscho** [comment]
I merged this so that I can now start to rebase to Git v2.24.0, which will take quite a while because of all the builtin `add -c` fallout...

**Comment by altimumdelta** [comment]
Thanks for this. I have made edits in these files and yep this surely helps with having a clear picture and avoid conflicts. I use another msys2 installation for compiling and I was just having an issue with GIT popping up when I ran a command to configure a compilation prep file, turned out I had a bloated install with a lot of git packages in the separate msys2, but I also removed git from the PATH since it's not needed for Git Bash anyway. There's already a need to rename or delete "link.exe" in the default msys2 installation to be able to compile FFmpeg on windows with MSVC for example. These things only look small but they can cost hours and hours of troubleshooting, not to mention the nerves.

**Comment by whut** [comment]
Looks like the `rebase.autosquash=true`, that was previously in `C:\ProgramData\Git\config` was not migrated to new location. Was that a deliberate decision?

**Comment by dscho** [comment]
> Looks like the `rebase.autosquash=true`, that was previously in `C:\ProgramData\Git\config` was not migrated to new location. Was that a deliberate decision?

No, it was not a deliberate decision. To the contrary, it should still be there, see https://github.com/git-for-windows/build-extra/blob/master/git-extra/gitconfig

@whut could you open a new ticket for this, filling out all the placeholders so that I know where to chase the bug?

**Comment by dscho** [comment]
FWIW I even see this setting [in the current version of Git for Windows' SDK](https://github.com/git-for-windows/git-sdk-64/blob/8a0e2a69282470cbd506bf613cf8ba9012fcace1/etc/gitconfig#L15-L16).

**Comment by JojOatXGME** [comment]
I also noticed some months ago that `git rebase -i` did no-longer use `--autosquash` by default after updating my Git installation on Windows. I did not bother investigating the issue at first but I recently noticed that some users were “blaming” JetBrains for changing the behavior. See [IDEA-209497](https://youtrack.jetbrains.com/issue/IDEA-209497). I guess they run into the same issue.

**Pull request merged**
