### PR TITLE
Offer a built-in version of `git add -i` and `git add -p`

### PR DESCRIPTION
**Pull request by dscho**
This reduces not only our dependency on Perl even further, but it also reduces the startup time of `git add -p` substantially.

Note: this PR is currently meant primarily as a way to test this feature thoroughly, with plans to merge it when the patches have been reviewed on the Git mailing list for a bit.

### CODE REVIEW

**Comment by dscho** [comment]
Companion PRs over at GitGitGadget:
https://github.com/gitgitgadget/git/pull/170
https://github.com/gitgitgadget/git/pull/171
https://github.com/gitgitgadget/git/pull/172
https://github.com/gitgitgadget/git/pull/173
https://github.com/gitgitgadget/git/pull/174
https://github.com/gitgitgadget/git/pull/175

**Comment by lassevk** [comment]
Is there a way to enable this feature if I'm using the portable distribution of Git for Windows? A global configuration option or some such?

Or does the installer deploy different executables/scripts if you enable this feature in the installer?

Please advise.

**Comment by dscho** [comment]
Yes! The config option `add.interactive.useBuiltin` needs to be set to `true`.

**Pull request merged**
