### PR TITLE
Fix "Open in Visual Studio Code" badge in README.md

### PR DESCRIPTION
**Pull request by sunzhuoshi**
Signed-off-by: sunzhuoshi <sunzhuoshi@gmail.com>

### CODE REVIEW

**Comment by sunzhuoshi** [comment]
"Open in Visual Studio Code" badge in REAME.md broke, please check following image for details:
image
and VSCode issue for solution by Microsoft
https://github.com/microsoft/vscode/issues/128813#issuecomment-943125631

**Comment by dscho** [comment]
@sunzhuoshi Thank you for noticing and fixing the bug! The diff looks good, but I would like to ask for the following changes:
- Mark it as a `fixup!` for https://github.com/git-for-windows/git/commit/7b440c3faafed100bf08a1794b188af8d06bdaf9 so that next time I rebase, the change gets squashed into the correct commit automatically, without requiring me to remember.
- The commit message has too little information. Please follow [this guidance](https://github.blog/2022-06-30-write-better-commits-build-better-projects/) to improve it.
- I would like to ask you to use your real name in the `Signed-off-by:`.

**Comment by sunzhuoshi** [comment]
> @sunzhuoshi Thank you for noticing and fixing the bug! The diff looks good, but I would like to ask for the following changes:
> 
> * Mark it as a `fixup!` for [7b440c3](https://github.com/git-for-windows/git/commit/7b440c3faafed100bf08a1794b188af8d06bdaf9) so that next time I rebase, the change gets squashed into the correct commit automatically, without requiring me to remember.
Sure, no problem
> * The commit message has too little information. Please follow [this guidance](https://github.blog/2022-06-30-write-better-commits-build-better-projects/) to improve it.
OK
> * I would like to ask you to use your real name in the `Signed-off-by:`.
Haha, I just rolled back my name to English, for Chinese may not be supported very well in some cases. I will change it to Chinese.

**Comment by dscho** [comment]
> I didn't move my fixup commit under [7b440c3](https://github.com/git-for-windows/git/commit/7b440c3faafed100bf08a1794b188af8d06bdaf9), for there're some conflicts I don't understand yet when I rebase.

I rebased it and used the opportunity to add a commit to reword the commit message of the commit that will be fixed up.

**Pull request merged**
