### PR TITLE
Rebase to v2.47.0

### PR DESCRIPTION
**Pull request by dscho**
<details><summary>Range-diff relative to </summary>

* 5:  4d1fa2f4130e =   1:  82b47a40e17a t9350: point out that refs are not updated correctly
* 4:  f4a21be1ed9a =   2:  32c8a616e5aa gitk(Windows): avoid inadvertently calling executables in the worktree
* 6:  9c8ddeb5019a =   3:  84c0be4e6a21 transport-helper: add trailing --
* 7:  0388e0f48983 =   4:  8b51b7a7684c remote-helper: check helper status after import/export
* 8:  a2fc5f4becdb =   5:  5278695a9fc3 mingw: demonstrate a problem with certain absolute paths
* 9:  19e2851cb280 =   6:  2c843e899143 Always auto-gc after calling a fast-import transport
* 10:  591248d76c79 =   7:  4097c1dff65a mingw: allow absolute paths without drive prefix
* 11:  241c1dfcbc55 =   8:  298f318a1cb4 mingw: include the Python parts in the build
* 12:  a6c8bed98c3d =   9:  30e563a1f5c2 clean: do not traverse mount points
* 13:  dff182e19839 =  10:  0c32432bdb9d win32/pthread: avoid name clashes with winpthread
* 14:  39566c5d6476 =  11:  71b00f96bcc5 clean: remove mount points when possible
* 15:  34ba44beadf0 =  12:  e08a265bbd2f git-compat-util: avoid redeclaring _DEFAULT_SOURCE
* 16:  f603a03fb10d =  13:  8d0c8baad8f1 Import the source code of mimalloc v2.1.2
* 17:  25f63e8b667e =  14:  f5bbbbb2ec0c mimalloc: adjust for building inside Git
* 18:  f699fdae2dc9 =  15:  c70b87995fb2 mimalloc: offer a build-time option to enable it
* 19:  cac17949c120 =  16:  7134a1e511f3 mimalloc: use "weak" random seed when statically linked
* 20:  6021bfb4b890 =  17:  a7c62e6c9d08 mingw: use mimalloc
* 21:  8eeb5a09b3e0 =  18:  894ab100dd33 transport: optionally disable side-band-64k
* 22:  228a2bafaeaa =  19:  bee546e4b78d mingw: make sure `errno` is set correctly when socket operations fail
* 23:  65bfabdf9192 =  20:  9b9040f2c183 mingw: do resolve symlinks in `getcwd()`
* 25:  e78152909142 =  21:  9d6e3906e1e9 mingw: demonstrate a `git add` issue with NTFS junctions
* 28:  ae71902018fb =  22:  f9318107cf8a strbuf_realpath(): use platform-dependent API if available
* 24:  c08df1433a47 =  23:  14f188fa338b mingw: fix fatal error working on mapped network drives on Windows
* 26:  c78ac595c3a4 =  24:  9a3f6c2f5a8c clink.pl: fix MSVC compile script to handle libcurl-d.lib
* 27:  64b04e8d3c2c =  25:  2d3b95d793f0 mingw: ensure valid CTYPE
* 29:  40e207d8772d =  26:  a25428ab2fe8 mingw: allow `git.exe` to be used instead of the "Git wrapper"
* 32:  2e0c2aba89a6 =  27:  8bf47b107385 mingw: ignore HOMEDRIVE/HOMEPATH if it points to Windows' system directory
* 33:  cfcc09909ef5 =  28:  20ed4ceb2b93 http: use new "best effort" strategy for Secure Channel revoke checking
* 30:  b680f09a453a =  29:  29b8d1ec1b01 mingw: implement a platform-specific `strbuf_realpath()`
* 31:  1b42afc27ee5 =  30:  e46b3fef4bd4 vcxproj: unclash project directories with build outputs
* 34:  f1f23e45b7db =  31:  e58a01ed06a0 t5505/t5516: allow running without `.git/branches/` in the templates
* 35:  dd2a52565b6e =  32:  7ef36fb0ee46 t5505/t5516: fix white-space around redirectors
* 36:  72487ea853be =  33:  3dbe3b6b8e11 t3701: verify that we can add *lots* of files interactively
* 37:  6288c4db79f7 =  34:  4096d9642712 git add -i: handle CR/LF line endings in the interactive input
* 38:  4958dbf9ecdc =  35:  ec6ab10449f4 commit: accept "scissors" with CR/LF line endings
* 39:  abfefcfea750 =  36:  0297fd3c36b4 t0014: fix indentation
* 40:  64d500c9e1a8 =  37:  eca2cf5258de git-gui: accommodate for intent-to-add files
* 41:  526a67e27c29 =  38:  d19278dabc1e clink.pl: fix libexpatd.lib link error when using MSVC
* 42:  980c640d4ee2 =  39:  a1cdb002aa0f Makefile: clean up .ilk files when MSVC=1
* 43:  b3909cb24f9c =  40:  b0782daa491e vcbuild: add support for compiling Windows resource files
* 44:  991b6bc03c4b =  41:  bfc8ec08cdcf config.mak.uname: add git.rc to MSVC builds
* 45:  dd1e6782eabd =  42:  7571c7c0f3d0 clink.pl: ignore no-stack-protector arg on MSVC=1 builds
* 46:  048c378a22cc =  43:  acd8bcd667bf clink.pl: move default linker options for MSVC=1 builds
* 47:  af990b72be5c =  44:  530cbc44f45d buildsystems: remove duplicate clause
* 48:  c11788b63bc1 =  45:  75f49662afce vcxproj: handle resource files, too
* 49:  d9a9273a3648 =  46:  314c8cdbd33c vcxproj: ignore -fno-stack-protector and -fno-common
* 50:  76ca105db8d1 =  47:  4ced2abfb7e5 vcxproj: handle GUI programs, too
* 51:  e24174df893a =  48:  eb6bbeb280db vcpkg_install: detect lack of Git
* 52:  c848dd0ae469 =  49:  b8faef9782fb vcpkg_install: add comment regarding slow network connections
* 53:  673ea43e5a4e =  50:  f4aea0b29985 vcxproj: support building Windows/ARM64 binaries
* 55:  e581b8fc91bb =  51:  321c096826a4 cmake: install headless-git.
* 54:  d7299cb9ca05 =  52:  d2e44fdbfac1 vcbuild: install ARM64 dependencies when building ARM64 binaries
* 56:  a35125a9194e =  53:  984b17725d54 vcbuild: add an option to install individual 'features'
* 57:  a048ca2ea6bf =  54:  d848405f360e cmake: allow building for Windows/ARM64
* 58:  e3e5c93f9039 =  55:  8efc69420ffa ci(vs-build) also build Windows/ARM64 artifacts
* 59:  4ee690347430 =  56:  54bbcfe54c5f Add schannel to curl installation
* 60:  33191e93961a =  57:  cbaedbee1b21 cmake(): allow setting HOST_CPU for cross-compilation
* 62:  17271def4267 =  58:  d1078e13c96a subtree: update `contrib/subtree` `test` target
* 61:  589c2ed7cd7c =  59:  d96e86fc13cc mingw: allow for longer paths in `parse_interpreter()`
* 63:  1d39b88873b5 =  60:  fd88e77c4afc compat/vcbuild: document preferred way to build in Visual Studio
* 64:  f3a8521d44e1 =  61:  ef787ec6b6d3 http: optionally send SSL client certificate
* 66:  3821d7480a4a =  62:  72c0388cd2b8 CMake: default Visual Studio generator has changed
* 67:  6c8207ba1b47 =  63:  dbeace96559c .gitignore: add Visual Studio CMakeSetting.json file
* 68:  f3bd85151772 =  64:  dc7b364ae5af CMakeLists: add default "x64-windows" arch for Visual Studio
* 65:  bd5a61ac2f72 =  65:  3a5a85d7f804 ci: run `contrib/subtree` tests in CI builds
* 69:  134d2adc0b93 =  66:  8f9ee9af0451 CMake: show Win32 and Generator_platform build-option values
* 71:  a559944d9f1e =  67:  89a13aad78d3 hash-object: demonstrate a >4GB/LLP64 problem
* 72:  7d65d1357936 =  68:  d21a631ff2cd write_object_file_literally(): use size_t
* 73:  22c171e1e40e =  69:  fc342ff8564f object-file.c: use size_t for header lengths
* 74:  18a1d9e8ad28 =  70:  af5980d9d48c hash algorithms: use size_t for section lengths
* 75:  010e219757f3 =  71:  a3aa580ba1e6 hash-object --stdin: verify that it works with >4GB/LLP64
* 70:  45da5f1c668a =  72:  2e16f8d20e8c init: do parse _all_ core.* settings early
* 76:  5fd555606424 =  73:  75551ae45440 hash-object: add another >4GB/LLP64 test case
* 77:  eae89665706f =  74:  3011d308f143 setup: properly use "%(prefix)/" when in WSL
* 78:  5c00a2341faa =  75:  7f3f3e498725 hash-object: add a >4GB/LLP64 test case using filtered input
* 79:  64dc42ce8e29 =  76:  2f29de61cac6 compat/mingw.c: do not warn when failing to get owner
* 81:  fe66c70f4789 =  77:  1e34e83b0068 mingw: $env:TERM="xterm-256color" for newer OSes
* 80:  748639684da0 =  78:  fcd3b4e6f106 Add config option `windows.appendAtomically`
* 84:  72a3cfde6857 =  79:  4bb392dd9c38 vcxproj: allow building with `NO_PERL` again
* 82:  278e73713eec =  80:  17fd211a84a4 winansi: check result and Buffer before using Name
* 83:  cbd02d41d0ff =  81:  1a361887722e mingw: change core.fsyncObjectFiles = 1 by default
* 85:  c7f6953a29e4 =  82:  ae9705d96642 vcxproj: require C11
* 86:  e68175701097 =  83:  5c2f375fdbd6 vcxproj: ignore the `-pedantic` option
* 87:  69460875d000 =  84:  31233e3c04c1 vcxproj: include reftable when committing `.vcxproj` files
* 88:  caceb1529eb1 =  85:  956a0d4a1ae0 vcxproj: handle libreftable_test, too
* 89:  42435818a26d =  86:  4eb3bfcd495c vcxproj: avoid escaping double quotes in the defines
* 90:  6c18069a427c =  87:  af6fc9aee569 ci: adjust Azure Pipeline for `runs_on_pool`
* 91:  e095e4cbf067 =  88:  81c2b63366d3 ci: stop linking the `prove` cache
* 92:  a981ae8ef0e6 =  89:  63dd7274be6b ci: reinstate Azure Pipelines support
* 93:  727d2686c940 =  90:  8c8d3ee6a75b azure-pipeline: drop the `GETTEXT_POISON` job
* 94:  ecc368ba6134 =  91:  082f7b66d902 azure-pipeline: stop hard-coding `apt-get` calls
* 95:  ea10516e23ef =  92:  915aa048df86 azure-pipeline: drop the code to write to/read from a file share
* 96:  190832c1836d =  93:  fe5de3e17dc7 azure-pipeline: use partial clone/parallel checkout to initialize minimal-sdk
* 97:  7d81f0b56b49 =  94:  4572d4da6ceb azure-pipeline: downcase the job name of the `Linux32` job
* 98:  28d78a2cfe5d =  95:  83cceede95b2 azure-pipeline: run static-analysis on jammy
* 99:  c9f66c4b5352 =  96:  fe9ded9cda36 bswap.h: add support for built-in bswap functions
* 100:  6c1b6051567c =  97:  9dff4e757957 config.mak.uname: add support for clangarm64
* 101:  86c3000e5275 =  98:  94f1f27f7971 MinGW: link as terminal server aware
* 102:  a36a76ccc80b =  99:  9685fb643670 Fix Windows version resources
* 103:  a99ced1eec37 = 100:  cafdce8178e4 ci: create clangarm64-build.yml
* 104:  da2c993a59a3 = 101:  3957cee3e62a status: fix for old-style submodules with commondir
* 108:  b81567e0b6f1 = 102:  fd5e65def957 windows: skip linking `git-<command>` for built-ins
* 109:  3106f5fffc13 = 103:  74807d1bd99d windows: fix Repository>Explore Working Copy
* 105:  630c9ff526d8 = 104:  98f21f5cd5b3 http: optionally load libcurl lazily
* 106:  f0ba8a260060 = 105:  eec957ee7067 http: support lazy-loading libcurl also on Windows
* 107:  1cc64e9d5fc7 = 106:  9d0e62237745 http: when loading libcurl lazily, allow for multiple SSL backends
* 110:  09bef5a82ebc = 107:  2718450690cb mingw: do load libcurl dynamically by default
* 111:  93c275dcb940 = 108:  1047e1b28a56 Add a GitHub workflow to verify that Git/Scalar work in Nano Server
* 112:  5ac3aeb95be8 = 109:  94f552233565 mingw: suggest `windows.appendAtomically` in more cases
* 113:  11c77e4fe65a = 110:  56ea536e8879 win32: use native ANSI sequence processing, if possible
* 114:  1687e53df205 = 111:  b478fc7ed969 git.rc: include winuser.h
* 115:  a53393715f4d = 112:  a92f41b3288d common-main.c: fflush stdout buffer upon exit
* 116:  b01d5cbf43e3 = 113:  7179e42d8b4c t5601/t7406(mingw): do run tests with symlink support
* 119:  ddf961b5bf82 = 114:  8202b2403dbc win32: ensure that `localtime_r()` is declared even in i686 builds
* 120:  aaf6d53a5792 = 115:  d2ebe058270c Fallback to AppData if XDG_CONFIG_HOME is unset
* 117:  26ba963f7daf = 116:  776b930b8da3 ci: work around a problem with HTTP/2 vs libcurl v8.10.0
* 118:  6ed5f629fdb9 = 117:  31382dcda793 pack-objects: add --full-name-hash option
* 122:  5cc3464a360e = 118:  e9fe71fb442e repack: test --full-name-hash option
* 123:  221be0ea675d = 119:  2bd50fb13d20 pack-objects: add GIT_TEST_FULL_NAME_HASH
* 121:  744273059d17 = 120:  f398f64cf6ef run-command: be helpful with Git LFS fails on Windows 7
* 124:  78dbc402052b = 121:  d3c08260882b git-repack: update usage to match docs
* 125:  4a37ccb7353a = 122:  871f9368410c p5313: add size comparison test
* 126:  18686eb04a36 = 123:  97829b5bddca test-tool: add helper for name-hash values
* 127:  82bb044f88d4 = 124:  5c8182bb7dba repack/pack-objects: mark `--full-name-hash` as experimental
* 128:  41e90b42f170 = 125:  685d13082878 path-walk: introduce an object walk by path
* 129:  65b5595a4880 = 126:  f10a957a3162 t6601: add helper for testing path-walk API
* 130:  6fedcc49c91c = 127:  118b06dc4e81 path-walk: allow consumer to specify object types
* 131:  e6acd743c75a = 128:  731998ced29c path-walk: allow visiting tags
* 132:  8e5e612e70b8 = 129:  9e7da314ed5d revision: create mark_trees_uninteresting_dense()
* 133:  d0f2213752d7 = 130:  ec1a5d43589f path-walk: add prune_all_uninteresting option
* 134:  ce40df44d4d7 = 131:  4578489d1af3 pack-objects: extract should_attempt_deltas()
* 135:  8e8a5b87d4c3 = 132:  454cfdddd8c6 pack-objects: add --path-walk option
* 136:  13ff91f66508 = 133:  82abe4003409 pack-objects: introduce GIT_TEST_PACK_PATH_WALK
* 137:  a9bc29e91e8f = 134:  f07075e2d76f repack: add --path-walk option
* 138:  5b38114dc67b = 135:  bf51d093d4ec pack-objects: enable --path-walk via config
* 139:  c7bd1dfe9834 = 136:  2d533c9ede9c scalar: enable path-walk during push via config
* 140:  2488d13c1e9d = 137:  2f07cd7ec70c pack-objects: refactor path-walk delta phase
* 141:  4f530f726345 = 138:  cd6e3a6b2f19 pack-objects: thread the path-based compression
* 275:  930a3aaa917a = 139:  8b02eeb9ddf5 path-walk API: avoid adding a root tree more than once
* 142:  1dedc040f0b6 = 140:  a288333be69b backfill: add builtin boilerplate
* 143:  2fae6ee07cf4 = 141:  e61870bea912 backfill: basic functionality and tests
* 144:  439210584bc9 = 142:  c7df6b470d15 backfill: add --batch-size=<n> option
* 145:  120e50cb9a8e = 143:  938bdf9d9f35 backfill: add --sparse option
* 146:  bff91f1d5ea5 = 144:  b8cebf0a8156 backfill: assume --sparse when sparse-checkout is enabled
* 147:  192f63ed1bdc = 145:  51b8ae8648f0 backfill: mark it as experimental
* 148:  714beddd72a8 = 146:  6d2fb8b326e0 survey: stub in new experimental 'git-survey' command
* 149:  5bac1adb95a9 = 147:  4e61f93688b6 survey: add command line opts to select references
* 150:  8f9e2201cfd9 = 148:  3c9a3ddf17e2 survey: start pretty printing data in table form
* 151:  f2f89bc4ae51 = 149:  dc4a5f7721c8 survey: add object count summary
* 152:  f39486ae23c5 = 150:  61f5ff51d1de survey: summarize total sizes by object type
* 153:  6a43d0737bee = 151:  0714eced57f6 survey: show progress during object walk
* 154:  34983c13e0fb = 152:  76ae6b5c0973 survey: add ability to track prioritized lists
* 155:  54844019731e = 153:  1eef810a4e38 survey: add report of "largest" paths
* 156:  7e30b29b060d = 154:  910d8657aca0 survey: add --top=<N> option and config
* 1:  05c21616c350 = 155:  1b6847f1595a line-log: protect inner strbuf from free
* 157:  2be2c924d155 = 156:  a5639450b3e9 survey: clearly note the experimental nature in the output
* 2:  94d2c034b4a8 = 157:  eff0ca076e87 line-log: remove output_prefix()
* 3:  e1d825ad212d = 158:  db93c6657b0c diff: modify output_prefix function pointer
* 158:  ca2829aa5bea = 159:  2e6b87127859 Win32: make FILETIME conversion functions public
* 159:  efd075347858 = 160:  dcfad57a92ad Win32: dirent.c: Move opendir down
* 160:  2c4e75743430 = 161:  007757525272 mingw: make the dirent implementation pluggable
* 161:  6070b5d7f695 = 162:  95bccd8e94f6 Win32: make the lstat implementation pluggable
* 162:  e4b7d0feb0a3 = 163:  98e220af719a mingw: add infrastructure for read-only file system level caches
* 163:  273b65dbe7be = 164:  028efdac1811 mingw: add a cache below mingw's lstat and dirent implementations
* 164:  4fc7b9e6b9e7 = 165:  d4f044493092 fscache: load directories only once
* 165:  0fc3a7647c51 = 166:  e45f8adca749 fscache: add key for GIT_TRACE_FSCACHE
* 166:  028fac72e728 = 167:  d00800e01e24 fscache: remember not-found directories
* 167:  db1aa34a4447 = 168:  ade3ba78df44 fscache: add a test for the dir-not-found optimization
* 168:  98882127cf54 = 169:  53de33f7a609 add: use preload-index and fscache for performance
* 169:  08455cf809fe = 170:  fda16c8e894d dir.c: make add_excludes aware of fscache during status
* 170:  c30c7af69414 = 171:  3826f0d9f6f7 fscache: make fscache_enabled() public
* 171:  5b0f5ab73418 = 172:  eeead2413dae dir.c: regression fix for add_excludes with fscache
* 172:  ca14fa263b77 = 173:  7973ab27e2a6 fetch-pack.c: enable fscache for stats under .git/objects
* 173:  2e5a053bda61 = 174:  bb923bbbf33e checkout.c: enable fscache for checkout again
* 174:  95dd5f5c22d8 = 175:  6f5ebad634d4 Enable the filesystem cache (fscache) in refresh_index().
* 175:  ae01e29883f7 = 176:  5517a9f819df fscache: use FindFirstFileExW to avoid retrieving the short name
* 176:  e6aace3b3ce5 = 177:  2a5d448eeb23 status: disable and free fscache at the end of the status command
* 177:  d8b277104a85 = 178:  e9311859a777 fscache: add GIT_TEST_FSCACHE support
* 178:  d7c89b0758f1 = 179:  94dd82410404 fscache: add fscache hit statistics
* 179:  b6d63b679bfa = 180:  3257dfe0933e mem_pool: add GIT_TRACE_MEMPOOL support
* 180:  ff03c407cb19 = 181:  9e1e2280a47f fscache: fscache takes an initial size
* 181:  bbfecad84a56 = 182:  daf7e83e06e1 fscache: update fscache to be thread specific instead of global
* 182:  a49d409ba409 = 183:  b8f8cdc57049 fscache: teach fscache to use mempool
* 183:  936a14871bcf = 184:  f34dae82b9f3 fscache: make fscache_enable() thread safe
* 184:  af2cbc4060a9 = 185:  6330375b6e6c fscache: teach fscache to use NtQueryDirectoryFile
* 185:  0bc448d55897 = 186:  36295910e0cb unpack-trees: enable fscache for sparse-checkout
* 186:  e9b3856c10e5 = 187:  8cf3d4081f8a fscache: remember the reparse tag for each entry
* 187:  ed01d91287d8 = 188:  8b3764197935 git-gui: provide question helper for retry fallback on Windows
* 188:  fad0d53294d3 = 189:  d5c7454062c4 fscache: implement an FSCache-aware is_mount_point()
* 189:  23e7a19fe639 = 190:  3158c66138e4 git gui: set GIT_ASKPASS=git-gui--askpass if not set yet
* 190:  634d2fd5f642 = 191:  75ce3291c81e clean: make use of FSCache
* 191:  77d9198755ee = 192:  76d79d95e25e gitk: Unicode file name support
* 192:  eff723f1ac1e = 193:  4ab6eca376aa git-gui--askyesno: fix funny text wrapping
* 193:  574b79385a21 = 194:  0c82cc9d076f gitk: Use an external icon file on Windows
* 194:  f915c8061e22 = 195:  dde11f482f1f git-gui--askyesno: allow overriding the window title
* 195:  60ab5b701039 = 196:  28d40b9d9a3b gitk: fix arrow keys in input fields with Tcl/Tk >= 8.6
* 196:  60e7d4abacba = 197:  e6058c8f74dd git-gui--askyesno (mingw): use Git for Windows' icon, if available
* 197:  a7d2c230a198 = 198:  24be74acf55f gitk: make the "list references" default window width wider
* 198:  90dd9dffea43 = 199:  bf28c7f9a871 pack-objects (mingw): demonstrate a segmentation fault with large deltas
* 199:  55212525fa56 = 200:  0b30bc08fc6a mingw: support long paths
* 200:  be9ac1920fbb = 201:  0a9dc09a4566 Win32: fix 'lstat("dir/")' with long paths
* 201:  edd7b9e3c7da = 202:  5ff1ebe4645d win32(long path support): leave drive-less absolute paths intact
* 206:  a345fc3c5485 = 203:  e4527a86cefd compat/fsmonitor/fsm-*-win32: support long paths
* 202:  4fa5d93622af = 204:  67337c8977ae mingw: Support `git_terminal_prompt` with more terminals
* 203:  5242dd59b9c1 = 205:  b5dc26ae5e5d compat/terminal.c: only use the Windows console if bash 'read -r' fails
* 204:  23da43433efe = 206:  1f391ddab357 mingw (git_terminal_prompt): do fall back to CONIN$/CONOUT$ method
* 205:  74b72b7926a9 = 207:  2c87e7ba335c strbuf_readlink: don't call readlink twice if hint is the exact link size
* 207:  a13b10707453 = 208:  a36b695e680f clean: suggest using `core.longPaths` if paths are too long to remove
* 208:  4b961fbdcdeb = 209:  5bea09f841b2 strbuf_readlink: support link targets that exceed PATH_MAX
* 209:  0796d9267fd3 = 210:  512490f5f22e lockfile.c: use is_dir_sep() instead of hardcoded '/' checks
* 210:  2a3f2e7c9b76 = 211:  bd1d08815800 Win32: don't call GetFileAttributes twice in mingw_lstat()
* 211:  72bb1c8265d6 = 212:  6d219671713b Win32: implement stat() with symlink support
* 212:  3ddbf363b3b8 = 213:  a32c452c7d22 Win32: remove separate do_lstat() function
* 213:  1bc157315a88 = 214:  04ac44d3d170 Win32: let mingw_lstat() error early upon problems with reparse points
* 214:  077ca3d51858 = 215:  797b60f6528e mingw: teach fscache and dirent about symlinks
* 215:  71d423766103 = 216:  147a64834363 Win32: lstat(): return adequate stat.st_size for symlinks
* 216:  59e73e66c46c = 217:  3d9ebe39f86f Win32: factor out retry logic
* 217:  a88262b138da = 218:  65c4e233f4a8 Win32: change default of 'core.symlinks' to false
* 218:  73aa817a2e31 = 219:  d8c08931327d Win32: add symlink-specific error codes
* 219:  bcd17e6e26d4 = 220:  3a56953bd2c8 Win32: mingw_unlink: support symlinks to directories
* 220:  a6b60599ec26 = 221:  d27bed2b17fe Win32: mingw_rename: support renaming symlinks
* 221:  cfe1b4f2c789 = 222:  f99b8576667e Win32: mingw_chdir: change to symlink-resolved directory
* 222:  7218afe95eb9 = 223:  86420a1b84d1 Win32: implement readlink()
* 223:  6f3d99bd8929 = 224:  dc59fced73bf mingw: lstat: compute correct size for symlinks
* 224:  a6bfbd05fd9b = 225:  a7ad2f4045ff Win32: implement basic symlink() functionality (file symlinks only)
* 225:  26495c74d7bd = 226:  73e5a1e0a437 Win32: symlink: add support for symlinks to directories
* 226:  40bd44a94bd9 = 227:  248e7b445218 mingw: try to create symlinks without elevated permissions
* 227:  0323d4da299c = 228:  ebe873025dab mingw: emulate stat() a little more faithfully
* 228:  409d8351d519 = 229:  132c94f3c466 mingw: special-case index entries for symlinks with buggy size
* 229:  182e5198b88d = 230:  4d79b76c1428 mingw: introduce code to detect whether we're inside a Windows container
* 230:  4bf94db0ed4e = 231:  f3ef296d66c9 mingw: when running in a Windows container, try to rename() harder
* 231:  74cf36c15ccd = 232:  7d1cc976a4ad mingw: move the file_attr_to_st_mode() function definition
* 232:  179084cacd27 = 233:  53cb5c1bd7cd mingw: Windows Docker volumes are *not* symbolic links
* 233:  f08767626be6 = 234:  ec29d2bba643 Win32: symlink: move phantom symlink creation to a separate function
* 234:  1263235c59e2 = 235:  c088807dcc78 Introduce helper to create symlinks that knows about index_state
* 235:  a96c675d4b81 = 236:  5a3049711bbd mingw: allow to specify the symlink type in .gitattributes
* 236:  b4744d85a6b0 = 237:  a9ed70cca352 Win32: symlink: add test for `symlink` attribute
* 241:  2cbb28f7880a = 238:  fc965724b622 mingw: work around rename() failing on a read-only file
* 237:  08dde17f3247 = 239:  236b7b7799bc mingw: explicitly specify with which cmd to prefix the cmdline
* 238:  3c30fa9ce5b0 = 240:  9fd2e840588c mingw: when path_lookup() failed, try BusyBox
* 239:  ddcc426cebe6 = 241:  cf2a4790e38f test-lib: avoid unnecessary Perl invocation
* 240:  60bbecf97776 = 242:  00139f90c06a test-tool: learn to act as a drop-in replacement for `iconv`
* 242:  e36a6beed736 = 243:  77746240864c tests(mingw): if `iconv` is unavailable, use `test-helper --iconv`
* 243:  56d40cad7e20 = 244:  023f17b6acb2 gitattributes: mark .png files as binary
* 244:  6788827cdf5f = 245:  9ab6b6b9fcce tests: move test PNGs into t/lib-diff/
* 245:  80dd4518447f = 246:  95f6db956d6a tests: only override sort & find if there are usable ones in /usr/bin/
* 246:  61b13d67914b = 247:  1aab1ad99798 tests: use the correct path separator with BusyBox
* 247:  d60e55389bc0 = 248:  e03367673537 mingw: only use Bash-ism `builtin pwd -W` when available
* 248:  d899318263e2 = 249:  8e3b66b059ad tests (mingw): remove Bash-specific pwd option
* 249:  13908df1e959 = 250:  7ae8372291dc test-lib: add BUSYBOX prerequisite
* 250:  b0ff24d3914d = 251:  bb1b278e6ad0 t5003: use binary file from t/lib-diff/
* 251:  15dfc0cbdc3c = 252:  ffe950360dec t5532: workaround for BusyBox on Windows
* 252:  5a9274c2cf6a = 253:  dbb27bdf7e48 t5605: special-case hardlink test for BusyBox-w32
* 253:  eeaff0e20062 = 254:  5b36798a9ba2 t5813: allow for $PWD to be a Windows path
* 254:  7779b95342f3 = 255:  918f4abcac9e t9200: skip tests when $PWD contains a colon
* 255:  a7bab719324c = 256:  b99fde492d08 mingw: add a Makefile target to copy test artifacts
* 256:  15ae0077003b = 257:  0f35e7723c37 mingw: optionally enable wsl compability file mode bits
* 257:  6e70a32d84a7 = 258:  10bb07fc8b00 mingw: kill child processes in a gentler way
* 258:  24c2e4bca761 = 259:  63cc420ed73e mingw: do not call xutftowcs_path in mingw_mktemp
* 259:  9bad1656e1ad = 260:  26539c495665 mingw: really handle SIGINT
* 260:  a5cd03b7f797 = 261:  8b8b1235b306 Partially un-revert "editor: save and reset terminal after calling EDITOR"
* 261:  d2f963ee17bb = 262:  2ce548c532fc Add a GitHub workflow to monitor component updates
* 263:  4f0462d7da02 = 263:  c3e1525e399c reset: reinstate support for the deprecated --stdin option
* 264:  3f88490de32f = 264:  b4fb482dfdba fsmonitor: reintroduce core.useBuiltinFSMonitor
* 265:  866b1c5ba199 = 265:  7a06b7bbb279 dependabot: help keeping GitHub Actions versions up to date
* 262:  1b3e31660fef = 266:  2ce307af6095 Describe Git for Windows' architecture [no ci]
* 266:  d4b1f97db51b = 267:  26bccbee75c8 Modify the Code of Conduct for Git for Windows
* 267:  d634b06215eb = 268:  141b8aba6265 CONTRIBUTING.md: add guide for first-time contributors
* 268:  c4881c1bc3da = 269:  b134efe5f62b README.md: Add a Windows-specific preamble
* 269:  8614edba38f8 = 270:  fa6fc63219de Add an issue template
* 270:  7ff9f4dbe881 = 271:  0ce6de6a858e Modify the GitHub Pull Request template (to reflect Git for Windows)
* 271:  dd05d1c7ff2a = 272:  e587604a5359 .github: Add configuration for the Sentiment Bot
* 272:  f346b35114bf = 273:  2ff87a4ed524 Document how $HOME is set on Windows
* 273:  4bccebaf5423 = 274:  9468391cdddc SECURITY.md: document Git for Windows' policies
* 274:  49e30693fac4 (upstream: 7355574a226e15a06c07fdcf1c401cf043298e4b) <   -:  ------------ t0610: skip concurrent write test case on Windows

</details>

Nothing stands out, except maybe that the numbers reflect that I moved a couple of patches into the `ready-for-upstream` thicket.

### CODE REVIEW

**Comment by dscho** [comment]
I briefly considered backporting gitgitgadget/git#1812 because the link _is_ broken: `start /mingw64/share/doc/git-doc/technical/platform-support.html` _will_ open file:///C:/Program Files/Git/mingw64/share/doc/git-doc/technical/platform-support.html, and the ["How to maintain Git"](file:///C:/Program Files/Git/mingw64/share/doc/git-doc/howto/maintain-git.txt) link incorrectly specifies a `.txt` file (which does not exist) when it should specify a `.html` (which does).

But I decided against backporting given that there is no easy `git help` invocation to open [the `technical/platform-support` page](https://git-scm.com/docs/platform-support), indeed, the only other page containing the string "platform-support" would be the `technical/unit-tests` one, and it is merely an anchor there, not a link, and besides, `technical/unit-tests` is not linked from any other page at all, so there.

**Comment by Unknown0423** [comment]
``--config-env=<name>=<envvar>]

**Pull request merged**
