### PR TITLE
Add a brief "code of conduct" section to the Governance Model

### PR DESCRIPTION
**Pull request by dscho**
It is better to state clearly expectations and intentions than to assume quietly that everybody agrees.

So let's add a concise section to the governance model, maybe modeled after http://software-carpentry.org/conduct.html.

### CODE REVIEW

**Comment by dscho** [comment]
Thanks! To make it easier to discuss, I turned this issue into a Pull Request.

**Comment by mhagger** [comment]
I'm not involved enough in this community to have earned a vote. But the code of conduct you linked to seems fine, assuming you really plan to go to the effort of setting up a response team like it describes.

**Comment by PhilipOakley** [comment]
I liked it. It has a nice neutral, rather than preaching, tone setting out clear aspirations. 

Michael's point about a response team would need addressing as it suggests a large team is available, and the "will contact you personally" is perhaps open to misinterpretation.

also (a petty) s/Git%20for%20Windows/Git-for-Windows/

**Comment by dscho** [comment]
Okay, I just adjusted it to reflect the fact that there is no "response team". Here is the interdiff:

```diff
diff --git a/CONTRIBUTING.md b/CONTRIBUTING.md
index c62628d..df1eee4 100644
--- a/CONTRIBUTING.md
+++ b/CONTRIBUTING.md
@@ -28,14 +28,13 @@ characteristics above, including participants with disabilities.
 
 ### Reporting Issues
 
-If you experience or witness unacceptable behavior—or have any other concerns—please report it by contacting us via **git-for-windows@googlegroups.com**. All reports will be handled with discretion. In your report please include:
+If you experience or witness unacceptable behavior—or have any other concerns—please report it by contacting us via **johannes.schindelin@gmx.de**. All reports will be handled with discretion. In your report please include:
 
 - Your contact information.
-- Names (real, nicknames, or pseudonyms) of any individuals involved. If there are additional witnesses, please
-include them as well. Your account of what occurred, and if you believe the incident is ongoing. If there is a publicly available record (e.g. a mailing list archive or a public IRC logger), please include a link.
+- Names (real, nicknames, or pseudonyms) of any individuals involved. If there are additional witnesses, please include them as well. Your account of what occurred, and if you believe the incident is ongoing. If there is a publicly available record (e.g. a mailing list archive or a public IRC logger), please include a link.
 - Any additional information that may be helpful.
 
-After filing a report, a representative will contact you personally. If the person who is harassing you is part of the response team, they will recuse themselves from handling your incident. A representative will then review the incident, follow up with any additional questions, and make a decision as to how to respond. We will respect confidentiality requests for the purpose of protecting victims of abuse.
+After filing a report, the Git for Windows maintainer will contact you personally. If this happens to be the person who is harassing you, they will recuse themselves from handling your incident and ask another trusted Git for Windows contributor to handle it instead, follow up with any additional questions, and make a decision as to how to respond. We will respect confidentiality requests for the purpose of protecting victims of abuse.
 
 Anyone asked to stop unacceptable behavior is expected to comply immediately. If an individual engages in unacceptable behavior, the representative may take any action they deem appropriate, up to and including a permanent ban from our community without warning.
 
```

**Comment by PhilipOakley** [comment]
Was the middle change (introduce a linefeed) deliberate, or was something else intended.

Could the first change be improved by indicating that the email address is that of the maintainer, e.g. "contacting the maintainer via **johannes.schindelin@gmx.de**."? (i.e. bring forward the mention of the maintainer to here).

Looks good [https://github.com/dscho/git/blob/code-of-conduct/CONTRIBUTING.md].

**Comment by dscho** [comment]
> Was the middle change (introduce a linefeed) deliberate, or was something else intended.

The linefeed was actually removed (because it was unintended in the first place).

> Could the first change be improved by indicating that the email address is that of the maintainer, e.g. "contacting the maintainer via johannes.schindelin@gmx.de."? (i.e. bring forward the mention of the maintainer to here).

Changed.

The interdiff is:

```diff
diff --git a/CONTRIBUTING.md b/CONTRIBUTING.md
index df1eee4..af4c7fb 100644
--- a/CONTRIBUTING.md
+++ b/CONTRIBUTING.md
@@ -28,7 +28,7 @@ characteristics above, including participants with disabilities.
 
 ### Reporting Issues
 
-If you experience or witness unacceptable behavior—or have any other concerns—please report it by contacting us via **johannes.schindelin@gmx.de**. All reports will be handled with discretion. In your report please include:
+If you experience or witness unacceptable behavior—or have any other concerns—please report it by contacting Git for Windows' maintainer via **johannes.schindelin@gmx.de**. All reports will be handled with discretion. In your report please include:
 
 - Your contact information.
 - Names (real, nicknames, or pseudonyms) of any individuals involved. If there are additional witnesses, please include them as well. Your account of what occurred, and if you believe the incident is ongoing. If there is a publicly available record (e.g. a mailing list archive or a public IRC logger), please include a link.
```

**Comment by rcdailey** [comment]
I never understood why these codes of conduct have to exist. They seem like silly forced guidelines authored by people that have nothing actually useful to contribute. And also if women want to contribute, by all means they always could. Why do we need to basically force them to contribute by over talking the issue? Talking about the importance of women in software development isn't going to suddenly make them decide to come help and deliver patches.

**Comment by PhilipOakley** [comment]
The sentiment about the need for the C-of-C is something that in some ways is an issue, it's also a reflection on the wider social issues and the development of our civil society. These C-of-C's hopefully help address the *institutionalised* nature of some of the biases and tendencies we humans commonly have. 

In the UK there was a report about 'Institutional Racism' in the London Metropolitan police force, where no individual was personally aggressively racist, but as a whole the combined actions of many small choices made the overall *system* biased, and demonstrably so. 

The point of the C-of-C is to assist in the highlighting and removal of ungrounded biases. 

I'd agree that 'equality' (which underlies the C-of-C) is a tricky social term with a contrary meaning for the technically minded. It's like comparing 4 and 7, and making the decision on greatness based on even numbers being somehow better than odd numbers (which would make 4 greater than 7). It's about making the discrimination/decision based on a true assessment of the relevant facts, rather than some stand in false parameter.

**Comment by dscho** [comment]
> I never understood why these codes of conduct have to exist. They seem like silly forced guidelines authored by people that have nothing actually useful to contribute.

The point is that they are not forced: I *want* it. Nobody forces me to adhere to any code of conduct, but I *choose* to publicize the rules by which I intend to conduct this project.

> And also if women want to contribute, by all means they always could.

Sorry, I find this attitude not welcoming. "If you want to visit me, you know where I live" is not something I would like any of my friends to tell me. Something like "I'd love you to visit me soon!" is more the message I want to convey. It is not so much the *what*, it is more the *how* we say it. It matters.

By the way I *want* encourage diversity out of purely selfish reasons: a diverse, empathy-rich environment is exactly what I like, therefore I want to do everything I can to make this project such a diverse environment.

And one of the things I do to that end is to work on this Pull Request.

**Comment by dscho** [comment]
> The point of the C-of-C is to assist in the highlighting and removal of ungrounded biases.

I could not agree more.

Nobody thinks of themselves biased, nobody thinks that they treat equally competent male and female, or equally competent Caucasian and African-American, differently. Yet there is a growing mountain of evidence that we *all* fall prey to it. And the only way to counter it is to define the rules by which we want to judge (and be judged) whether we fail to overcome those biases.

And yes, that also entails that we display more empathy and go out of our way to invite people of different sex, of different race, of different background.

**Comment by dscho** [comment]
Okay, I think this PR has exhausted the discussion ;-) Will merge it in a moment. Thanks, all!

**Pull request merged**
