### PR TITLE
[DO NOT MERGE YET] builtin rebase and stash

### PR DESCRIPTION
**Pull request by dscho**
The Google Summer of Code 2018 was particularly useful for Windows users: all three accepted students worked on converting slow Unix shell scripts to fast Git builtins. Specifically:

- `git stash`
- `git rebase`
- `git rebase -i`

The latter looks as if it should be part of `git rebase`, but that is not the case: `rebase` is such a complex command that it consisted of 5 separate shell scripts. This PR also takes care of the default `git rebase` backend, which I converted this afternoon, for fun.

NOTE: it might be too risky to go "full in" with the builtins, as the patches are still being reviewed/developed, and have not seen a whole lot of real-world usage. We can help with that real-world usage in Git for Windows, but it may be a tall order to force potentially buggy software onto end users, so I am considering the following additional patches:

- we still have that `rebase.useBuiltin` config variable, which defaults to `true` in this PR, but the Git for Windows installer could override that and default to `false`, just like we did it with the builtin `difftool`
- we could easily introduce a `stash.useBuiltin` config variable, and re-introduce the shell-scripted version as `git-legacy-stash.sh`, and also let the Git for Windows default to `false` here, and
- we should then re-introduce the `rebase -i` backend (under a slightly different name) and call it from the `git-legacy-rebase.sh` (which is only called if `rebase.useBuiltin` is set to `false`).

Note also: I used the current branches as per the Git maintainer's current state, but I know that a couple of updates are still planned, so I will have to incorporate them accordingly.

### CODE REVIEW

**Comment by tgummerer** [comment]
> we could easily introduce a stash.useBuiltin config variable, and re-introduce the shell-scripted version as git-legacy-stash.sh, and also let the Git for Windows default to false here, and

I think having at least the config variable would be a good thing I think.  I'm having some seconds thoughts on what I said yesterday on IRC:

> yeah I gave the stash patches a look, and I didn't find anything that seemed seriously wrong with them

I *did* spot a few bugs, especially in the last patch in the series, which breaks stash in a `worktree` I think.  Also the configuration variables are not respected correctly.  This is the two top ones that I remember of the top of my head.  I can help trying to sort through my review feedback to see what I consider broken vs. possible improvements in the code, but that's not going to happen any earlier than the weekend.

**Comment by prertik** [comment]
Whoa! Awesome!! You implemented `rebase --am` too, cool! Excited about the new release incorporating these. :tada:

**Comment by peolsson** [comment]
I use both rebase -i and stash quite often. I've tested this new release, and so far I'm amazed by the speed improvement! I will continue running this version and report back if I find any issues with it.

**Comment by dscho** [comment]
Superseded by https://github.com/git-for-windows/git/pull/1806

**Comment by dscho** [comment]
> Superseded by #1806

(This will hopefully be published as Git for Windows v2.19.0-rc1 soon. And it does have the built-in `stash` and `rebase` as experimental options, opt-in, as recommended by @tgummerer.)

**Pull request closed without merging**
