### PR TITLE
Rebase to v2.40.0

### PR DESCRIPTION
**Pull request by dscho**
<details><summary>Range-diff relative to main</summary>

* 1:  bd6ebabe440f =   1:  f124a5d354cc windows: ignore empty `PATH` elements
* 2:  848c9c80b29d =   2:  96694083d4c2 is_Cygwin: avoid `exec`ing anything
* 3:  eff706cac6fe =   3:  c2fc8a33b12e Move is_<platform> functions to the beginning
* 4:  52e2f38a0e55 =   4:  bd4d74e2aafd Move the `_which` function (almost) to the top
* 5:  1e24734213f9 =   5:  41fb13834b3b Work around Tcl's default `PATH` lookup
* 6:  714fb8a8111e =   6:  8f6e9f2b6892 gitk(Windows): avoid inadvertently calling executables in the worktree
* 7:  4f4b19deb9dc =   7:  11cca9dcba3b t9350: point out that refs are not updated correctly
* 8:  c08973ecb09e =   8:  b3a4cdb4768e transport-helper: add trailing --
* 9:  d0e800641710 =   9:  6d37f548d2ea remote-helper: check helper status after import/export
* 10:  4787255c79d8 =  10:  fbfecff622b1 mingw: demonstrate a problem with certain absolute paths
* 14:  5ea7bc81eb81 =  11:  899a0b9a5445 gitk: prevent overly long command lines
* 15:  47e24be0e9be =  12:  9d5386f4fd7c clean: do not traverse mount points
* 13:  c9d5afa99040 =  13:  940209528b75 mingw: include the Python parts in the build
* 11:  78b49fb29b0d =  14:  62535f209d6b Always auto-gc after calling a fast-import transport
* 12:  c5b0bf833cb2 =  15:  17f4b41a031c mingw: allow absolute paths without drive prefix
* 17:  6425518d7aed =  16:  f155ab81be9e mingw: change core.fsyncObjectFiles = 1 by default
* 18:  7238456cf5d1 =  17:  6fea891a5f8b gitk: Escape file paths before piping to git log
* 19:  131170e57786 =  18:  8771bcbadbc6 clean: remove mount points when possible
* 16:  168b16ee8e5d =  19:  cd1dd7fc4c66 win32/pthread: avoid name clashes with winpthread
* 20:  b7544b2e84b7 =  20:  646dc9bc030b git-compat-util: avoid redeclaring _DEFAULT_SOURCE
* 21:  7e39b9e65fdc =  21:  ddbf6d0e5c01 Import the source code of mimalloc v2.0.9
* 37:  c6c23ca0c1e5 =  22:  8a2ee8fd8962 vcxproj: unclash project directories with build outputs
* 29:  fe35fb9962b8 =  23:  88e7449f6df6 mingw: ensure valid CTYPE
* 22:  144bdf5cdb40 =  24:  19814dce0d5f mimalloc: adjust for building inside Git
* 30:  923fcfb6b2a9 =  25:  20fffa06b4a2 mingw: demonstrate a `git add` issue with NTFS junctions
* 38:  93dd2595ade8 =  26:  bcf7ca371e41 t5505/t5516: allow running without `.git/branches/` in the templates
* 31:  ff07440ffd12 =  27:  a9c0818b34d8 mingw: allow `git.exe` to be used instead of the "Git wrapper"
* 23:  484fb347b3bd =  28:  73c8c75b69e8 mimalloc: offer a build-time option to enable it
* 32:  46efdb810c47 =  29:  90692235c657 strbuf_realpath(): use platform-dependent API if available
* 39:  ed9bd0890e25 =  30:  9d4a8a75a85a t5505/t5516: fix white-space around redirectors
* 33:  1ac14aca4b45 =  31:  5caced36ab6d mingw: ignore HOMEDRIVE/HOMEPATH if it points to Windows' system directory
* 34:  ae43de6e82ff =  32:  e791e3086125 http: use new "best effort" strategy for Secure Channel revoke checking
* 24:  5ac453cca012 =  33:  a4b4e6b4c18f mingw: use mimalloc
* 25:  3f3618a36172 =  34:  6f00d6e4136f Config option to disable side-band-64k for transport
* 26:  10ed21f8d5d2 =  35:  fa68002ef9ab mingw: make sure `errno` is set correctly when socket operations fail
* 27:  10a00ff40e0b =  36:  227e59ef6045 mingw: do resolve symlinks in `getcwd()`
* 28:  7a6656d85520 =  37:  2469d5f645a9 mingw: fix fatal error working on mapped network drives on Windows
* 35:  d92cc58a0710 =  38:  048dd3cb625e clink.pl: fix MSVC compile script to handle libcurl-d.lib
* 36:  fef731ea9e33 =  39:  11349793db7a mingw: implement a platform-specific `strbuf_realpath()`
* 44:  3faf821bb4f0 =  40:  1d2c84a59379 clink.pl: fix libexpatd.lib link error when using MSVC
* 45:  6547869d7700 =  41:  f7ead44aa98a Makefile: clean up .ilk files when MSVC=1
* 46:  755d9079365b =  42:  289dc2181be6 vcbuild: add support for compiling Windows resource files
* 47:  257f10a1e350 =  43:  ac9583cfeba6 config.mak.uname: add git.rc to MSVC builds
* 48:  7e54968f6756 =  44:  22bea9881b80 clink.pl: ignore no-stack-protector arg on MSVC=1 builds
* 49:  bf748c59de71 =  45:  e8c9213de060 clink.pl: move default linker options for MSVC=1 builds
* 50:  5f816933f1d0 =  46:  4850092e4739 buildsystems: remove duplicate clause
* 51:  11946d937038 =  47:  9f7526b8a032 vcxproj: handle resource files, too
* 52:  9cbfb50cb11a =  48:  d7ac97116663 vcxproj: ignore -fno-stack-protector and -fno-common
* 60:  ea98bb2f9160 =  49:  e81bb008977d vcxproj: handle GUI programs, too
* 54:  32c43bebde8f =  50:  60245c61f6c0 vcpkg_install: detect lack of Git
* 62:  c24d59db4699 =  51:  186485406843 win32: add a helper to run `git.exe` without a foreground window
* 55:  e76e70177a08 =  52:  41d46e6396a3 vcpkg_install: add comment regarding slow network connections
* 64:  0bb4143ae848 =  53:  67837703ca45 git maintenance: avoid console window in scheduled tasks on Windows
* 56:  9b06ea5806ed =  54:  f0f12c03a727 vcxproj: support building Windows/ARM64 binaries
* 40:  5afa5f1e2ce5 =  55:  3507ef762416 t3701: verify that we can add *lots* of files interactively
* 41:  05b951a6fe82 =  56:  5fabc8a5b613 git add -i: handle CR/LF line endings in the interactive input
* 42:  4a53c10af659 =  57:  1fc535dd26db commit: accept "scissors" with CR/LF line endings
* 43:  e1becce4975c =  58:  52ef10ac9c01 t0014: fix indentation
* 53:  89c2f6d60077 =  59:  046d7583748f git-gui: accommodate for intent-to-add files
* 228:  ccf4bc39e347 =  60:  a931ea3873ef cmake: install headless-git.
* 57:  74fada2f1602 =  61:  f03ace2d5fb4 vcbuild: install ARM64 dependencies when building ARM64 binaries
* 58:  eecf0e068e85 =  62:  9d1f711ac054 vcbuild: add an option to install individual 'features'
* 59:  c5c6ebe216ad =  63:  3ceff8888fd9 cmake: allow building for Windows/ARM64
* 61:  55023a834bd6 =  64:  fd808c371ed3 ci(vs-build) also build Windows/ARM64 artifacts
* 73:  9e78caba49d4 =  65:  ee1cfcb55953 hash-object: demonstrate a >4GB/LLP64 problem
* 63:  e3836303ce39 =  66:  d4dff6294783 Add schannel to curl installation
* 74:  6ba5d0b4de5c =  67:  c4f5b0cc951f hash_object_file_literally(): use size_t
* 65:  53a1855c8757 =  68:  4d7e56a45311 cmake(): allow setting HOST_CPU for cross-compilation
* 75:  98acebbe51d6 =  69:  ec8e7efb7afc object-file.c: use size_t for header lengths
* 67:  fc9bd9531fb2 =  70:  d93cf8b05cf0 CMake: default Visual Studio generator has changed
* 76:  e7670bb712fb =  71:  9e7074d2a3e8 hash algorithms: use size_t for section lengths
* 77:  9aaf88142f7e =  72:  acee1a14da6f .gitignore: add Visual Studio CMakeSetting.json file
* 78:  6bdf3beab49c =  73:  a5bd1c1a5fed hash-object --stdin: verify that it works with >4GB/LLP64
* 66:  e0d4df570660 =  74:  77e2349e8bd8 subtree: update `contrib/subtree` `test` target
* 79:  024d6fcb0990 =  75:  ba385cd5d095 CMakeLists: add default "x64-windows" arch for Visual Studio
* 80:  a54f43008d6c =  76:  63cb1d8db1bf hash-object: add another >4GB/LLP64 test case
* 68:  b4ab549e2409 =  77:  9efd86dfea25 ci(vs-build): download the vcpkg artifacts using a dedicated Action
* 69:  b416fb12ea15 =  78:  dcefb0d0df15 mingw: allow for longer paths in `parse_interpreter()`
* 70:  94b25687f6bb =  79:  b2c9c2369af8 compat/vcbuild: document preferred way to build in Visual Studio
* 71:  a6edb377f7d5 =  80:  d1752b8ae42a http: optionally send SSL client certificate
* 72:  78bb93f37bf2 =  81:  d4cc077d994e ci: run `contrib/subtree` tests in CI builds
* 81:  393029109698 =  82:  f4a888feb71d CMake: show Win32 and Generator_platform build-option values
* 82:  00dfbdb2958b =  83:  7df25e3fc53f init: do parse _all_ core.* settings early
* 83:  87fa9178a6f4 =  84:  39038c8c23e6 Enable the built-in FSMonitor as an experimental feature
* 84:  b2288e719a64 =  85:  dfa1d8ae1c5a vcxproj: allow building with `NO_PERL` again
* 85:  ff812430e28e =  86:  819a30a539f4 vcxproj: require C11
* 87:  8094cbfe6d5d =  87:  c17c30e73f7f vcxproj: ignore the `-pedantic` option
* 93:  65eea9736240 =  88:  46d32372ec3b vcxproj: include reftable when committing `.vcxproj` files
* 94:  a78b8801cb61 =  89:  e40dfcbd6561 vcxproj: handle libreftable_test, too
* 95:  4a17ceb3171f =  90:  ca18e9d01df8 vcxproj: avoid escaping double quotes in the defines
* 96:  493b47bd4a24 =  91:  030bc6bc1256 ci: adjust Azure Pipeline for `runs_on_pool`
* 97:  ffe17b35b425 =  92:  164d8bb9261e ci: stop linking the `prove` cache
* 98:  86fa888f5a66 =  93:  aca3d9a2a8c1 ci: reinstate Azure Pipelines support
* 99:  bd8d5769267e =  94:  a4c6c25b1842 azure-pipeline: drop the `GETTEXT_POISON` job
* 100:  8e021b2744b7 =  95:  90776c164f90 azure-pipeline: stop hard-coding `apt-get` calls
* 101:  399612a7e05c =  96:  f9d38b1f7de2 azure-pipeline: drop the code to write to/read from a file share
* 102:  10c79c9bdd5f =  97:  b9a7f14bfe0c azure-pipeline: use partial clone/parallel checkout to initialize minimal-sdk
* 86:  137fe29e86de =  98:  f9bfcd6010ea setup: properly use "%(prefix)/" when in WSL
* 103:  625eb6b62789 =  99:  af7d72abd302 azure-pipeline: downcase the job name of the `Linux32` job
* 88:  d9760e713c0c = 100:  a39d3b2d4c09 hash-object: add a >4GB/LLP64 test case using filtered input
* 89:  0cef7b85e88d = 101:  d4d15de65294 compat/mingw.c: do not warn when failing to get owner
* 90:  8577111ac4c4 = 102:  0cf7f677f46b mingw: $env:TERM="xterm-256color" for newer OSes
* 91:  65d4229fa139 = 103:  956f197a4968 winansi: check result and Buffer before using Name
* 92:  bb2c55911262 = 104:  28159be4f632 Add config option `windows.appendAtomically`
* 104:  82230ee581b0 = 105:  d20e7ab7383c azure-pipeline: run static-analysis on jammy
* 105:  a84cb92bbc3e = 106:  bef11ce832c6 MinGW: link as terminal server aware
* 108:  4474514a19ca = 107:  502f2539f600 Fix Windows version resources
* 106:  4cbf821cb66d = 108:  0902c8febbf1 bswap.h: add support for built-in bswap functions
* 107:  d1f2f74222e1 = 109:  a19211c0c2e3 config.mak.uname: add support for clangarm64
* 109:  d31b9b73842a = 110:  1606ab873d3f ci: create clangarm64-build.yml
* 110:  35ffb00b04df = 111:  3982fcfdef22 status: fix for old-style submodules with commondir
* 111:  3d02958a6fa0 = 112:  7cf44348db93 windows: skip linking `git-<command>` for built-ins
* 112:  2a97c0384576 = 113:  aed229ef0258 Win32: make FILETIME conversion functions public
* 113:  e9a5264ae5a2 = 114:  805fcc90b844 Win32: dirent.c: Move opendir down
* 114:  1b9a8727ffd1 = 115:  92a5b46200a3 mingw: make the dirent implementation pluggable
* 115:  2c47f208202b = 116:  5b068f382bda Win32: make the lstat implementation pluggable
* 116:  9d0fae29f71c = 117:  32611101c3a8 add infrastructure for read-only file system level caches
* 117:  590186953899 = 118:  41e3d13398f1 mingw: add a cache below mingw's lstat and dirent implementations
* 118:  0dc4c255f233 = 119:  a8cdc59803ef fscache: load directories only once
* 119:  114332446fad = 120:  f7bbedbfb99a fscache: add key for GIT_TRACE_FSCACHE
* 120:  f83dfbc89615 = 121:  a916c7eb74c9 fscache: remember not-found directories
* 121:  8c398e4cae7d = 122:  d29d19eaaccc fscache: add a test for the dir-not-found optimization
* 122:  7f1524716cec = 123:  971055c649f7 add: use preload-index and fscache for performance
* 123:  9f4bb06a67bc = 124:  0642202152e5 dir.c: make add_excludes aware of fscache during status
* 124:  faa042ca983c = 125:  8dad19afc796 fscache: make fscache_enabled() public
* 125:  30c5220168ae = 126:  7741a997cedb dir.c: regression fix for add_excludes with fscache
* 126:  d9e05e7b344e = 127:  6dc39f9c3db5 fetch-pack.c: enable fscache for stats under .git/objects
* 127:  72a658fd8b33 = 128:  d4e674788199 checkout.c: enable fscache for checkout again
* 128:  8293c814103f = 129:  f963200ec9bd Enable the filesystem cache (fscache) in refresh_index().
* 129:  6a06ac0e6fe3 = 130:  3c036ab332a3 fscache: use FindFirstFileExW to avoid retrieving the short name
* 130:  5c4819eec1ac = 131:  5c33ee435d10 status: disable and free fscache at the end of the status command
* 131:  25cde1afca96 = 132:  5b8dd172fab3 fscache: add GIT_TEST_FSCACHE support
* 132:  27325920ba79 = 133:  1094fe76c93c fscache: add fscache hit statistics
* 133:  bddbefa0a652 = 134:  0f91efcc4bc6 mem_pool: add GIT_TRACE_MEMPOOL support
* 134:  24bdcf770f33 = 135:  152997e6b0b8 fscache: fscache takes an initial size
* 135:  808412ed391f = 136:  924b15e30051 fscache: update fscache to be thread specific instead of global
* 136:  9d0ea8c05320 = 137:  8ffa3df978e8 fscache: teach fscache to use mempool
* 137:  6a37d04b76d5 = 138:  61c922b12abc fscache: make fscache_enable() thread safe
* 138:  f3bd1f8408ee = 139:  7d10c2e43535 fscache: teach fscache to use NtQueryDirectoryFile
* 139:  bbe1619179de = 140:  b19f21a8f004 unpack-trees: enable fscache for sparse-checkout
* 140:  c92c48a88d48 = 141:  a27b7128a8fa fscache: remember the reparse tag for each entry
* 141:  dfa4d99b2ee7 = 142:  c88ed01871ea git-gui: provide question helper for retry fallback on Windows
* 142:  feb7e8502d57 = 143:  d5fbcc56d493 git gui: set GIT_ASKPASS=git-gui--askpass if not set yet
* 149:  0b065650cbc7 = 144:  baae7573bbf1 gitk: Unicode file name support
* 143:  6671a36fa8af = 145:  7136ae4d4913 git-gui--askyesno: fix funny text wrapping
* 150:  d3bb7a907207 = 146:  63f795e3f1c0 gitk: Use an external icon file on Windows
* 144:  f08ace1eec44 = 147:  b13397ff4bdb git-gui--askyesno: allow overriding the window title
* 146:  977bfb68bd2f = 148:  dcaa509f806a respect core.hooksPath, falling back to .git/hooks
* 151:  111dcff8090b = 149:  bb071a974c8a gitk: fix arrow keys in input fields with Tcl/Tk >= 8.6
* 147:  b995977f1257 = 150:  78fa37ae3efc git-gui--askyesno (mingw): use Git for Windows' icon, if available
* 145:  2395dc62909b = 151:  443c5e326456 fscache: implement an FSCache-aware is_mount_point()
* 152:  ccd96aff2050 = 152:  7f52ee8fac8c gitk: make the "list references" default window width wider
* 148:  6977d38e3109 = 153:  4a4d1feb10cf clean: make use of FSCache
* 153:  fa6b1aec5e7e = 154:  10fef8a8f785 pack-objects (mingw): demonstrate a segmentation fault with large deltas
* 154:  2ee7f4acb829 = 155:  a2e5877c7284 mingw: support long paths
* 155:  46845f7a412f = 156:  fc8774b0521c Win32: fix 'lstat("dir/")' with long paths
* 156:  77add86656e4 = 157:  ef64beb78be8 mingw: Support `git_terminal_prompt` with more terminals
* 157:  15878ad415bd = 158:  946ee8209315 compat/terminal.c: only use the Windows console if bash 'read -r' fails
* 165:  6fe019f78649 = 159:  f7d4d0b18a28 compat/fsmonitor/fsm-*-win32: support long paths
* 166:  70b4cfc4e282 = 160:  2a112ca4a719 clean: suggest using `core.longPaths` if paths are too long to remove
* 158:  59126f1e0858 = 161:  9b123474eb84 mingw (git_terminal_prompt): do fall back to CONIN$/CONOUT$ method
* 159:  8bee12af4882 = 162:  34af1136ec69 Unbreak interactive GPG prompt upon signing
* 160:  255d2598469c = 163:  50c593487af0 strbuf_readlink: don't call readlink twice if hint is the exact link size
* 161:  1fb39b925e46 = 164:  234570d57db7 strbuf_readlink: support link targets that exceed PATH_MAX
* 162:  4682a97651bf = 165:  b53898387e63 lockfile.c: use is_dir_sep() instead of hardcoded '/' checks
* 163:  693a45df5010 = 166:  4abf6c0e9b05 Win32: don't call GetFileAttributes twice in mingw_lstat()
* 164:  952fd43acff1 = 167:  8d590b278537 Win32: implement stat() with symlink support
* 167:  b8af7534d2f5 = 168:  dbd77b9e463b Win32: remove separate do_lstat() function
* 168:  788a8888daaf = 169:  693d52525808 Win32: let mingw_lstat() error early upon problems with reparse points
* 169:  38b412fac77b = 170:  238d5165dc35 mingw: teach fscache and dirent about symlinks
* 170:  2cc9f7f474b0 = 171:  31dccd7c56e2 Win32: lstat(): return adequate stat.st_size for symlinks
* 171:  4daaca7644f9 = 172:  568ffe165c66 Win32: factor out retry logic
* 172:  4920f9d0681b = 173:  5e7668815645 Win32: change default of 'core.symlinks' to false
* 173:  77ceacfe58a0 = 174:  dc2061c375e7 Win32: add symlink-specific error codes
* 174:  1ba6d1b5fb2d = 175:  550a0b9b245f Win32: mingw_unlink: support symlinks to directories
* 175:  bd3cf50e1e5b = 176:  e3ec56641371 Win32: mingw_rename: support renaming symlinks
* 176:  4a5304cad476 = 177:  d1595125d3bd Win32: mingw_chdir: change to symlink-resolved directory
* 177:  56193d96f088 = 178:  52ff58616e96 Win32: implement readlink()
* 178:  dcb9ab62cb53 = 179:  f428857c9f1c mingw: lstat: compute correct size for symlinks
* 179:  2b9eed303920 = 180:  f80d20448879 Win32: implement basic symlink() functionality (file symlinks only)
* 180:  68d5dceed03b = 181:  c49125df8916 Win32: symlink: add support for symlinks to directories
* 181:  9ec33a8f2ccc = 182:  16446927d511 mingw: try to create symlinks without elevated permissions
* 182:  0b4ba1de4eb3 = 183:  817b60da91b7 mingw: emulate stat() a little more faithfully
* 183:  e9dd0b295f9f = 184:  bac60d0ab46e mingw: special-case index entries for symlinks with buggy size
* 184:  9fdca04b0ab4 = 185:  0d91a17e402e Win32: symlink: move phantom symlink creation to a separate function
* 185:  23152df08751 = 186:  bd664348182c Introduce helper to create symlinks that knows about index_state
* 187:  1570ab2d5883 = 187:  a0e43a37bb5f mingw: allow to specify the symlink type in .gitattributes
* 189:  2254c0acc9e8 = 188:  1c7a8c51578f Win32: symlink: add test for `symlink` attribute
* 191:  97fd87f590ed = 189:  8df24b7d885b mingw: explicitly specify with which cmd to prefix the cmdline
* 193:  0355237ce432 = 190:  2d8fe06910dd mingw: when path_lookup() failed, try BusyBox
* 194:  576ff5486dba = 191:  93e62dd96764 test-lib: avoid unnecessary Perl invocation
* 195:  b52b7fef98b4 = 192:  1c322d28c59f test-tool: learn to act as a drop-in replacement for `iconv`
* 196:  81ae93188beb = 193:  37928a6fc08b tests(mingw): if `iconv` is unavailable, use `test-helper --iconv`
* 197:  dabf4f956894 = 194:  89d4d810e741 gitattributes: mark .png files as binary
* 198:  df7d1bd15f80 = 195:  7606ef021be7 tests: move test PNGs into t/lib-diff/
* 199:  e46ec6df0c43 = 196:  283dd54ad583 tests: only override sort & find if there are usable ones in /usr/bin/
* 200:  b53e78155974 = 197:  bac0a1e36716 tests: use the correct path separator with BusyBox
* 201:  04e60284fc3c = 198:  79a36c874cb4 mingw: only use Bash-ism `builtin pwd -W` when available
* 186:  399b27b49044 = 199:  9a1623846e05 mingw: introduce code to detect whether we're inside a Windows container
* 202:  682a4daa4c5c = 200:  0cbc48f7a080 tests (mingw): remove Bash-specific pwd option
* 188:  ecb4aae5c458 = 201:  6938c4d0ad05 mingw: when running in a Windows container, try to rename() harder
* 203:  2e296318ebc0 = 202:  45216ee3101c test-lib: add BUSYBOX prerequisite
* 190:  59065b4148da = 203:  cc71976837b9 mingw: move the file_attr_to_st_mode() function definition
* 204:  2733c0795bec = 204:  6cbbcba504b3 t5003: use binary file from t/lib-diff/
* 192:  0d876cec28dc = 205:  031ec3308fcf mingw: Windows Docker volumes are *not* symbolic links
* 205:  f83180ebc3b6 = 206:  b619ac520aed t5532: workaround for BusyBox on Windows
* 206:  b2d14f380da7 = 207:  632ca18c8573 t5605: special-case hardlink test for BusyBox-w32
* 207:  f7a9c37e1e22 = 208:  122795773239 t5813: allow for $PWD to be a Windows path
* 208:  b4472e495ada = 209:  a93d3b3f2e16 t9200: skip tests when $PWD contains a colon
* 209:  37982fd562cc = 210:  d8d6f5e952f4 mingw: kill child processes in a gentler way
* 210:  bc91e2f11bb3 = 211:  ddb9a444e7e8 mingw: do not call xutftowcs_path in mingw_mktemp
* 213:  b78c0c56edd3 = 212:  cf59ddc861b7 Describe Git for Windows' architecture [no ci]
* 211:  4a4f41804da0 = 213:  3ccbb859961e mingw: add a Makefile target to copy test artifacts
* 212:  7870f217d151 = 214:  bd47e4f14a39 mingw: really handle SIGINT
* 215:  ababf9f37e78 = 215:  224615951349 Partially un-revert "editor: save and reset terminal after calling EDITOR"
* 216:  7b78a7986133 = 216:  64587ed881b8 reset: reinstate support for the deprecated --stdin option
* 217:  ee05cc3a6b04 = 217:  8e4630867ddb mingw: deprecate old-style runtime-prefix handling in interpolate_path()
* 218:  41087a2c203d = 218:  2c9d6e7efbc2 fsmonitor: reintroduce core.useBuiltinFSMonitor
* 219:  621ea060e4f0 ! 219:  d00bb49c2352 Add a GitHub workflow to monitor component updates

   ``````diff
   @@ .github/workflows/monitor-components.yml (new)
    +          - label: git-lfs
    +            feed: https://github.com/git-lfs/git-lfs/tags.atom
    +          - label: git-credential-manager
   -+            feed: https://github.com/GitCredentialManager/git-credential-manager/tags.atom
   ++            feed: https://github.com/git-ecosystem/git-credential-manager/tags.atom
    +          - label: tig
    +            feed: https://github.com/jonas/tig/tags.atom
    +          - label: cygwin
   ``````

* 214:  246b09200b29 = 220:  aa4b8bb45042 Modify the Code of Conduct for Git for Windows
* 220:  86f4df79837b = 221:  e33a6dc55e4c CONTRIBUTING.md: add guide for first-time contributors
* 221:  4c68eb191105 = 222:  e908fa62573c README.md: Add a Windows-specific preamble
* 222:  89504260130f = 223:  3ae47928eb9e Add an issue template
* 223:  27d54960c346 = 224:  17ca14e0b8a7 Modify the GitHub Pull Request template (to reflect Git for Windows)
* 224:  119e067c6984 = 225:  b6e1156408c4 .github: Add configuration for the Sentiment Bot
* 225:  931156b1c91f = 226:  d20e1fcc917f Document how $HOME is set on Windows
* 226:  172f79f7446b = 227:  32960c7ef14c SECURITY.md: document Git for Windows' policies
* 227:  f6ec79b0b84f <   -:  ------------ fixup! Add a GitHub workflow to monitor component updates

</details>

### CODE REVIEW

**Review by derrickstolee — APPROVED** [review]
> * 219:  [621ea06](https://github.com/git-for-windows/git/commit/621ea060e4f046c0198a795f5043e3440d7f0087) ! 219:  [d00bb49](https://github.com/git-for-windows/git/commit/d00bb49c2352e2fa8056427ff750694dc37b4626) Add a GitHub workflow to monitor component updates
>   ```diff
>   @@ .github/workflows/monitor-components.yml (new)
>    +          - label: git-lfs
>    +            feed: https://github.com/git-lfs/git-lfs/tags.atom
>    +          - label: git-credential-manager
>   -+            feed: https://github.com/GitCredentialManager/git-credential-manager/tags.atom
>   ++            feed: https://github.com/git-ecosystem/git-credential-manager/tags.atom
>    +          - label: tig
>    +            feed: https://github.com/jonas/tig/tags.atom
>    +          - label: cygwin
>   ```

:heart:

**Comment by dscho** [comment]
Note: I canceled the `main.yml` workflow run because https://github.com/git-for-windows/git/actions/runs/4407752569 is still running and validates a tree-same commit. I have no doubt that the latter will eventually succeed, after which I will re-run this PR's run, which will then pick up that successful run and skip building and testing (because it's already validated, and we're not in the business of unduly wasting resources, however generously they might have been donated to the project) with success.

**Pull request merged**
