### PR TITLE
Rebase to 2.34.0-rc1

### PR DESCRIPTION
**Pull request by vdye**
Adds a fix for the Fedora build to `ready-for-upstream` (branch `vdye/fix-fedora-build`), but otherwise a clean rebase!

Range diff:

```
   1:  5edc74f93c =   1:  dfa8ebced1 t9350: point out that refs are not updated correctly
  14:  75047aef51 =   2:  e2507b697d mingw: ensure valid CTYPE
   2:  8ad985ab15 =   3:  95d2f28358 transport-helper: add trailing --
  10:  93134bb0f6 =   4:  45b284f83d mingw: demonstrate a `git add` issue with NTFS junctions
 114:  840230f078 =   5:  5f6bc30523 mingw: allow `git.exe` to be used instead of the "Git wrapper"
   3:  97774b3c88 =   6:  c1153d5f33 remote-helper: check helper status after import/export
   4:  bd8a984adf =   7:  b11a18dbee mingw: demonstrate a problem with certain absolute paths
   7:  ed7fb40dc0 =   8:  28eb04fc04 archive: replace write_or_die() calls with write_block_or_die()
  11:  09de934271 =   9:  8a305383f8 gitk: prevent overly long command lines
  12:  589df84122 =  10:  aea2904ec5 clean: do not traverse mount points
  13:  af3405b167 =  11:  e06de56cd0 strbuf_realpath(): use platform-dependent API if available
  25:  8ab119c721 =  12:  19f9da9b3a vcxproj: unclash project directories with build outputs
 115:  b0f9908f31 =  13:  8c3dcf1f33 mingw: ignore HOMEDRIVE/HOMEPATH if it points to Windows' system directory
  24:  efeeeaa0bb =  14:  0b1483e430 http: use new "best effort" strategy for Secure Channel revoke checking
   5:  13907b6dab =  15:  8e27c745e9 Always auto-gc after calling a fast-import transport
   6:  4b2ea66ad9 =  16:  c7e2d413fb mingw: allow absolute paths without drive prefix
   8:  741a5a3842 =  17:  0954f06c12 archive: avoid spawning `gzip`
   9:  ea6f42d9c3 =  18:  dcc3bc89e6 mingw: change core.fsyncObjectFiles = 1 by default
  15:  a56cde4289 =  19:  92a0d9da31 gitk: Escape file paths before piping to git log
  16:  69d359f8bf =  20:  4081e1ba52 clean: remove mount points when possible
  17:  b9e0f9ee75 =  21:  3836724a52 mingw: include the Python parts in the build
  18:  ad613152ff =  22:  e14fc032d8 Config option to disable side-band-64k for transport
  19:  b5d21cee11 =  23:  c2234bd7a3 mingw: make sure `errno` is set correctly when socket operations fail
  20:  9b7a09694a =  24:  5e2f5c9b75 mingw: do resolve symlinks in `getcwd()`
  21:  7d5ca878e2 =  25:  694c0940c0 mingw: fix fatal error working on mapped network drives on Windows
  22:  79c80ab7cb =  26:  1c5f4c028a clink.pl: fix MSVC compile script to handle libcurl-d.lib
  23:  db6382fe79 =  27:  47958acdb0 mingw: implement a platform-specific `strbuf_realpath()`
  26:  0a8380de5f =  28:  f514bf4838 t5505/t5516: allow running without `.git/branches/` in the templates
  39:  cec6b3b4c8 =  29:  33ad9e986f t5505/t5516: fix white-space around redirectors
 116:  59a0d3baa9 =  30:  3937729754 clink.pl: fix libexpatd.lib link error when using MSVC
 117:  c9574ab2f8 =  31:  64bc95aaa6 Makefile: clean up .ilk files when MSVC=1
 118:  270e48b6c2 =  32:  dd4feabfd2 vcbuild: add support for compiling Windows resource files
 119:  84027885b7 =  33:  bfc468a1ac config.mak.uname: add git.rc to MSVC builds
  27:  d598e0575a =  34:  8c8d756158 vcpkg_install: detect lack of Git
 120:  a22c706377 =  35:  37b1d84fac clink.pl: ignore no-stack-protector arg on MSVC=1 builds
  28:  c805336e45 =  36:  60c77d4a37 vcpkg_install: add comment regarding slow network connections
 121:  859cf4110d =  37:  9472b3532b clink.pl: move default linker options for MSVC=1 builds
  29:  f660190445 =  38:  5d7c693c27 vcxproj: support building Windows/ARM64 binaries
 122:  30b80f6c82 =  39:  401228fd93 buildsystems: remove duplicate clause
  30:  4011cf2293 =  40:  e1e1ae5922 vcbuild: install ARM64 dependencies when building ARM64 binaries
 123:  c6e11c2406 =  41:  24565a7648 vcxproj: handle resource files, too
  31:  85a8d68a2e =  42:  f4a1c27a31 vcbuild: add an option to install individual 'features'
 124:  b9ee73507c =  43:  bd9e31cad1 vcxproj: ignore -fno-stack-protector and -fno-common
  32:  12b7d5b2a4 =  44:  357282cbee Add a GitHub workflow to generate Git for Windows' Pacman package
  33:  bb5575a9e9 =  45:  ad33dde8e1 cmake: allow building for Windows/ARM64
 125:  212c2bea19 =  46:  76a631e494 vcxproj: handle GUI programs, too
  34:  d84bb12679 =  47:  1078334dc6 git-artifacts: if GPG secrets are available, use them
  35:  c29bc3dff2 =  48:  b74dcedda4 ci(vs-build) also build Windows/ARM64 artifacts
  36:  5f50435580 =  49:  dde71778d3 Allow `add -p` and `add -i` with a large number of files
 127:  5c24b25129 =  50:  d716a43ddd win32: add a helper to run `git.exe` without a foreground window
  37:  3062433938 =  51:  7e611137b5 git-artifacts: also code-sign, if configured via the secrets
  38:  ce77b07f7b =  52:  c3b96f59f3 Add schannel to curl installation
  40:  97ce9c212a =  53:  0d8eaabca4 t3701: verify that we can add *lots* of files interactively
  41:  d13da7cc43 =  54:  1bff2efc7f git add -i: handle CR/LF line endings in the interactive input
  42:  56060ba7b8 =  55:  a1968f9a5d commit: accept "scissors" with CR/LF line endings
  43:  6edda184ff =  56:  1a1745db23 t0014: fix indentation
  44:  d68afbaebe =  57:  2482f4e12f git-gui: accommodate for intent-to-add files
 128:  25884623dd =  58:  6fcc2da8fa git maintenance: avoid console window in scheduled tasks on Windows
  45:  f3b3ada7ce =  59:  2ad36507b1 git-artifacts: also build the installer
  46:  1c7e19f237 =  60:  ca235e0f81 git-artifacts: also build portable, mingit and mingit-busybox
  47:  ed93be64d2 =  61:  e27e3c27ca git-artifacts: also build 32-bit versions
  48:  d806781d7e =  62:  cbf0e55a77 git-artifacts: also build the nuget package
  49:  d0237839d7 =  63:  d8bda3b2e2 git-artifacts: allow restricting which artifacts are built
  50:  1bef441825 =  64:  36daf04b2a git-artifacts: allow specifying repo/ref via workflow_dispatch
  51:  4e56e13b09 =  65:  f5c271ca04 git-artifacts: cache the build-installers artifact
  52:  59eb8b3d83 =  66:  88f2561b84 git-artifacts: use the cached build-installers instead of makepkg-git
  53:  5bee1eca82 =  67:  78b658f398 git-artifacts: add ARM64 artifacts
  54:  c6744a80c9 =  68:  912f4ad5fc git-artifacts(arm64): avoid hard-linking the dashed built-ins
  55:  59f49b9717 =  69:  10c23dbd22 git-artifacts: use a narrower `PATH`
  56:  fd9a4f01bc =  70:  95b96ddf47 git-artifacts: fix BUILD_ONLY handling for ARM64
  57:  6e4d4a6743 =  71:  ff5ca13707 git-artifacts: extend the `SKIP` logic to handle `pkg` and `build-arm64`
  58:  30f3ce1d80 =  72:  053236849c git-artifacts: mark all inputs as "not required"
  59:  d7a868b611 =  73:  88c8777bdf git-artifacts(build-arm64): build artifacts using the intended Git revision
  60:  9b07a50ee2 =  74:  e7d30e1954 git-artifacts: add workaround for GCM Core on ARM64
  61:  37e62e4b17 =  75:  35759f3016 cmake(): allow setting HOST_CPU for cross-compilation
  62:  a8902e1427 =  76:  1cac293722 git-artifacts: Use the shiny new setup-git-for-windows-sdk Action
  63:  27a4aa8025 =  77:  a4848f10ae ci(): add HOST_CPU to CMake command
  69:  dda42c270f =  78:  efcc404d00 CMake: default Visual Studio generator has changed
  70:  62798a104c =  79:  0908ef79ec .gitignore: add Visual Studio CMakeSetting.json file
  67:  05be7b3263 =  80:  5610c725ec subtree: update `contrib/subtree` `test` target
  71:  87af1658ad =  81:  b49cb56e22 CMakeLists: add default "x64-windows" arch for Visual Studio
  64:  600b3374f1 =  82:  0242ead4bb ci(vs-build): download the vcpkg artifacts using a dedicated Action
  65:  0ac9f8a01f =  83:  380985273b mingw: allow for longer paths in `parse_interpreter()`
  66:  f50c2d5845 =  84:  3c4dcc5d26 compat/vcbuild: document preferred way to build in Visual Studio
 126:  0a728176b4 =  85:  f9c111cce9 http: optionally send SSL client certificate
  68:  a2ae4363e4 =  86:  6fab38d0bf ci: run `contrib/subtree` tests in CI builds
  72:  92d563c1cc =  87:  c21ab5f4db CMake: show Win32 and Generator_platform build-option values
  73:  554438be3f =  88:  c97bbecbf0 mingw: avoid fallback for {local,gm}time_r()
 129:  70789fb6c1 =  89:  606850bc88 fsmonitor: enhance existing comments
 130:  d35af7d3ec =  90:  b7b66391e8 fsmonitor-ipc: create client routines for git-fsmonitor--daemon
 131:  521d3fd3ea =  91:  d2492c9594 fsmonitor: config settings are repository-specific
 132:  800dc508c7 =  92:  f221068b14 fsmonitor: use IPC to query the builtin FSMonitor daemon
 133:  18035b2747 =  93:  301e850ca4 fsmonitor: update fsmonitor config documentation
 134:  cd6ef1d602 =  94:  c13f90bc3a fsmonitor--daemon: man page
 135:  681c53a074 =  95:  a5f48d359b fsmonitor--daemon: add a built-in fsmonitor daemon
 136:  49189d69a1 =  96:  9b81b28a27 builtin/fsmonitor--daemon: use parse-options API fully
 137:  63ed66753b =  97:  30c3f819b9 fsmonitor--daemon: implement 'stop' and 'status' commands
 138:  79e34e5c1a =  98:  0c7286d44c compat/fsmonitor/fsm-listen-win32: stub in backend for Windows
 139:  7d929b450d =  99:  644337e073 compat/fsmonitor/fsm-listen-darwin: stub in backend for Darwin
 140:  13d73a0ef0 = 100:  fa424465b1 fsmonitor--daemon: implement 'run' command
 141:  cff0633921 = 101:  eeb71a47b9 fsmonitor--daemon: implement 'start' command
 142:  780661d035 = 102:  6d4a1f90e8 fsmonitor--daemon: add pathname classification
 143:  2646363a60 = 103:  e78493c6e3 fsmonitor--daemon: define token-ids
 144:  1b481ca550 = 104:  f528d99cbe fsmonitor--daemon: create token-based changed path cache
 145:  50266f412d = 105:  39696b1c2f compat/fsmonitor/fsm-listen-win32: implement FSMonitor backend on Windows
 146:  4a4ef40a94 = 106:  bfd7ffbc4f compat/fsmonitor/fsm-listen-darwin: add macos header files for FSEvent
 147:  e73e15beb9 = 107:  4a3bcae79b compat/fsmonitor/fsm-listen-darwin: implement FSEvent listener on MacOS
 148:  aad79810b6 = 108:  082ddca19c fsmonitor--daemon: implement handle_client callback
 149:  c98cb15ebf = 109:  21f8a44c41 help: include fsmonitor--daemon feature flag in version info
 150:  02da6ae272 = 110:  53f4aa5701 t/helper/fsmonitor-client: create IPC client to talk to FSMonitor Daemon
 151:  e1e2e32754 = 111:  18e3acaf35 t7527: create test for fsmonitor--daemon
 152:  c30bafc321 = 112:  073a48c879 t/perf: avoid copying builtin fsmonitor files into test repo
 153:  5c7e684dcb = 113:  5b0afbf278 t/helper/test-chmtime: skip directories on Windows
 154:  7b32ae12af = 114:  0b20865673 t/perf/p7519: speed up test on Windows
 155:  95fa86211e = 115:  327c0335ed t/perf/p7519: add fsmonitor--daemon test cases
 156:  9c42eff3fd = 116:  b732ab0ed4 fsmonitor--daemon: periodically truncate list of modified files
 157:  3a87e9b13a = 117:  ba20c6f2b6 fsmonitor--daemon: use a cookie file to sync with file system
 158:  e9cd2cebbd = 118:  a6a2b47615 fsmonitor: force update index after large responses
 159:  69080f3eae = 119:  c12ffb3365 t7527: test status with untracked-cache and fsmonitor--daemon
 160:  17cf5ec78f = 120:  64c0cef838 compat/fsmonitor/fsm-listen-win32: handle shortnames
 161:  b0952ae9ab = 121:  91671744f0 t7527: test FS event reporing on MacOS WRT case and Unicode
 162:  91fd1ad5a0 = 122:  5da9b61f88 t7527: test builtin FSMonitor watching repos with unicode paths
 163:  2a7e7fb917 = 123:  ceca93933d t/helper/fsmonitor-client: create stress test
 164:  8fb34c85f0 = 124:  8214fe49bc fsmonitor-settings: bare repos are incompatible with FSMonitor
 165:  b32b87b89a = 125:  9a1ae86a50 fsmonitor-settings: stub in platform-specific incompatibility checking
  74:  aa01ae7cc4 = 126:  fd1e88a3c5 init: do parse _all_ core.* settings early
 166:  e415a492e6 = 127:  eff4c11f0f fsmonitor-settings: virtual repos are incompatible with FSMonitor
 167:  7ea200b45e = 128:  8faa6bc48e fsmonitor-settings: stub in platform-specific incompatibility checking on MacOS
 168:  42ff415375 = 129:  3f84ce337b fsmonitor-settings: remote repos on MacOS are incompatible with FSMonitor
 169:  6b00fba522 = 130:  d825514b4b fsmonitor-settings: remote repos on Windows are incompatible with FSMonitor
 170:  24b222f196 = 131:  962821298d unpack-trees: initialize fsmonitor_has_run_once in o->result
 171:  6eb437f5fc = 132:  bfb0976bfa compat/fsmonitor/fsm-listen-darwin: ignore FSEvents caused by xattr changes on MacOS
 172:  257fd1f4c2 = 133:  dc03e49bc2 fsmonitor--daemon: print start message only if fsmonitor.announceStartup
 173:  32501c9a98 = 134:  fe97311460 fsmonitor--daemon: cd out of worktree root
 174:  c19eef7f78 = 135:  cb7fa90ada fsmonitor--daemon: prepare for adding health thread
 175:  2fb0407757 = 136:  a17cef4789 fsmonitor--daemon: rename listener thread related variables
 176:  d6e54323d1 = 137:  5e74e6111a fsmonitor--daemon: stub in health thread
 177:  515daa7f64 = 138:  5a7ad4adfd compat/fsmonitor/fsm-health-win32: add framework for periodically monitoring
 178:  151f498c2e = 139:  a7a7111610 compat/fsmonitor/fsm-health-win32: force shutdown daemon if worktree root moves
 179:  ee3e6146ca = 140:  564eb98b64 compat/fsmonitor/fsm-listen-darwin: shutdown daemon if worktree root is moved/renamed
 180:  3dc716a9e4 = 141:  927aeae765 fsmonitor: measure time taken to apply fsmonitor query result
 181:  c1fbad2bdc = 142:  5ce0e766ec fsmonitor: optimize processing of directory events
 182:  450ac41ded = 143:  cba91f03cc t7527: FSMonitor tests for directory moves
 183:  b6852509cc = 144:  2060d59d44 fsmonitor: mark the built-in FSMonitor as experimental
 184:  971e5fdd22 = 145:  c5506570d8 Enable the built-in FSMonitor as an experimental feature
  75:  91f2e2d1c3 = 146:  425af7a9e3 git-gui: provide question helper for retry fallback on Windows
  76:  59d9caeb70 = 147:  e530235ccc git gui: set GIT_ASKPASS=git-gui--askpass if not set yet
  77:  2a0cdbf5be = 148:  e88f0aa576 gitk: Unicode file name support
  78:  395cd16008 = 149:  7028f59a1f git-gui--askyesno: fix funny text wrapping
  79:  11888174e5 = 150:  601244efff gitk: Use an external icon file on Windows
  80:  f3c24da41c = 151:  9ee90a2b01 git-gui--askyesno: allow overriding the window title
  82:  4ac01d7bd4 = 152:  12d54c15e1 respect core.hooksPath, falling back to .git/hooks
  81:  d6b9c123de = 153:  1d534e7c86 gitk: fix arrow keys in input fields with Tcl/Tk >= 8.6
  83:  142d71ab6b = 154:  4326900602 git-gui--askyesno (mingw): use Git for Windows' icon, if available
  84:  95700ec530 = 155:  0e0f3775e5 gitk: make the "list references" default window width wider
  85:  c914a11171 = 156:  06a89928b2 Modify the Code of Conduct for Git for Windows
  86:  37df46d5b7 = 157:  44f855f108 CONTRIBUTING.md: add guide for first-time contributors
  87:  5d8bceb5e4 = 158:  cfc91a2cfb README.md: Add a Windows-specific preamble
  88:  e2a408a69c = 159:  7255771c85 Add an issue template
  89:  905888a808 = 160:  79b0f3b63b Modify the GitHub Pull Request template (to reflect Git for Windows)
  91:  c8eea17d18 = 161:  f5a35a9d7a .github: Add configuration for the Sentiment Bot
  90:  c2fee0f0c7 = 162:  8c75bcfb90 status: carry the --no-lock-index option for backwards-compatibility
  95:  b05000a6c7 = 163:  9ed96b7c38 Document how $HOME is set on Windows
  92:  dff6c654a1 = 164:  b9f9d2dce0 status: reinstate --show-ignored-directory as a deprecated option
  93:  925a038d15 = 165:  9976bf7431 reset: reinstate support for the deprecated --stdin option
  94:  c8cf596f88 = 166:  61abf14943 Add a GitHub workflow to monitor component updates
  96:  637cb0df39 = 167:  db01c3e26d SECURITY.md: document Git for Windows' policies
  97:  e4cbf30ac9 = 168:  2c24264d68 tmp-objdir: new API for creating temporary writable databases
  98:  7585e42e33 = 169:  3a16916f51 tmp-objdir: disable ref updates when replacing the primary odb
  99:  2ea4103c84 = 170:  f26ecdd9d9 bulk-checkin: rename 'state' variable and separate 'plugged' boolean
 100:  153b515a3b = 171:  1555f733d3 core.fsyncobjectfiles: batched disk flushes
 101:  5da66e6b6b = 172:  ca53e4db88 core.fsyncobjectfiles: add windows support for batch mode
 102:  b8f5dbf46a = 173:  1b2e98a76f update-index: use the bulk-checkin infrastructure
 103:  f102f61822 = 174:  d73d3b8268 unpack-objects: use the bulk-checkin infrastructure
 104:  ca82eaca50 = 175:  4abaed249e core.fsyncobjectfiles: tests for batch mode
 105:  94a1e37179 = 176:  2f44adc9ae core.fsyncobjectfiles: performance tests for add and stash
 106:  d6aeb51b0f = 177:  39f1293fd4 test-genzeros: allow more than 2G zeros in Windows
 107:  ac5fad0880 = 178:  9b4dc5cee9 test-tool genzeros: generate large amounts of data more efficiently
 108:  47781897f1 = 179:  ee859f4389 test-lib: add prerequisite for 64-bit platforms
 109:  2eb9fca09f = 180:  bbc5a0213a t1051: introduce a smudge filter test for extremely large files
 110:  8a1792225e = 181:  91cd82d0cb odb: teach read_blob_entry to use size_t
 111:  baac2a712c = 182:  c5e8eda60f git-compat-util: introduce more size_t helpers
 112:  684d9f0066 = 183:  6665d24ba4 odb: guard against data loss checking out a huge file
 113:  e081fb014a = 184:  4b0a622617 clean/smudge: allow clean filters to process extremely large files
  -:  ---------- > 185:  dbd77d17c1 async_die_is_recursing: work around GCC v11.x issue on Fedora
 185:  5fd4104321 = 186:  8c8f6d4a6c Win32: make FILETIME conversion functions public
 186:  d661ec165e = 187:  ba7e5f2419 Win32: dirent.c: Move opendir down
 187:  b2194e2ba1 = 188:  3075f170c7 mingw: make the dirent implementation pluggable
 188:  5955b0fb97 = 189:  62645be1ca Win32: make the lstat implementation pluggable
 189:  14cc335836 = 190:  94196ab64f add infrastructure for read-only file system level caches
 190:  c7162598ed = 191:  aac647ed7e mingw: add a cache below mingw's lstat and dirent implementations
 191:  941a8f758f = 192:  abff5bbe42 fscache: load directories only once
 192:  3d16bd5bcb = 193:  b8053f6cbc fscache: add key for GIT_TRACE_FSCACHE
 193:  da66a73b14 = 194:  e5ce24c083 fscache: remember not-found directories
 194:  04deed9669 = 195:  1e4502cae6 fscache: add a test for the dir-not-found optimization
 195:  0669bd1e0c = 196:  af2e49b6ef add: use preload-index and fscache for performance
 196:  9703cfacfd = 197:  b0e12ac3cc dir.c: make add_excludes aware of fscache during status
 197:  6c23e7b9d0 = 198:  2da37253b7 fscache: make fscache_enabled() public
 198:  56fe00aa5d = 199:  62da989411 dir.c: regression fix for add_excludes with fscache
 199:  0171bc8bbf = 200:  4393ae6c03 fetch-pack.c: enable fscache for stats under .git/objects
 200:  2a12430dbc = 201:  d18315bb34 checkout.c: enable fscache for checkout again
 201:  61f2ade99e = 202:  593d1838ff Enable the filesystem cache (fscache) in refresh_index().
 202:  3d26d57b00 = 203:  52859d1077 fscache: use FindFirstFileExW to avoid retrieving the short name
 203:  4a27c22721 = 204:  732c447072 status: disable and free fscache at the end of the status command
 204:  c9354ca0dc = 205:  7810d1bef5 fscache: add GIT_TEST_FSCACHE support
 205:  e6675e7e8f = 206:  30204e4002 fscache: add fscache hit statistics
 206:  a0a5b038c5 = 207:  4000b2133d mem_pool: add GIT_TRACE_MEMPOOL support
 207:  579455234e = 208:  e509516f55 fscache: fscache takes an initial size
 208:  a643c1c138 = 209:  9c36c72f7c fscache: update fscache to be thread specific instead of global
 209:  820be81007 = 210:  9eedb53a1a fscache: teach fscache to use mempool
 210:  59e31fa62d = 211:  9374fdf57d fscache: make fscache_enable() thread safe
 211:  b207b84ad4 = 212:  41329335e7 fscache: teach fscache to use NtQueryDirectoryFile
 212:  0db232b6b8 = 213:  f77ba481d8 unpack-trees: enable fscache for sparse-checkout
 213:  2af46683e7 = 214:  103b43299f fscache: remember the reparse tag for each entry
 214:  0674224ddf = 215:  d635aed59a fscache: implement an FSCache-aware is_mount_point()
 215:  f248f80b65 = 216:  0d453305a9 clean: make use of FSCache
 216:  9e38bc26d0 = 217:  f3cc446c5d pack-objects (mingw): demonstrate a segmentation fault with large deltas
 217:  c5e1f8a48b = 218:  83caf8603d mingw: support long paths
 218:  c746da5a23 = 219:  57b8f1025b Win32: fix 'lstat("dir/")' with long paths
 219:  cc96cc2864 = 220:  feb55e8eac mingw: ensure that core.longPaths is handled *always*
 220:  92f5438999 = 221:  a70b627fe8 mingw: Support `git_terminal_prompt` with more terminals
 221:  d855059e2e = 222:  ebe65ef846 compat/terminal.c: only use the Windows console if bash 'read -r' fails
 222:  338b550f76 = 223:  07145aecce mingw (git_terminal_prompt): do fall back to CONIN$/CONOUT$ method
 223:  f724c89438 = 224:  570e4741dc Unbreak interactive GPG prompt upon signing
 224:  a8cbba0a41 = 225:  a1ddf9cd0e strbuf_readlink: don't call readlink twice if hint is the exact link size
 225:  749be8747c = 226:  db10ef8374 strbuf_readlink: support link targets that exceed PATH_MAX
 226:  8e3ae1f31a = 227:  6263705375 lockfile.c: use is_dir_sep() instead of hardcoded '/' checks
 227:  adb0a1317d = 228:  5cb13759bf Win32: don't call GetFileAttributes twice in mingw_lstat()
 228:  914d3095d1 = 229:  245f4d2cdc Win32: implement stat() with symlink support
 229:  32bf0bdfb4 = 230:  08d26da2bf Win32: remove separate do_lstat() function
 230:  1f6451d497 = 231:  2b70994b7c Win32: let mingw_lstat() error early upon problems with reparse points
 231:  e3bb45856a = 232:  dbb167c7e6 mingw: teach fscache and dirent about symlinks
 232:  08697c402e = 233:  12dbdd81cf Win32: lstat(): return adequate stat.st_size for symlinks
 233:  22608c097d = 234:  880d9d6021 Win32: factor out retry logic
 234:  fada59283c = 235:  b09b50d6e7 Win32: change default of 'core.symlinks' to false
 235:  4d6cb88aa7 = 236:  243430d0de Win32: add symlink-specific error codes
 236:  1b91465a7d = 237:  57632d42f3 Win32: mingw_unlink: support symlinks to directories
 237:  44a54a6127 = 238:  5f4670f621 Win32: mingw_rename: support renaming symlinks
 238:  6edf2c74bc = 239:  43736430d5 Win32: mingw_chdir: change to symlink-resolved directory
 239:  e3dca020d6 = 240:  c5a08a38e8 Win32: implement readlink()
 240:  1fb6980cef = 241:  7907581d77 mingw: lstat: compute correct size for symlinks
 241:  4ccafa2034 = 242:  13f9c3cebe Win32: implement basic symlink() functionality (file symlinks only)
 242:  ad4c28b99c = 243:  2ae52e1e29 Win32: symlink: add support for symlinks to directories
 243:  8c20975231 = 244:  ab0cb13a9f mingw: try to create symlinks without elevated permissions
 244:  a329b19dcb = 245:  3b3f2eaee7 mingw: emulate stat() a little more faithfully
 245:  d16a60f024 = 246:  96eacba881 mingw: special-case index entries for symlinks with buggy size
 247:  07428666e0 = 247:  e81652a146 Win32: symlink: move phantom symlink creation to a separate function
 249:  fffc3d0f67 = 248:  f41aace0ad Introduce helper to create symlinks that knows about index_state
 251:  736e5a964a = 249:  e03e332608 mingw: allow to specify the symlink type in .gitattributes
 253:  50210f9602 = 250:  1c7c614b47 Win32: symlink: add test for `symlink` attribute
 254:  ba3fbf1393 = 251:  5179f1788c mingw: explicitly specify with which cmd to prefix the cmdline
 255:  5d7e809b9f = 252:  c5293bf1eb mingw: when path_lookup() failed, try BusyBox
 256:  2925e4a0c9 = 253:  3c893a823a test-lib: avoid unnecessary Perl invocation
 257:  b42ebf502c = 254:  54fc836712 tests: replace mingw_test_cmp with a helper in C
 258:  890be0ab26 = 255:  384a82a033 test-tool: learn to act as a drop-in replacement for `iconv`
 259:  4c6fa95228 = 256:  eda1595b26 tests(mingw): if `iconv` is unavailable, use `test-helper --iconv`
 260:  3d3b1d2179 = 257:  ef1259f9db gitattributes: mark .png files as binary
 261:  202ed98bb3 = 258:  1b7ff7085e tests: move test PNGs into t/lib-diff/
 262:  7a302b45e2 = 259:  ae61ac18d5 tests: only override sort & find if there are usable ones in /usr/bin/
 263:  e9d7ea6b95 = 260:  19e4aabf8b tests: use the correct path separator with BusyBox
 264:  8652cb28fb = 261:  0180af6b71 mingw: only use Bash-ism `builtin pwd -W` when available
 265:  dd862f81d0 = 262:  195e5b9add tests (mingw): remove Bash-specific pwd option
 266:  d6b68bc554 = 263:  4bfde2d8d1 test-lib: add BUSYBOX prerequisite
 267:  7f48ae2867 = 264:  862afb7283 t0021: use Windows path when appropriate
 268:  53a605e17d = 265:  00acfb9eb0 t5003: use binary file from t/lib-diff/
 269:  f45c92e374 = 266:  dc4d659310 t5532: workaround for BusyBox on Windows
 246:  e2caff7e76 = 267:  5d30baa52a mingw: introduce code to detect whether we're inside a Windows container
 270:  d49e012ea5 = 268:  c6d211ef2d t5605: special-case hardlink test for BusyBox-w32
 248:  643aec0ed0 = 269:  f85325e57f mingw: when running in a Windows container, try to rename() harder
 271:  551b43b60b = 270:  2e95fb1222 t5813: allow for $PWD to be a Windows path
 250:  fde23a388a = 271:  9971d830fe mingw: move the file_attr_to_st_mode() function definition
 272:  82498efb59 = 272:  145e62b7da t9200: skip tests when $PWD contains a colon
 252:  070940d4c8 = 273:  b85f7c79e3 mingw: Windows Docker volumes are *not* symbolic links
 274:  8bbc0e6627 = 274:  9af2f06531 mingw: add a Makefile target to copy test artifacts
 273:  27684d181e = 275:  2db2f7873a mingw: kill child processes in a gentler way
 275:  ae508b0583 = 276:  bb5e47a579 mingw: really handle SIGINT
 276:  fece79e311 = 277:  171063be6e compat/fsmonitor/fsm-*-win32: support long paths
 277:  a9ce8bee1e = 278:  d7fa20cfe3 mingw: deprecate old-style runtime-prefix handling in interpolate_path()
 278:  bea231e862 = 279:  3897d39d92 mingw: do not call xutftowcs_path in mingw_mktemp
 279:  c31d6a082e = 280:  d865cad803 mingw: make core.fsyncObjectFiles default explicit
```

### CODE REVIEW

**Review by derrickstolee — APPROVED** [review]
Nice and easy!

**Review by dscho — APPROVED** [review]
Looks good!

**Comment by dscho** [comment]
As mentioned [on the Git mailing list](https://lore.kernel.org/git/nycvar.QRO.7.76.6.2111040007170.56@tvgsbejvaqbjf.bet/T/#u), @vdye and I got to the bottom of the build failure, and @vdye has a good plan for a fix.

**Review by derrickstolee — APPROVED** [review]
Using this version for the `microsoft/git` rebase. thanks!

**Pull request merged**
