### PR TITLE
README: add an "Open in VS Code" badge

### PR DESCRIPTION
**Pull request by dscho**
There is a neat, new feature, to open GitHub repositories quickly (remotely), and I think we should support it, too.

### CODE REVIEW

**Review by derrickstolee — APPROVED** [review]
I agree!

The even more advanced thing I was thinking about was to have an "open in codespaces" as an option, but that's a bit more work.

**Comment by dscho** [comment]
> The even more advanced thing I was thinking about was to have an "open in codespaces" as an option, but that's a bit more work.

I would _love_ to have that, but there is one really big blocker for that: Codespaces creates _Linux_ containers. In some circumstances, this does not matter because we actually develop things that are not exactly Windows-specific. But it does feel wrong to suggest editing Git _for Windows_' source code in a Linux container, where it not only cannot be tested but not even be built (for Windows, that is).

**Comment by derrickstolee** [comment]
> > The even more advanced thing I was thinking about was to have an "open in codespaces" as an option, but that's a bit more work.
> 
> I would _love_ to have that, but there is one really big blocker for that: Codespaces creates _Linux_ containers.

Yeah, such an option would be best to contribute upstream so new contributors can set up a dev environment in a codespace to get started more quickly.

**Comment by dscho** [comment]
> > > The even more advanced thing I was thinking about was to have an "open in codespaces" as an option, but that's a bit more work.
> > 
> > 
> > I would _love_ to have that, but there is one really big blocker for that: Codespaces creates _Linux_ containers.
> 
> Yeah, such an option would be best to contribute upstream so new contributors can set up a dev environment in a codespace to get started more quickly.

Right, but Codespaces is not yet generally available: https://github.com/github/roadmap/issues/55

**Pull request merged**
