### PR TITLE
DO NOT MERGE YET: make git-rebase a builtin

### PR DESCRIPTION
**Pull request by keugenek**
rebase: Introduce native rebase helper

Git rebase functionality currently implemented in the git-rebase.sh,
git-rebase--am.sh, git-rebase--interactive.sh and git-rebase--merge.sh.
Rewritten in C it will become faster and ready to integrate with other C code.

rebase--helper to be called from git-rebase.sh run_specific_rebase with
git-rebase-am, git-rebase-interactive, git-rebase-merge subcommands eliminating
above scripts one by one and then git-rebase.sh will be converted itself.

Signed-off-by: Evgeny Knyazev <evgeny.knyazev@gmail.com>

### CODE REVIEW

**Comment by keugenek** [comment]
Found error, will recreate new one

**Comment by dscho** [comment]
Please do not add a new Pull Request. Force-push into the same branch to update the Pull Request instead. I see, however, that you deleted your fork, so you simply cannot re-open this Pull Request :-(

**Comment by keugenek** [comment]
Well, I've already recreated new pull request right after closed this one. Sorry for messing it up.

**Comment by linquize** [comment]
Is such change more suitable to send to git-core team instead?

**Comment by keugenek** [comment]
@linquize, it was previously agreed in git-for-windows mailing list with @dscho that I create such stub patch to start communication around making rebase native

**Pull request closed without merging**
