### PR TITLE
Fix linkage on MinGW

### PR DESCRIPTION
**Pull request by orgads**
fscache is using NtQueryDirectoryFile, but the required library (ntoskrnl) was not linked against.

This amends commit 27a0a6f516ad9f3966a0b34d9a79f7e6a7c45ead.

### CODE REVIEW

**Comment by orgads** [comment]
Any idea why you didn't hit this problem and I did? I have the most up-to-date packages from GfW repo, and building inside mingw64 environment using just `make`.

**Comment by orgads** [comment]
Apparently caused by https://github.com/git-for-windows/git/issues/2081

**Comment by dscho** [comment]
> Apparently caused by #2081

Hmm. I don't quite understand what the MSYS2 runtime has to do with the MINGW64 linking...

**Comment by orgads** [comment]
`uname` is called in `config.mak.uname`, and because it returns wrong values, then the platform is mis-detected.

**Pull request closed without merging**
