### PR TITLE
Use the pre-built vcpkg packages in the vs-build(arm64) job

### PR DESCRIPTION
**Pull request by dscho**
This should shave off about 16 minutes off of our PR builds.

### CODE REVIEW

**Comment by rimrul** [comment]
We should probably extend `vs-test` to also cover `arm64`. Can't have that much time saved.

**Comment by rimrul** [comment]
Scratch that. Github actions do not currently support ARM64 Windows.
See also actions/virtual-environments#768 and actions/runner#785

**Comment by dscho** [comment]
@rimrul good find. And yes, I am aware that neither Azure Pipelines nor GitHub Actions offer Windows/ARM64 agents at the moment.

@rimrul may I take your taking time to comment as approval for this PR?

**Comment by rimrul** [comment]
Yes.

[X] less unnescessary waiting
[X] fewer unnescessary differences between the VS builds for AMD64 and ARM64
[X] the CI builds still pass
[X] no obvious downsides

That's an improvement in my books.

**Pull request merged**
