### PR TITLE
Improve the default user name & email logic

### PR DESCRIPTION
**Pull request by dscho**
The concept of using `getpwuid()` is slightly incompatible with the design of the related functions in the Win32 API. While it *does* have a way to provide the user's display name (which is called "gecos"), there is no POSIX function to obtain the email address of the current user.

So let's work a little bit harder to provide sensible defaults.

### CODE REVIEW

**Comment by dscho** [comment]
Cc @lutzroeder

**Comment by dscho** [comment]
Oh @buildhive! I tested with Linux locally and it works without problems. That test case is completely unrelated to the changes in this Pull Request, anyway.

So I only await the comments of @lutzroeder before merging...

**Comment by dscho** [comment]
> Should USER_EMAIL be called USER_PRINCIPAL_NAME as this is what is actually querying?

Personally, I find the name `USER_PRINCIPAL_NAME` referring to the user's email address perfectly confusing :stuck_out_tongue_winking_eye: 

> if we stick with EXTENDED_NAME_FORMAT (name of the Windows enum) it should use similar/same names to avoid confusion?

I guess you're right. I need to use `NameUserPrincipal` and `NameDisplay` instead. Even if they are not exactly intuitive names, they should match the original definition.

**Comment by dscho** [comment]
And now I made it so. @lutzroeder could you have another look, please?

**Comment by lutzroeder** [comment]
Looks good

**Comment by dscho** [comment]
Thanks!

**Pull request merged**
