### PR TITLE
.github: build vs-build with NO_GETTEXT

### PR DESCRIPTION
**Pull request by dennisameling**
As discussed in https://github.com/git-for-windows/git/pull/3017#issuecomment-775501426, removes the dependency on `git-sdk-64-minimal` in `vs-build` by changing to `NO_GETTEXT`.

### CODE REVIEW

**Comment by dscho** [comment]
Hmm. [It looks as if we require `make.exe`, still](https://github.com/git-for-windows/git/runs/1880045325), if only to bundle the build artifacts...

> ```
>   & git-sdk-64-minimal\usr\bin\bash.exe -lc @"
>    mkdir -p artifacts &&
>    eval \"`$(make -n artifacts-tar INCLUDE_DLLS_IN_ARTIFACTS=YesPlease ARTIFACTS_DIRECTORY=artifacts 2>&1 | grep ^tar)\"
>  "@
> ```

How about using the same `cache` trick you provided for the `git-artifacts.yml` workflow, just for `git-sdk-64-minimal`?

**Comment by dennisameling** [comment]
Will have a look at this tomorrow towards the end of the day!

**Comment by dscho** [comment]
> 
> 
> Will have a look at this tomorrow towards the end of the day!

Actually, I thought about it, and it might be a perfect time to get a GitHub Action started for that. Let me try that.

**Comment by dscho** [comment]
> [...] it might be a perfect time to get a GitHub Action started for that. Let me try that.

Took long enough: https://github.com/git-for-windows/setup-git-for-windows-sdk. It does not yet implement caching, but I think that'll be next.

**Comment by dennisameling** [comment]
_Very_ fancy, love it! 🚀 Let me try 👀

**Comment by dscho** [comment]
> 
> 
> _Very_ fancy, love it! 🚀 Let me try 👀

Are you familiar with Typescript, Jest & Mocking? I would _love_ to have somebody look over this (I have a feeling that this is hodgepodge code, and could be done much more elegantly): https://github.com/git-for-windows/setup-git-for-windows-sdk/blob/f6f78470e56fadd03f2175101f627aacd6362602/__tests__/downloader.test.ts#L51-L77

**Comment by dscho** [comment]
> It does not yet implement caching, but I think that'll be next.

Here it is: https://github.com/git-for-windows/setup-git-for-windows-sdk/pull/8

**Comment by dennisameling** [comment]
> I have a feeling that this is hodgepodge code, and could be done much more elegantly

Done in https://github.com/git-for-windows/setup-git-for-windows-sdk/pull/11 😊 hope that helps!

**Comment by dscho** [comment]
The good news: I cherry-picked this commit into https://github.com/gitgitgadget/git/pull/878. The bad news: the Action does not yet do what it is supposed to do...

**Comment by dennisameling** [comment]
Just added your shiny new GH Action in https://github.com/git-for-windows/git/pull/3040/commits/ef908c3caac1ce1366df5433dc2488785019ff5b and it seems to work: https://github.com/git-for-windows/git/pull/3040/checks?check_run_id=1928729677

**Comment by dscho** [comment]
What would you think of force-pushing gitgitgadget/git#878's branch to this PR, since it essentially includes your work (but splits concerns into multiple commits, and also adds additional speed-ups)?

**Comment by dscho** [comment]
> What would you think of force-pushing [gitgitgadget#878](https://github.com/gitgitgadget/git/pull/878)'s branch to this PR, since it essentially includes your work (but splits concerns into multiple commits, and also adds additional speed-ups)?

@dennisameling if you're okay with going forward with this, I can do it for you... I just don't want to step on your toes.

**Comment by dennisameling** [comment]
Hi @dscho, I've been swamped with work in the last days, sorry. Please, if you have time, feel free to go ahead with this one 😊 I hope to have some time during the weekend as well if that helps!

**Comment by dennisameling** [comment]
@dscho I think it's easier to just close this PR and create a new one from your branch https://github.com/dscho/git/tree/use-setup-git-for-windows-sdk-action. What do you think? Please feel free to close this one 👍🏼

**Comment by dennisameling** [comment]
Force-pushing the other branch onto this one worked (had to check some docs on how to do that - `git push origin --force dscho/use-setup-git-for-windows-sdk-action:vs-build-no-gettext`).

Then there obviously was a conflict in `main.yml`, which I resolved in https://github.com/git-for-windows/git/pull/3040/commits/fc590b3584573908de3055d0a7a040838c80f0a6 by doing `git merge upstream/main` and then fixing the conflict. Hope that's okay!

**Comment by dscho** [comment]
Excellent, thank you so much!

> Then there obviously was a conflict in `main.yml`, which I resolved in [fc590b3](https://github.com/git-for-windows/git/commit/fc590b3584573908de3055d0a7a040838c80f0a6) by doing `git merge upstream/main` and then fixing the conflict. Hope that's okay!

Yes, of course, especially since it looks as if you didn't need the merge commit after all.

**Pull request merged**
