### PR TITLE
git-wrapper: case-insensitive path comparison

### PR DESCRIPTION
**Pull request by vitalyster**

### CODE REVIEW

**Comment by dscho** [comment]
Thanks!

**Comment by dscho** [comment]
Oh, one other thing... @vitalyster would you be okay with me adding your "Signed-off-by:" to testify that you are entitled to contribute this patch? I would like to send this patch upstream eventually, and they require that statement.

**Comment by vitalyster** [comment]
Okay. Is something needed from me? I'm not familiar with signed-off commits

**Comment by dscho** [comment]
Well, I will need your statement "Yes, I have all rights to contribute this patch", which is essentially what all those "Signed-off-by" lines in the Git history are all about.

**Comment by vitalyster** [comment]
Looking at http://git.kernel.org/cgit/git/git.git/tree/Documentation/SubmittingPatches?id=HEAD#n246 I choose (a) :)

**Comment by dscho** [comment]
Cool, thanks!

**Pull request merged**
