### PR TITLE
Rebase to v2.33.0

### PR DESCRIPTION
**Pull request by dscho**
Range-diff relative to `main`:

```diff
   1:  d1941cd70cd =   1:  6e34e54050c t9350: point out that refs are not updated correctly
   2:  aeff77769ba =   2:  158907ceb87 transport-helper: add trailing --
   3:  7c4646e7018 =   3:  f189282dcfc remote-helper: check helper status after import/export
   4:  afed4e7ca05 =   4:  f070e35da86 mingw: demonstrate a problem with certain absolute paths
   5:  3600f30fab7 =   5:  fc0e515ba1e archive: replace write_or_die() calls with write_block_or_die()
   6:  5e4f8ec1a44 =   6:  2e004e4a398 gitk: prevent overly long command lines
   8:  c64cc7d66aa =   7:  0221569db1c Always auto-gc after calling a fast-import transport
   9:  59bb1cf4dc7 =   8:  ecf7f0d78b9 mingw: allow absolute paths without drive prefix
  10:  40c063fb720 =   9:  8716f7dd490 mingw: handle absolute paths in expand_user_path()
  11:  cc3338ab5d4 =  10:  3b9f65ddf18 archive: avoid spawning `gzip`
  12:  e4be86c5a30 =  11:  409cae91eb7 mingw: change core.fsyncObjectFiles = 1 by default
  13:  ca5dfedf854 =  12:  904dc67d906 gitk: Escape file paths before piping to git log
  32:  96851e0dba3 =  13:  6889d057177 mingw: demonstrate a `git add` issue with NTFS junctions
   7:  e78c33356f1 =  14:  432b3154413 clean: do not traverse mount points
  34:  03eb7aed080 =  15:  c735978159d strbuf_realpath(): use platform-dependent API if available
  14:  1b93e9bc5e8 =  16:  379fe49ce4c clean: remove mount points when possible
  15:  1ce9589a343 =  17:  5e28151f0ec mingw: include the Python parts in the build
  16:  e1c1f20db0d =  18:  003f50c0545 Config option to disable side-band-64k for transport
  38:  00025282daf =  19:  6e2adf4721e mingw: make sure `errno` is set correctly when socket operations fail
  39:  42f7bd0b7e6 =  20:  134a05639a7 mingw: do resolve symlinks in `getcwd()`
  40:  7325995571d =  21:  99629cb6636 mingw: fix fatal error working on mapped network drives on Windows
  41:  c16ee02e038 =  22:  b876fea722d clink.pl: fix MSVC compile script to handle libcurl-d.lib
  17:  4ebae431888 =  23:  0d465cf4154 mingw: ensure valid CTYPE
  18:  85c2f61050b =  24:  cf4459343a5 vcxproj: unclash project directories with build outputs
  19:  5c779e95d0f =  25:  9f337d26ec6 mingw: allow `git.exe` to be used instead of the "Git wrapper"
  20:  2fb6dbfb329 =  26:  4eb35c79dbb t5505/t5516: allow running without `.git/branches/` in the templates
  21:  e6dd54e2cb3 =  27:  27f4215a769 mingw: ignore HOMEDRIVE/HOMEPATH if it points to Windows' system directory
  35:  9dcce9f56c1 =  28:  896f959a01a Allow `add -p` and `add -i` with a large number of files
  22:  1389ee83c8b =  29:  c0d57820a52 t5505/t5516: fix white-space around redirectors
  23:  2f0e837731c =  30:  8efa52f5967 tests: exercise the RUNTIME_PREFIX feature
  37:  382f6bef992 =  31:  88de6b82cc4 http: use new "best effort" strategy for Secure Channel revoke checking
  42:  0e7927b4f34 =  32:  fcb281d7f2d mingw: implement a platform-specific `strbuf_realpath()`
  43:  98900a396b3 =  33:  2ad88237bed t3701: verify that we can add *lots* of files interactively
  44:  ec99d80aab0 =  34:  968faba67fd git add -i: handle CR/LF line endings in the interactive input
  45:  2913fcc2f76 =  35:  85baeaf82b9 commit: accept "scissors" with CR/LF line endings
  24:  266f3aa22c1 =  36:  493e33ea166 clink.pl: fix libexpatd.lib link error when using MSVC
  25:  7c6a9659e49 =  37:  d225b8d9cc3 Makefile: clean up .ilk files when MSVC=1
  26:  1f2f630cf68 =  38:  b6a63defec9 vcbuild: add support for compiling Windows resource files
  27:  21a343b5a8b =  39:  f11a12831c0 config.mak.uname: add git.rc to MSVC builds
  28:  53690669ad8 =  40:  10ded59193a clink.pl: ignore no-stack-protector arg on MSVC=1 builds
  29:  c1fc640821f =  41:  04e077d10d0 clink.pl: move default linker options for MSVC=1 builds
  30:  948d9cfaeb7 =  42:  49b4c9c3d2e buildsystems: remove duplicate clause
  31:  78a104ae904 =  43:  50fc145b7cb vcxproj: handle resource files, too
  33:  2b1896f32f8 =  44:  a788112422f vcxproj: ignore -fno-stack-protector and -fno-common
  36:  f8faf304340 =  45:  d1019842d69 vcxproj: handle GUI programs, too
  77:  69bf72c5f94 =  46:  e4148a1b349 win32: add a helper to run `git.exe` without a foreground window
  46:  3876486b412 =  47:  3ecf225ed6a t0014: fix indentation
  47:  4ab5cb0616d =  48:  6bd7e02351d git-gui: accommodate for intent-to-add files
  48:  280bad8a63e =  49:  9eba813a1d1 Add a GitHub workflow to generate Git for Windows' Pacman package
  49:  bd5c09d5877 =  50:  14ee5f181ff git-artifacts: if GPG secrets are available, use them
  58:  50512fc8ba0 =  51:  d51b83cf8c9 vcpkg_install: detect lack of Git
  50:  b1e53631317 =  52:  72c57264514 git-artifacts: also code-sign, if configured via the secrets
  60:  c001eb38e00 =  53:  c120e2a28e9 vcpkg_install: add comment regarding slow network connections
  51:  a9e9f5c92c5 =  54:  5271fc5179c git-artifacts: also build the installer
  62:  ecb73a9d4ca =  55:  f81c40f0a3f vcxproj: support building Windows/ARM64 binaries
  52:  3b222b34ea0 =  56:  8b60e143015 git-artifacts: also build portable, mingit and mingit-busybox
  64:  ffa020cac61 =  57:  f60779f0c5e vcbuild: install ARM64 dependencies when building ARM64 binaries
  53:  fd5c09e23b7 =  58:  ae06c57c7fe git-artifacts: also build 32-bit versions
  66:  ea858046610 =  59:  04ad761c165 vcbuild: add an option to install individual 'features'
  54:  cc1a246530e =  60:  dc4c23f8f88 git-artifacts: also build the nuget package
  68:  f7069924960 =  61:  b78e2d18de9 cmake: allow building for Windows/ARM64
  55:  33cea97679c =  62:  4b0f57f9b51 git-artifacts: allow restricting which artifacts are built
  70:  a45d6ad86e0 =  63:  4146dec51c6 ci(vs-build) also build Windows/ARM64 artifacts
  56:  55070bc40be =  64:  558c8013803 git-artifacts: allow specifying repo/ref via workflow_dispatch
  72:  802bfcae210 =  65:  918bdd05e95 Add schannel to curl installation
  78:  86259a88962 =  66:  571b378cb8b git maintenance: avoid console window in scheduled tasks on Windows
  57:  6b7c0e39ccf =  67:  9df13c8b0ef git-artifacts: cache the build-installers artifact
  59:  0953f81d3aa =  68:  5e1c9b38530 git-artifacts: use the cached build-installers instead of makepkg-git
  61:  5fafd5ca9a1 =  69:  90fd5c4786d git-artifacts: add ARM64 artifacts
  63:  d9f73cac9e1 =  70:  e120e7ee42c git-artifacts(arm64): avoid hard-linking the dashed built-ins
  65:  bffa3780f6d =  71:  62cc9843161 git-artifacts: use a narrower `PATH`
  67:  352dd79e1d5 =  72:  638a027aab2 git-artifacts: fix BUILD_ONLY handling for ARM64
  69:  f5d86bdd366 =  73:  81986ca4cf7 git-artifacts: extend the `SKIP` logic to handle `pkg` and `build-arm64`
  71:  043be7237a9 =  74:  c7bb8dc553c git-artifacts: mark all inputs as "not required"
  73:  5291f874e2b =  75:  d5e623f7369 git-artifacts(build-arm64): build artifacts using the intended Git revision
  74:  2cd18b1000c =  76:  c12b62b0088 git-artifacts: add workaround for GCM Core on ARM64
  75:  46fba48be1d =  77:  dea98a56905 cmake(): allow setting HOST_CPU for cross-compilation
  76:  8c76315caf2 =  78:  1046ebe7c12 git-artifacts: Use the shiny new setup-git-for-windows-sdk Action
  79:  a5b31307bb1 =  79:  467ddc982da ci(): add HOST_CPU to CMake command
  83:  e2afd89c75d =  80:  15b44c3f216 simple-ipc: preparations for supporting binary messages.
  84:  b947599c1bb =  81:  e3e590dbc75 fsmonitor--daemon: man page
  85:  a904d5c8eee =  82:  5641d51b02f fsmonitor--daemon: update fsmonitor documentation
  86:  f753538605b =  83:  a2f5482b4e8 fsmonitor-ipc: create client routines for git-fsmonitor--daemon
  87:  a9e0aa0c393 =  84:  bd7a1410d34 help: include fsmonitor--daemon feature flag in version info
  88:  a3a2f2c7eb5 =  85:  81f7337e3dc fsmonitor: config settings are repository-specific
  89:  f3221531b3f =  86:  abc1c46df9f fsmonitor: use IPC to query the builtin FSMonitor daemon
  90:  d0e88e90af6 =  87:  b441b3720ed fsmonitor--daemon: add a built-in fsmonitor daemon
  91:  5f2ac85f159 =  88:  1866a62b4f5 fsmonitor--daemon: implement 'stop' and 'status' commands
  92:  fd12b6a251c =  89:  f6e27d05bc9 t/helper/fsmonitor-client: create IPC client to talk to FSMonitor Daemon
  93:  7d8978d5d15 =  90:  1b42506abac fsm-listen-win32: stub in backend for Windows
  94:  9314d96cdbc =  91:  a6784cb3784 fsm-listen-darwin: stub in backend for Darwin
  95:  606f7ce591e =  92:  7d39bbb344b fsmonitor--daemon: implement 'run' command
  96:  e284650b7b5 =  93:  f5c5085496b fsmonitor--daemon: implement 'start' command
  80:  b2e37c46c94 =  94:  11f3d271c30 ci(vs-build): download the vcpkg artifacts using a dedicated Action
  81:  179555c8081 =  95:  34fc8ef403b mingw: allow for longer paths in `parse_interpreter()`
  82:  6c61017da71 =  96:  15acb6178a0 compat/vcbuild: document preferred way to build in Visual Studio
  97:  dfd0064a444 =  97:  eab07e13cc2 fsmonitor--daemon: do not try to operate on bare repos
  98:  60f66dd1a4d =  98:  89265708a0b fsmonitor--daemon: add pathname classification
  99:  79de750e976 =  99:  13cf2b39447 fsmonitor--daemon: define token-ids
 100:  ee46de05f03 = 100:  68a4ae60326 fsmonitor--daemon: create token-based changed path cache
 101:  323d85e5b2b = 101:  a25a759709a fsm-listen-win32: implement FSMonitor backend on Windows
 102:  2c3fca62184 = 102:  ccc75e26a14 fsm-listen-darwin: add macos header files for FSEvent
 103:  9ce9383e42e = 103:  8657519ee51 fsm-listen-darwin: implement FSEvent listener on MacOS
 104:  f7cb04c0faf = 104:  d0ed68b4a1f fsmonitor--daemon: implement handle_client callback
 105:  60d4560299a = 105:  fd9522aa9ba t/helper/test-chmtime: skip directories on Windows
 106:  14e49154208 = 106:  b34d252c709 t/perf/p7519: speed up test on Windows
 107:  6e42373b2a0 = 107:  5ab490f926b t/perf: avoid copying builtin fsmonitor files into test repo
 108:  7f26f351a85 = 108:  41b215e19af t/perf/p7519: add fsmonitor--daemon test cases
 109:  fff6146c287 = 109:  8318d7dec0a t7527: create test for fsmonitor--daemon
 110:  871d66e9a66 = 110:  20eea488e8f fsmonitor--daemon: periodically truncate list of modified files
 111:  3fc7c9c5eca = 111:  0de22628c59 fsmonitor--daemon: use a cookie file to sync with file system
 112:  90bf2497658 = 112:  76408441581 fsmonitor: enhance existing comments
 113:  3c13f56004c = 113:  ec3dfa64cc1 fsmonitor: force update index after large responses
 114:  9281ec82ced = 114:  27846ccfc58 t7527: test status with untracked-cache and fsmonitor--daemon
 115:  47b34968b1e = 115:  0fadc91ae49 fsmonitor: handle shortname for .git
 116:  ff30dbdb945 = 116:  207eece649a t7527: test FS event reporing on MacOS WRT case and Unicode
 117:  371bd5918a5 = 117:  0f46db7c01a t7527: test builtin FSMonitor watching repos with unicode paths
 118:  ab034678abc = 118:  751d7c39ddb t/helper/fsmonitor-client: create stress test
 119:  6e20d33c548 = 119:  ddab099c559 ipc-win32: add trace2 debugging
 120:  d0343755728 = 120:  56b6c9aa992 fsmonitor-settings: stub in platform-specific incompatibility checking
 121:  3a3746703ab = 121:  7b37f49707b fsmonitor-settings: virtual repos are incompatible with FSMonitor
 122:  3a1b1cecf4c = 122:  e3fc6efce38 fsmonitor--daemon: background daemon must free the console on windows
 123:  f93eb4100df = 123:  7b8c024f511 fsmonitor-settings: stub in platform-specific incompatibility checking on MacOS
 124:  c0a805e66f2 = 124:  da396b62982 fsmonitor-settings: remote repos on MacOS are incompatible with FSMonitor
 125:  73067d5df30 = 125:  a002e816f2a fsmonitor-settings: remote repos on Windows are incompatible with FSMonitor
 126:  6554f23bc7d = 126:  63d2d7bb4a2 fsmonitor: mark the built-in FSMonitor as experimental
 127:  629f4e67bba = 127:  3bcb1a2f29a Enable the built-in FSMonitor as an experimental feature
 128:  d73b3e99896 = 128:  cc84746ae5b http: optionally send SSL client certificate
 243:  60003bac2a3 = 129:  93b402967b2 subtree: update `contrib/subtree` `test` target
 244:  abf831b5fa5 = 130:  4759da4d759 ci: run `contrib/subtree` tests in CI builds
 129:  271c7bfca65 = 131:  bd68b55eb92 Win32: make FILETIME conversion functions public
 130:  706cce4939e = 132:  cc5abf3a3ce Win32: dirent.c: Move opendir down
 131:  ce3bc52b72b = 133:  40e42138559 mingw: make the dirent implementation pluggable
 132:  01f783d1a7d = 134:  c95d6e65bf7 Win32: make the lstat implementation pluggable
 133:  ad4e01447f1 = 135:  b92364d9c4a add infrastructure for read-only file system level caches
 134:  16b32613732 = 136:  39149f72f44 mingw: add a cache below mingw's lstat and dirent implementations
 135:  6e0d2fde4cb = 137:  375e03b8144 fscache: load directories only once
 136:  da772c171d6 = 138:  00689f77375 fscache: add key for GIT_TRACE_FSCACHE
 137:  975ab749863 = 139:  07894b1bda8 fscache: remember not-found directories
 138:  8c8a11ca194 = 140:  332b7e5b52b fscache: add a test for the dir-not-found optimization
 139:  b235d9547d7 = 141:  dc21f40e56d add: use preload-index and fscache for performance
 140:  7dc3a4883cf = 142:  13183f66761 dir.c: make add_excludes aware of fscache during status
 141:  593de4c256b = 143:  3db9cef9c7d fscache: make fscache_enabled() public
 142:  4ebb9b5fb51 = 144:  c5bf291237e dir.c: regression fix for add_excludes with fscache
 143:  c496872adc7 = 145:  e3d1b63b161 fetch-pack.c: enable fscache for stats under .git/objects
 144:  f4e25638b5d = 146:  232ebfa223c checkout.c: enable fscache for checkout again
 145:  f875f4b67ce = 147:  63620296936 Enable the filesystem cache (fscache) in refresh_index().
 146:  b859c15a742 = 148:  98ccd0043a3 fscache: use FindFirstFileExW to avoid retrieving the short name
 147:  8df00b28fe6 = 149:  fd9d280871b status: disable and free fscache at the end of the status command
 148:  b60c29a2867 = 150:  ed404edda32 fscache: add GIT_TEST_FSCACHE support
 149:  0209d9ce5ab = 151:  18d00258c0c fscache: add fscache hit statistics
 150:  6aab823053c = 152:  b358145995b mem_pool: add GIT_TRACE_MEMPOOL support
 151:  0d4f6eee364 = 153:  6bbb0a58991 fscache: fscache takes an initial size
 152:  4d974b30a38 = 154:  a67b953e438 fscache: update fscache to be thread specific instead of global
 153:  8ec0563c806 = 155:  be310618241 fscache: teach fscache to use mempool
 154:  22dd474c679 = 156:  631dd3f3d01 fscache: make fscache_enable() thread safe
 156:  a1e88851487 = 157:  71a42798f60 fscache: teach fscache to use NtQueryDirectoryFile
 155:  aaf5e3047bb = 158:  9354370d095 git-gui: provide question helper for retry fallback on Windows
 157:  1905acd18b0 = 159:  df4dbab7fc8 git gui: set GIT_ASKPASS=git-gui--askpass if not set yet
 158:  cf8bdbcfa66 = 160:  46da4fab880 unpack-trees: enable fscache for sparse-checkout
 160:  4fced7cca45 = 161:  194082e2584 git-gui--askyesno: fix funny text wrapping
 161:  503423b9e9d = 162:  cb143e12b92 fscache: remember the reparse tag for each entry
 163:  3f0d7c4f1a0 = 163:  1829cb8bfe3 git-gui--askyesno: allow overriding the window title
 164:  54e2a2e68ac = 164:  3329a58463a fscache: implement an FSCache-aware is_mount_point()
 165:  3096f0c6510 = 165:  06b638d8ded respect core.hooksPath, falling back to .git/hooks
 167:  48ba17ba258 = 166:  8a19601d42c git-gui--askyesno (mingw): use Git for Windows' icon, if available
 168:  d113ec1b645 = 167:  7fc0b64c7cc clean: make use of FSCache
 159:  c9ceabd549c = 168:  cb34179f409 gitk: Unicode file name support
 162:  3c36a17fdb1 = 169:  047e3cbb9f4 gitk: Use an external icon file on Windows
 166:  5c12b10992b = 170:  fcaf4614e32 gitk: fix arrow keys in input fields with Tcl/Tk >= 8.6
 169:  385efe9badf = 171:  8647725bdc3 gitk: make the "list references" default window width wider
 170:  1456313f023 = 172:  2d725f225e0 pack-objects (mingw): demonstrate a segmentation fault with large deltas
 171:  5eb8d3a8aa6 = 173:  64da6f21825 mingw: support long paths
 172:  538f855d55d = 174:  d20fa02250c Win32: fix 'lstat("dir/")' with long paths
 173:  cb0a23990e9 = 175:  fc948a4da4c mingw: ensure that core.longPaths is handled *always*
 174:  22664abd34b = 176:  8bbc80a2f7e mingw: Support `git_terminal_prompt` with more terminals
 175:  f79e0dafb6b = 177:  e58a8c6ab9d compat/terminal.c: only use the Windows console if bash 'read -r' fails
 176:  1815b67a73c = 178:  f6d4ef49d9b mingw (git_terminal_prompt): do fall back to CONIN$/CONOUT$ method
 177:  590ad48cf3c = 179:  16cf4533a01 Unbreak interactive GPG prompt upon signing
 178:  9e69eba932f = 180:  d8b1fdbb102 strbuf_readlink: don't call readlink twice if hint is the exact link size
 179:  c94804dc169 = 181:  af6584d4818 strbuf_readlink: support link targets that exceed PATH_MAX
 180:  063d3750d24 = 182:  4cb604183da lockfile.c: use is_dir_sep() instead of hardcoded '/' checks
 181:  a2dd9a7c712 = 183:  49ddf83e2b3 Win32: don't call GetFileAttributes twice in mingw_lstat()
 182:  4dd588ccb03 = 184:  8e5e6422aeb Win32: implement stat() with symlink support
 183:  d0e0a2db3a5 = 185:  46913db96f9 Win32: remove separate do_lstat() function
 184:  95c6a85df74 = 186:  346ee4b505c Win32: let mingw_lstat() error early upon problems with reparse points
 185:  ed94b366148 = 187:  a3e0701abee mingw: teach fscache and dirent about symlinks
 186:  f89fa191ed2 = 188:  602ddfa7056 Win32: lstat(): return adequate stat.st_size for symlinks
 187:  48d100ac9bd = 189:  2e061b527ab Win32: factor out retry logic
 188:  c0210b4bb65 = 190:  accc9a5566e Win32: change default of 'core.symlinks' to false
 189:  912647584d1 = 191:  6f42d3c5b91 Win32: add symlink-specific error codes
 190:  fbfc1f1ffc7 = 192:  3a212768ef0 Win32: mingw_unlink: support symlinks to directories
 191:  c9fbd0fad27 = 193:  04116c6fb6b Win32: mingw_rename: support renaming symlinks
 192:  f0d5f0a0384 = 194:  dfd50377108 Win32: mingw_chdir: change to symlink-resolved directory
 193:  9d9c8cb1009 = 195:  d28caf09c73 Win32: implement readlink()
 194:  be523844525 = 196:  2d445b7fa8f mingw: lstat: compute correct size for symlinks
 195:  b345273e9ed = 197:  d6cdafff3f6 Win32: implement basic symlink() functionality (file symlinks only)
 196:  314393a1d6b = 198:  6bd9c8e02b6 Win32: symlink: add support for symlinks to directories
 197:  34def60b680 = 199:  32ccf8e094b mingw: try to create symlinks without elevated permissions
 198:  fded3a7a451 = 200:  55060fa3f39 mingw: emulate stat() a little more faithfully
 199:  f358c3e730c = 201:  b487ad175c7 mingw: special-case index entries for symlinks with buggy size
 200:  559658c123d = 202:  777c01e8322 Win32: symlink: move phantom symlink creation to a separate function
 201:  f822e1febd6 = 203:  0fb3908161d Introduce helper to create symlinks that knows about index_state
 202:  d879607e728 = 204:  f116920dc72 mingw: allow to specify the symlink type in .gitattributes
 203:  e4b438a8e7d = 205:  7bf6c747432 Win32: symlink: add test for `symlink` attribute
 204:  77e6c715d2c = 206:  7a578347638 mingw: explicitly specify with which cmd to prefix the cmdline
 221:  5ed48106d77 = 207:  2b4bf3501e9 mingw: introduce code to detect whether we're inside a Windows container
 205:  f976886a1e4 = 208:  82f50e22d97 mingw: when path_lookup() failed, try BusyBox
 223:  5972feb84c9 = 209:  481741d01d6 mingw: when running in a Windows container, try to rename() harder
 206:  83cdac1fa71 = 210:  427a02510ea test-lib: avoid unnecessary Perl invocation
 225:  f1c6e585bd6 = 211:  9e7403b1929 mingw: move the file_attr_to_st_mode() function definition
 207:  d3c541f610a = 212:  cd49051c5bf tests: replace mingw_test_cmp with a helper in C
 229:  3c0a902ccc3 = 213:  daeb0d14ee3 mingw: Windows Docker volumes are *not* symbolic links
 208:  19fdd7953ba = 214:  c238b1c55d2 test-tool: learn to act as a drop-in replacement for `iconv`
 209:  87fcf646123 = 215:  335d6011316 tests(mingw): if `iconv` is unavailable, use `test-helper --iconv`
 210:  aff0e58138d = 216:  6010e2206a8 tests: use t/lib-diff/* consistently
 211:  cffb1f9a924 = 217:  89affffb31d gitattributes: mark .png files as binary
 212:  c567bf280cb = 218:  d48928d0c37 tests: move test PNGs into t/lib-diff/
 213:  60bce140c43 = 219:  70fd6a7ce4b tests: only override sort & find if there are usable ones in /usr/bin/
 214:  ffe29a10b82 = 220:  0fac8c16f76 tests: use the correct path separator with BusyBox
 215:  7b0c52c357f = 221:  e21503c0a66 mingw: only use Bash-ism `builtin pwd -W` when available
 216:  fcccf360a47 = 222:  a8cd46e5b7f tests (mingw): remove Bash-specific pwd option
 217:  b7523ea91f4 = 223:  9bab197d832 test-lib: add BUSYBOX prerequisite
 218:  b63366649b7 = 224:  5ddcb65bc06 t0021: use Windows path when appropriate
 219:  2525029e4af = 225:  9da9c7f7988 t5003: use binary file from t/lib-diff/
 220:  cf7502514a3 = 226:  6bac98919a3 t5532: workaround for BusyBox on Windows
 222:  a13e74df159 = 227:  05185348c67 t5605: special-case hardlink test for BusyBox-w32
 224:  6932b00a0ed = 228:  23982ca731b t5813: allow for $PWD to be a Windows path
 226:  b01c651c553 = 229:  81faead10fc t9200: skip tests when $PWD contains a colon
 227:  ee15b06f8e6 = 230:  9b7249d142f mingw: kill child processes in a gentler way
 228:  e314be940b6 = 231:  733f4d10324 status: carry the --no-lock-index option for backwards-compatibility
 230:  2ca17e6e164 = 232:  49b7755cd38 mingw: add a Makefile target to copy test artifacts
 231:  d23a10add7e = 233:  4b1d17dac15 mingw: really handle SIGINT
 232:  45ad1f47f3d = 234:  0b5bd988e88 status: reinstate --show-ignored-directory as a deprecated option
 234:  1e5d88039b7 = 235:  5d05386bea6 Modify the Code of Conduct for Git for Windows
 235:  db453d13d88 = 236:  4668f982e38 CONTRIBUTING.md: add guide for first-time contributors
 236:  b044e084b61 = 237:  083f3f2f027 README.md: Add a Windows-specific preamble
 237:  adba228dc0c = 238:  2b6efaa85a4 Add an issue template
 238:  cf65a9306af = 239:  fd47bb62edc Modify the GitHub Pull Request template (to reflect Git for Windows)
 239:  5b51622ec6f = 240:  cabd26a3e5c .github: Add configuration for the Sentiment Bot
 240:  4d661112b7f = 241:  77ff80a8f6b Document how $HOME is set on Windows
 233:  515fc17384b = 242:  4e46eb2071b reset: reinstate support for the deprecated --stdin option
 241:  6ffc888f2ab = 243:  71566e2f513 Add a GitHub workflow to monitor component updates
 242:  a49e9f3adfa = 244:  550ab5ca2c1 SECURITY.md: document Git for Windows' policies
```

### CODE REVIEW

**Review by derrickstolee — APPROVED** [review]
Looks like whitespace failures in the translation layers. I guess we force through them?

**Comment by dscho** [comment]
For the record: I need to rebuild `gnupg` first (I accepted a last-minute, supposedly minimal PR, and the PR itself is fine, but the Azure Pipeline fails to build due to those dreaded 32-bit issues with Perl's `Cwd.dll`). This will have to wait for tomorrow.

**Comment by web2033** [comment]
I'm reading the announcement and wondering where it is, now I see...
https://github.blog/2021-08-16-highlights-from-git-2-33/

**Comment by dscho** [comment]
> Looks like whitespace failures in the translation layers. I guess we force through them?

Yes. There is nothing we can do about those commits, they have been accepted into the localization maintainer's fork as-are, and we cannot change them now. The `check-whitespace` build has no way of knowing that it's not our fault ;-)

**Pull request merged**
