### PR TITLE
Replace the FSMonitor v1 patches with v2

### PR DESCRIPTION
**Pull request by dscho**
This PR takes it straight from gitgitgadget/git#923

### CODE REVIEW

**Comment by dscho** [comment]
I had a quick read through the (massive) diff, and it looks good to me! Thanks @jeffhostetler!!!

**Review by jeffhostetler — APPROVED** [review]
This looks good.  Thanks for pulling it in!

**Comment by jeffhostetler** [comment]
I'm going to take a look at the restart stuff this morning and try to get you another commit to put on top of this.

**Comment by dscho** [comment]
@derrickstolee have you seen [this failure in `t1092`](https://github.com/git-for-windows/git/pull/3234/checks?check_run_id=2652104508#step:5:3271) before? It looks a bit as if the progress display mismatches (because there is a `-` in front of the 80% report, which might indicate a slow machine), but the hunk header `@@ -1 0,0 @@` would disagree that the progress is the culprit: it would expect one line but got none instead (it really looks quite puzzling to me)...

**Comment by derrickstolee** [comment]
> @derrickstolee have you seen [this failure in `t1092`](https://github.com/git-for-windows/git/pull/3234/checks?check_run_id=2652104508#step:5:3271) before? It looks a bit as if the progress display mismatches (because there is a `-` in front of the 80% report, which might indicate a slow machine), but the hunk header `@@ -1 0,0 @@` would disagree that the progress is the culprit: it would expect one line but got none instead (it really looks quite puzzling to me)...

That's absolutely a slowness issue. The diff hunk is saying "one line removed, starting at line zero on both sides". The context shows that two lines did match: the first `(5/5)` and then the subsequent `(5/5), done.` lines.

The solution is to make the progress deterministic with `GIT_PROGRESS_DELAY=0`. I'll get a commit going.

**Comment by dscho** [comment]
> 
> 
> I'm going to take a look at the restart stuff this morning and try to get you another commit to put on top of this.

Or maybe we just do this on top, and merge this here PR first?

**Comment by dscho** [comment]
> Or maybe we just do this on top, and merge this here PR first?

Oh, and I think we might also be missing the 4e7fdd74d90e patch...

**Pull request merged**
