### PR TITLE
RFC: Diverse environment fixes

### PR DESCRIPTION
**Pull request by kblees**
This fixes several issues that recently crept into git's environment code.

### CODE REVIEW

**Comment by dscho** [comment]
Whoa. The changes speak a *very* different language than the PR's title suggests: they are *intrusive* and quite possibly reintroduce problems I just spent a ton of time and frustration to fix.

I will have to give this a very thorough review. The fact that the underlying issue -- playing games with the environment -- is not addressed by this PR makes me very wary. I think it might just paper over the problem that Git for Windows does not use the environment in the way it is designed to be used, and we incur all kinds of "interesting" problems.

**Comment by dscho** [comment]
> I will have to give this a very thorough review.

I reconsidered and will not do that, but instead focus on a few more pressing things first, then concentrate on a robust design for transparent Unicode environment access.

**Comment by lygstate** [comment]
@dscho, @kblees is expert about Unicode things, so we should trust him, he make the git can works with utf-8 properly on windows long time before, many thanks for his outstanding working

**Comment by dscho** [comment]
> @dscho, @kblees is expert about Unicode things

Funny that you say that. I am actually sitting right next to him while listening to a Microsoft guy speaking about Git.

**Comment by lygstate** [comment]
@dscho You should not be so rude.

**Comment by lygstate** [comment]
@dscho  you do not respect other people so you won't be respected.

**Comment by PhilipOakley** [comment]
Hi @lygstate, @dscho, I'm finding it difficult to follow some of the misunderstandings that are happening here. It is useful to "block quote" the relevent part of the previous message, especially if it is a quick one line reply. (I deliberately chose not to give an example here in case of misinterpretation).  

Because the replies are not threaded, it is easy (for the reader) to mistake which message is being commented upon (and it may accidently be from the wrong issue). It's then rather too easy to create blame where none was intended, leading to a downward spiral of misunderstanding.

Likewise, it's useful to try to expand any short 'on-liners'. While compact code is usually good,  it's terrible for social cohesion in open-ended English discussions with endless nuance, especially its (poor) use of the indefinite article (i.e. the solution is to try converting them to a definite item;-).

I also find it (have found it) difficult to do. It is easy to think things are 'obvious', and then find out the reader wasn't thinking along the same lines, so clearer writing is needed. Today an internal on-line email I was writing ended up as 6 paragraphs because of such realisations! - See the section "Burden of Expertise" in the classic "Unskilled and Unaware of it" paper by Kruger & Dunning, regarding the performance of peers (of experts). It takes a long time to learn, and I still make mistakes..

Keep up the good work, and my apologies for not contributing as much as I'd have liked.

Philip

**Comment by dscho** [comment]
> Keep up the good work, and my apologies for not contributing as much as I'd have liked.

Thanks so much! And don't worry about "not contributing much". You contribute when you have time, and you contribute really nice stuff and you are good with improving things when somebody has a suggestion how to do that.

As far as this PR is concerned, I am happy to report that @kblees and myself met in Paris for the Git Merge (which is still going on) and already threw back and forth ideas and problems that prevent the realization of said ideas. It's really fun!

**Comment by kblees** [comment]
As maintaining a separate (UTF-8) copy of the environment is still controversial, I've removed those patches. I also replaced "git-wrapper: remove redundant HOME initialization" with "git-wrapper: fix HOME initialization".

I'll create separate pull requests for the "separate copy" and "wrapped" alternatives discussed in issue #49.

**Comment by kblees** [comment]
> I am pretty certain that I introduced this change to fix several tests in the test suite

The test suite passes for me locally (that's why I had so much time to comment on other things :-)

**Comment by dscho** [comment]
:-) Just to make sure, I will let it run here, too (will go to sleep , though, rather than comment while waiting for the test suite to finish... :smiley_cat: )

**Comment by dscho** [comment]
Unsurprisingly you are correct! The test suite runs fine here, too, even after restarting the shell after `git-extra` is installed (which ensures that `TMP` is *not* set to `/tmp`). So I merged it!

Thank ou so much.y

**Comment by KamranMackey** [comment]
@dscho you need to fix your comment. It's supposed to be "Thank you so much.", not "Thank ou so much.y". :stuck_out_tongue:

**Pull request merged**
