### PR TITLE
Prepare for 2.41.0(3) release

### PR DESCRIPTION
**Pull request by mjcheetham**
Prepare for the 2.41.0(3) release with the new Git Credential Manager component (2.2.2).

### CODE REVIEW

**Review by derrickstolee — APPROVED** [review]

**Comment by dscho** [comment]
Could you edit the [release notes](https://github.com/git-for-windows/build-extra/blob/main/ReleaseNotes.md#known-issues) by copying over the remarks about Windows 7 and i686, and maybe edit the GCM entry to clarify that it's the reason for a quick follow-up release?

After editing and pushing, re-running the `tag-git` run and then ensuring that the `git-artifacts` runs are re-run should suffice to incorporate the changes.

**Comment by mjcheetham** [comment]
Release notes update here: https://github.com/git-for-windows/build-extra/commit/fb039a937fde8171b028899760e4754b9fb3960f

Will re-run the tag-git and artifacts workflow...

**Comment by mjcheetham** [comment]
Manually re-running the tag-git job...

https://github.com/git-for-windows/git-for-windows-automation/actions/runs/5547155502

**Comment by enderwert** [comment]
Dne čt 13. 7. 2023 23:43 uživatel Matthew John Cheetham <
***@***.***> napsal:

**Comment by mjcheetham** [comment]
Now re-running both 64 and 32 bit artifact workflows:

- https://github.com/git-for-windows/git-for-windows-automation/actions/runs/5547166381
- https://github.com/git-for-windows/git-for-windows-automation/actions/runs/5547166016

**Pull request merged**
