### PR TITLE
DO NOT MERGE YET: make git-rebase a builtin

### PR DESCRIPTION
**Pull request by keugenek**
rebase: Introduce native rebase helper

Git rebase functionality currently implemented in the git-rebase.sh,
git-rebase--am.sh, git-rebase--interactive.sh and git-rebase--merge.sh.
Rewritten in C it will become faster and ready to integrate with other C code.

rebase--helper to be called from git-rebase.sh run_specific_rebase with
git-rebase-am, git-rebase-interactive, git-rebase-merge subcommands eliminating
above scripts one by one and then git-rebase.sh will be converted itself.

Signed-off-by: Evgeny Knyazev <evgeny.knyazev (at) gmail.com>

### CODE REVIEW

**Comment by pyokagan** [comment]
Hi @keugenek, you may be interested in @pclouds 's [work in porting git-rebase to C](http://thread.gmane.org/gmane.comp.version-control.git/265702). 

Thanks, and I'm looking forward to this :-)

**Comment by keugenek** [comment]
Hi @pyokagan, thank you for the link! Looking into the @pclouds 's patch

**Comment by pclouds** [comment]
Please note that it's outdated (a lot have changed in the .sh version since I made the patches), so don't copy as-is. And at some point we should bring this to Git mailing list because the rewrite affects more than Windows platform.

**Comment by dscho** [comment]
> Please note that it's outdated (a lot have changed in the .sh version since I made the patches), so don't copy as-is.

But it will provide a good start!

> And at some point we should bring this to Git mailing list because the rewrite affects more than Windows platform.

Yes. But we have to have *something* to show first ;-)

**Comment by dscho** [comment]
@keugenek did you have any chance to look over the pre-existing work yet?

**Comment by keugenek** [comment]
Thank you @pclouds for this solution. I'd suggest to go to Git mailing list after we have visible progress here...
@dscho yes, I've looked over the existing work. As we discussed before I agree we should move forward with small steps implementing them in git-rebase--heper.c yet this code is very useful as a reference.
As a candidate to convert first I'm thinking of "git rebase --abort"  to go to git-rebase--helper.c. I understand this is not a good choice from gaining performance boost from the beginning but I guess approach of moving independent parts away first will help us to convert it with smaller parts more predictable.
What do you think?

**Comment by dscho** [comment]
I would like to know first how far along @pclouds' version is. If it is less work to complete it than to go forward with the `rebase--helper` approach, I would be very much in disfavor of my own, previous idea. The more we can benefit from @pclouds' hard work, the better.

**Comment by keugenek** [comment]
Hi @dscho, current state is the following (@pclouds, please correct me if I'm wrong):
1. git-rebase--*.sh have not been converted
2. git-rebase.sh has been converted on 80% with the following TODOs:
2.1. Implement run_pre_rebase_hook
2.2. Make sure the branch to rebase onto is valid. 
2.3. Is it "rebase other $branchname" or "rebase other $commit"? 
2.4. Check if we are already based on $onto with linear history
2.5. Detach HEAD and reset the tree
2.6. Validate strategy options

Current version of rebase.c based on git-rebase.sh from 2013. There are 200+ changes since 2013 that need to be addressed.
I'm trying to apply this patch now and run tests if this is possible in the current state.

**Comment by dscho** [comment]
> There are 200+ changes since 2013 that need to be addressed.

Ugh.

I will hopefully have time on Friday to have a look myself. Thanks!

**Comment by mstrap** [comment]
I think approaching the problem in small steps, as initially planned, is the right approach, because incrementally improving rebase less likely breaks anything and is significantly easier to review. So maybe splitting up @pclouds existing code into smaller bits, starting with the most low-level ones first and immediately going back to the Git mailing list with these results?

**Comment by dscho** [comment]
@mstrap sounds like a good strategy to me!

**Comment by keugenek** [comment]
Hi,

I merged first 2 @pclouds' changes into up-to-date branch (all tests work fine):
[PATCH/WIP 1/8] strbuf: add and use strbuf_read_file_or_die()
https://github.com/keugenek/git/commit/5404c7b5d14b7896099059274c0cc9933bc4601c
[PATCH/WIP 2/8] Move reset_tree from builtin/checkout.c to unpack-tree
https://github.com/keugenek/git/commit/ce7cb99bb9dd45ad613eb2d4cdccbd1ada96d97c

@dscho, what do you think if these changes enough to propose in the main Git mailing list?

Next @pclouds fixes fail tests after merge (looking into them now):
[PATCH/WIP 3/8] rebase: turn rebase--am into a separate program
[PATCH/WIP 4/8] rebase: turn rebase--merge into a separate program
[PATCH/WIP 5/8] rebase: turn rebase--interactive into a separate program

**Comment by dscho** [comment]
@keugenek please force-push your `master` branch to update this Pull Request.

**Comment by keugenek** [comment]
Hi @dscho I discussed these latest changes with @mstrap and we both agreed these changes does not yet address real problem, they just prepare code for future modifications. It might be not so good candidate for the community to apply changes without any immediate profit.

Looking into the changes that may be useful to implement in native code first it might be git-rebase-merge.sh where a loop of calls to functions call_merge and continue_merge located. I'll try to switch from implementing @pclouds patch for a while and try to check if I can make some portions of git-rebase-merge.sh code native and will use @pclouds changes when required.

**Comment by mstrap** [comment]
@dscho, regarding @keugenek's plan, can you confirm that the "merge" rebase (git-rebase--merge.sh) is the default rebase strategy, i.e. the most commonly used one? I guess for the merge strategy (--strategy parameter), "recursive" will be most commonly used because it's the default? Then, the amount of code which needs to be converted to support this specific configuration seems to be just a fraction of all rebase-related code, but it should still improve performance for the majority of rebases performed.

**Comment by pclouds** [comment]
@keugenek careful. Those git-rebase-XXX.sh is _sourced_ so you'll have to make sure you export the right variables first. And it adds more burden on people who update git-rebase.sh because this git-rebase--merge.sh now works in a bit different (non-sh) way than the others.

**Comment by mstrap** [comment]
@pclouds, can you please elaborate on what "sourced" here means and which possible problems you are expecting regarding variables exporting? Do you think the planned change is likely to be reviewed and accepted for one of the next (major) Git releases?

**Comment by pclouds** [comment]
(feeling guilty, I should be looking at the untracked cache problem in my very little time for git, but anyway.. well.. this is easier)

This line in git-rebase.sh

    	. git-rebase--$type

means all the functions or (not exported) variables in git-rebase.sh are available to this git-rebase-$type script. It's not exactly the same as launching a C-based program. This is why I chose the top-down approach, to convert git-rebase.sh first, so I know what all "sub" scripts are expected, because I would break them _all_.

I'm not saying you should convert git-rebase.sh first. Just think a minute what may happen and prepare for it if you want to convert git-rebase--<something>.sh first.

**Comment by dscho** [comment]
My strong preference would be to introduce a builtin helper (`git-rebase--helper`) and then start moving functionality from *parts* of `git-rebase--*.sh` to that helper.

**Comment by keugenek** [comment]
Hi @dscho,

Ok, moving into this direction yet already facing problem @pclouds warned. Some tests fail after merge  commit "[PATCH/WIP 4/8] rebase: turn rebase--merge into a separate program". I guess this is because lack of exporting some variables, but I added all that are used in git-rebase--merge.sh with no luck.

What is most convenient way to debug test failures with mixed shell & C code? Is there any way running them in debug mode step-by step or is the only way is to write trace output?

**Comment by dscho** [comment]
@keugenek how about force-pushing your current work? As it is, I cannot even have a look myself...

**Comment by keugenek** [comment]
@dscho Done!

**Comment by dscho** [comment]
As per [this mail](https://groups.google.com/d/msg/git-for-windows/vlvXXOD12wY/IqXbfVIeAwAJ), this effort has been abandoned.

**Pull request closed without merging**
