### PR TITLE
Clean-up Git for Windows' topic branches a little

### PR DESCRIPTION
**Pull request by dscho**
Now that the v2.39.1 dust has settled, let's re-arrange a couple of topics, and re-base the branch thicket onto the cherry-picked fixes c6ab91335a16 and 37537d6472d8 that made it into Git for Windows v2.39.1 but not into Git v2.39.1.

Note: the result of this PR is intentionally tree-same, i.e. it is not supposed to introduce any new file changes that had not been there before.

Also note: the mimalloc patches (including the two preparatory patches `win32/pthread: avoid name clashes with winpthread` and `git-compat-util: avoid redeclaring _DEFAULT_SOURCE`) look as if they were dropped in the range-diff; They were not dropped, in fact, but replaced with newer versions via #4211.

Lastly, including the patches to address cURL deprecation errors required some context changes.

<details><summary>Range-diff relative to `main`</summary>

* 1:  eb749d2bf537 <   -:  ------------ fixup! Merge pull request #4013 from dscho/mimalloc
* 262:  6d54c6b5bb21 !   1:  695601570442 http-push: prefer CURLOPT_UPLOAD to CURLOPT_PUT

   ``````diff
   @@ Commit message
    
        Signed-off-by: Jeff King <peff@peff.net>
        Signed-off-by: Junio C Hamano <gitster@pobox.com>
   -    Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>
    
     ## http-push.c ##
    @@ http-push.c: static void curl_setup_http(CURL *curl, const char *url,
   ``````

* 263:  ee08d7b1abe6 !   2:  fe7e44e1ab7d http: prefer CURLOPT_SEEKFUNCTION to CURLOPT_IOCTLFUNCTION

   ``````diff
   @@ Commit message
    
        Signed-off-by: Jeff King <peff@peff.net>
        Signed-off-by: Junio C Hamano <gitster@pobox.com>
   -    Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>
    
     ## INSTALL ##
    @@ INSTALL: Issues of note:
   ``````

* 264:  de848e381020 !   3:  6c065f72b8d5 http: support CURLOPT_PROTOCOLS_STR

   ``````diff
   @@ Commit message
    
        Signed-off-by: Jeff King <peff@peff.net>
        Signed-off-by: Junio C Hamano <gitster@pobox.com>
   -    Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>
    
     ## git-curl-compat.h ##
    @@
   + #define GIT_CURL_HAVE_CURLSSLSET_NO_BACKENDS
     #endif
     
   - /**
   ++/**
    + * CURLOPT_PROTOCOLS_STR and CURLOPT_REDIR_PROTOCOLS_STR were added in 7.85.0,
    + * released in August 2022.
    + */
   @@ git-curl-compat.h
    +#define GIT_CURL_HAVE_CURLOPT_PROTOCOLS_STR 1
    +#endif
    +
   -+/*
   -  * CURLSSLOPT_AUTO_CLIENT_CERT was added in 7.77.0, released in May
   -  * 2021.
   -  */
   + #endif
    
     ## http.c ##
    @@ http.c: void setup_curl_trace(CURL *handle)
   ``````

* 8:  fd03d8657ab0 =   4:  5ef19b63bf70 windows: ignore empty `PATH` elements
* 9:  8368ffd004c6 =   5:  9121f5c92c78 is_Cygwin: avoid `exec`ing anything
* 10:  42b272c04612 =   6:  15ea1198bae3 Move is_<platform> functions to the beginning
* 11:  1ea4132b3c39 =   7:  24f3f5833430 Move the `_which` function (almost) to the top
* 12:  5de016e4ad62 =   8:  2dd84542702a Work around Tcl's default `PATH` lookup
* 15:  e9d0ee2a2108 =   9:  f0d07dd9f263 t9350: point out that refs are not updated correctly
* 16:  81f82f5fab9f =  10:  eaf2326a3a57 transport-helper: add trailing --
* 17:  cebf6001aeaa =  11:  5d6481a20ee0 remote-helper: check helper status after import/export
* 18:  942f42fb6392 =  12:  4a9ad8b5c4d4 mingw: demonstrate a problem with certain absolute paths
* 19:  3dc57cec8e2f =  13:  891934013556 gitk: prevent overly long command lines
* 22:  c6f63b45a910 =  14:  d100ed41d33f Always auto-gc after calling a fast-import transport
* 23:  092d47680c45 =  15:  bf4e3fcc60c2 mingw: allow absolute paths without drive prefix
* 24:  39665ade8ed9 =  16:  ee73ee3a3326 mingw: change core.fsyncObjectFiles = 1 by default
* 21:  03391e899eb9 =  17:  ed43e86315da mingw: include the Python parts in the build
* 2:  e60e2a7910f1 =  18:  2384d028e2a5 win32/pthread: avoid name clashes with winpthread
* 3:  2a31976ae89e =  19:  1750da6dee77 git-compat-util: avoid redeclaring _DEFAULT_SOURCE
* 4:  174615b28533 =  20:  65a3e96108b2 Import the source code of mimalloc v2.0.9
* 5:  e90043cd27aa =  21:  8a69e1c3e14d mimalloc: adjust for building inside Git
* 6:  3d225d48df7d <   -:  ------------ mimalloc: offer a build-time option to enable it
* 20:  5f09b3c4f47e =  22:  d737a5f1b6d2 clean: do not traverse mount points
* 138:  71d92080de57 =  23:  4a6bd4b50df9 mimalloc: offer a build-time option to enable it
* 25:  f4fbf1906ee5 =  24:  b01bd6291b3e gitk: Escape file paths before piping to git log
* 26:  1ed0461115e2 =  25:  62954e10f87e clean: remove mount points when possible
* 29:  16c8fb670cc4 =  26:  7d8228f0aa9f mingw: demonstrate a `git add` issue with NTFS junctions
* 7:  e86d22c4fff0 =  27:  1dd4bba3f746 mingw: use mimalloc
* 13:  5a3c8436f570 (upstream: 37537d6472d8) <   -:  ------------ attr: adjust a mismatched data type
* 14:  3b753341ef8b (upstream: c6ab91335a16) <   -:  ------------ fsck: document the new `gitattributes` message IDs
* 27:  b74c43d06772 =  28:  3207284b4850 Config option to disable side-band-64k for transport
* 35:  dcae8ac22bf7 =  29:  a9aadca9785b mingw: make sure `errno` is set correctly when socket operations fail
* 36:  fbbe4b5b605e =  30:  cf8ebebf92e5 mingw: do resolve symlinks in `getcwd()`
* 37:  a790e8bd9850 =  31:  e0aed23dff91 mingw: fix fatal error working on mapped network drives on Windows
* 38:  8e901f1ed4b5 =  32:  8457885fdf95 clink.pl: fix MSVC compile script to handle libcurl-d.lib
* 32:  c339ecba4dc0 =  33:  ef56d2ea5d57 vcxproj: unclash project directories with build outputs
* 28:  594ca322f086 =  34:  0cd3a89a9730 mingw: ensure valid CTYPE
* 40:  3b801d4950b2 =  35:  828c9f81755a t5505/t5516: allow running without `.git/branches/` in the templates
* 30:  45e73e1da447 =  36:  7ecd14330902 mingw: allow `git.exe` to be used instead of the "Git wrapper"
* 31:  991301b2da0f =  37:  59dff162eea4 strbuf_realpath(): use platform-dependent API if available
* 41:  7354e6995e56 =  38:  8bb50a1fa924 t5505/t5516: fix white-space around redirectors
* 33:  492f6919cb6d =  39:  84dac4b74d34 mingw: ignore HOMEDRIVE/HOMEPATH if it points to Windows' system directory
* 34:  42ea09ad6e39 =  40:  e43973f8c272 http: use new "best effort" strategy for Secure Channel revoke checking
* 39:  cb2da8b89c70 =  41:  c4d21fb57c80 mingw: implement a platform-specific `strbuf_realpath()`
* 42:  6c40630a9d48 =  42:  7d71411e5786 Allow `add -p` and `add -i` with a large number of files
* 44:  911f6470d17f =  43:  f6b0abdf8985 t3701: verify that we can add *lots* of files interactively
* 45:  7995367d1e4a =  44:  485d36ceb911 git add -i: handle CR/LF line endings in the interactive input
* 46:  a9b1655b7cc0 =  45:  a5f0bddb1cd4 commit: accept "scissors" with CR/LF line endings
* 47:  8bcc106d19cf =  46:  77455779a956 t0014: fix indentation
* 48:  1630ae2068c3 =  47:  41735cab617b git-gui: accommodate for intent-to-add files
* 43:  f2481ee93a44 =  48:  46ae884ffc19 clink.pl: fix libexpatd.lib link error when using MSVC
* 49:  78fb69467451 =  49:  05efe8237f21 Makefile: clean up .ilk files when MSVC=1
* 50:  a59603709891 =  50:  b1c486c7020e vcbuild: add support for compiling Windows resource files
* 51:  1706d5bc7cac =  51:  aa95ce2317de config.mak.uname: add git.rc to MSVC builds
* 52:  78b185713257 =  52:  e243178663b1 clink.pl: ignore no-stack-protector arg on MSVC=1 builds
* 53:  e99b47dd16c6 =  53:  62022eca7f3b clink.pl: move default linker options for MSVC=1 builds
* 54:  9bd366de2b94 =  54:  4f0ff06285c9 buildsystems: remove duplicate clause
* 55:  719d577d210c =  55:  df6cc61cc82f vcxproj: handle resource files, too
* 57:  3442e146fb67 =  56:  f6454e8a13c2 vcxproj: ignore -fno-stack-protector and -fno-common
* 59:  d58aa7937742 =  57:  6677efa68b2b vcxproj: handle GUI programs, too
* 61:  9ad610a9e604 =  58:  640626ee4cc3 win32: add a helper to run `git.exe` without a foreground window
* 63:  6eeb025fb88c =  59:  15f63097b007 git maintenance: avoid console window in scheduled tasks on Windows
* 56:  fca5df5a62db =  60:  0139897d96c1 vcpkg_install: detect lack of Git
* 58:  163e37532443 =  61:  9be5a20930b2 vcpkg_install: add comment regarding slow network connections
* 60:  cefd8f58d5f7 =  62:  53abd5f0f9cc vcxproj: support building Windows/ARM64 binaries
* 62:  34cef15a1f56 =  63:  a22cc2bbd723 vcbuild: install ARM64 dependencies when building ARM64 binaries
* 73:  972d8374e724 =  64:  a2f3ca019520 vcbuild: add an option to install individual 'features'
* 75:  c757a9ec1f47 =  65:  18ae03e6b1eb cmake: allow building for Windows/ARM64
* 77:  74679e7bc8fa =  66:  c8be0503b400 ci(vs-build) also build Windows/ARM64 artifacts
* 79:  d034ac2e1002 =  67:  e24188aaa0e8 Add schannel to curl installation
* 64:  318ad3dd570c =  68:  466fabf85133 Add a GitHub workflow to generate Git for Windows' Pacman package
* 65:  a3116b38d54e =  69:  bd02e76cd1e1 git-artifacts: if GPG secrets are available, use them
* 66:  b835e92e96cf =  70:  ab500f73b95f git-artifacts: also code-sign, if configured via the secrets
* 67:  6bc46f49df4d =  71:  8920a9f894dc git-artifacts: also build the installer
* 68:  431410344a8b =  72:  f95f018beb1e git-artifacts: also build portable, mingit and mingit-busybox
* 69:  8b53cd0b181c =  73:  1517d161ef3e git-artifacts: also build 32-bit versions
* 70:  2bd540f43938 =  74:  4dd354b4f6d1 git-artifacts: also build the nuget package
* 71:  9fa55c684831 =  75:  061cb5922bd3 git-artifacts: allow restricting which artifacts are built
* 72:  24b3abe34971 =  76:  17074760330b git-artifacts: allow specifying repo/ref via workflow_dispatch
* 74:  1868ef548223 =  77:  05b1547e2263 git-artifacts: cache the build-installers artifact
* 76:  cf571e488bd9 =  78:  147eaecd4307 git-artifacts: use the cached build-installers instead of makepkg-git
* 78:  6b04a02d022d =  79:  ec2d71fd087b git-artifacts: add ARM64 artifacts
* 86:  e863b1ee634d =  80:  cbaf8cd96782 git-artifacts: add workaround for GCM Core on ARM64
* 80:  5c223e63829a =  81:  9c0c553fa1bb git-artifacts(arm64): avoid hard-linking the dashed built-ins
* 81:  fb01e623e892 =  82:  bdf89f234512 git-artifacts: use a narrower `PATH`
* 82:  363035ba0c83 =  83:  9989dd9ebe60 git-artifacts: fix BUILD_ONLY handling for ARM64
* 83:  d2efeabdc106 =  84:  52e4773991bb git-artifacts: extend the `SKIP` logic to handle `pkg` and `build-arm64`
* 84:  69efc7145336 =  85:  da9623d4f303 git-artifacts: mark all inputs as "not required"
* 85:  cc975e3df8c0 =  86:  53ff6361152d git-artifacts(build-arm64): build artifacts using the intended Git revision
* 87:  c5ed015f785c =  87:  d28652d0711c cmake(): allow setting HOST_CPU for cross-compilation
* 88:  febd9543f05d =  88:  e64e63723456 git-artifacts: use the `setup-git-for-windows-sdk` Action
* 89:  102c29978d86 =  89:  0780c6fed375 ci(): add HOST_CPU to CMake command
* 92:  bd131b2bef25 =  90:  838b167ad2b3 subtree: update `contrib/subtree` `test` target
* 95:  029348b74cfd =  91:  cb0861b20fb3 ci(vs-build): download the vcpkg artifacts using a dedicated Action
* 96:  3d7a8ed80efb =  92:  eb73e4758f7a mingw: allow for longer paths in `parse_interpreter()`
* 97:  b88a43931bbd =  93:  e1fc4bbe82c4 compat/vcbuild: document preferred way to build in Visual Studio
* 98:  0ccc1e394c08 !  94:  84faf809ec3b http: optionally send SSL client certificate

   ``````diff
   @@ Documentation/config/http.txt: http.schannelUseSSLCAInfo::
    
     ## git-curl-compat.h ##
    @@
   - #define GIT_CURL_HAVE_CURLSSLSET_NO_BACKENDS
   + #define GIT_CURL_HAVE_CURLOPT_PROTOCOLS_STR 1
     #endif
     
   -+/**
   ++/*
    + * CURLSSLOPT_AUTO_CLIENT_CERT was added in 7.77.0, released in May
    + * 2021.
    + */
   ``````

* 90:  e08a784af21e =  95:  1a1618b26105 CMake: default Visual Studio generator has changed
* 91:  f06b2be10b23 =  96:  143821126712 .gitignore: add Visual Studio CMakeSetting.json file
* 93:  3c10558ec7f2 =  97:  8950f879c7f3 CMakeLists: add default "x64-windows" arch for Visual Studio
* 94:  31f219515ae9 =  98:  89ea0bd5b9c2 fsmonitor: reintroduce core.useBuiltinFSMonitor
* 99:  3cd850cc5ee1 =  99:  9a6f6689b4f6 ci: run `contrib/subtree` tests in CI builds
* 100:  677b209584ce = 100:  1790274a9d53 CMake: show Win32 and Generator_platform build-option values
* 101:  9734bc754e09 = 101:  0030b131a3a9 init: do parse _all_ core.* settings early
* 102:  a2f6369335a0 = 102:  527096e89a7a Enable the built-in FSMonitor as an experimental feature
* 103:  ba255eb32e25 = 103:  deb05106779c hash-object: demonstrate a >4GB/LLP64 problem
* 104:  b1a65290db20 = 104:  8dfe78d661d0 hash_object_file_literally(): use size_t
* 105:  eb57df146ead = 105:  c7254ba18622 object-file.c: use size_t for header lengths
* 106:  c2129f41eb7e = 106:  659853a21fef hash algorithms: use size_t for section lengths
* 107:  8fb6b60ff997 = 107:  2f0aa656d02f hash-object --stdin: verify that it works with >4GB/LLP64
* 108:  6dfc114ff5a8 = 108:  98e366a326c8 hash-object: add another >4GB/LLP64 test case
* 109:  d38618cc7e71 = 109:  1d4de5463264 setup: properly use "%(prefix)/" when in WSL
* 110:  de49b9e85c68 = 110:  6ec3d4431f0f hash-object: add a >4GB/LLP64 test case using filtered input
* 111:  63d85c2d2e0c = 111:  447495416fa6 compat/mingw.c: do not warn when failing to get owner
* 112:  232e78dfec22 = 112:  2620f18f8511 mingw: $env:TERM="xterm-256color" for newer OSes
* 113:  98d736c01e96 = 113:  3c8df08f2667 winansi: check result and Buffer before using Name
* 115:  6821b1be3fa2 = 114:  2a5d240be76b vcxproj: allow building with `NO_PERL` again
* 116:  23a5b80fcd6c = 115:  e6d402c33af4 vcxproj: require C11
* 117:  4cbf48c29edd = 116:  021f02ab7447 vcxproj: ignore the `-pedantic` option
* 118:  ce51c4b86e91 = 117:  26c6f16e6e41 vcxproj: include reftable when committing `.vcxproj` files
* 119:  4b531000ab29 = 118:  0946acba5825 vcxproj: handle libreftable_test, too
* 120:  eef090937d34 = 119:  467b9f9530a3 vcxproj: avoid escaping double quotes in the defines
* 121:  0e640bde8bd3 = 120:  6c4f41f44cc3 ci: adjust Azure Pipeline for `runs_on_pool`
* 122:  5c7ae16964b5 = 121:  d71342d3140e ci: stop linking the `prove` cache
* 123:  351e738bbe87 = 122:  e246b18a25cf ci: reinstate Azure Pipelines support
* 114:  e4ff2e1ffe43 = 123:  ccc5c798a738 Add config option `windows.appendAtomically`
* 124:  3ec7a9d0d49e = 124:  f72ee05300ab azure-pipeline: drop the `GETTEXT_POISON` job
* 125:  3da72b6fa0ef = 125:  4ba2597ca397 azure-pipeline: stop hard-coding `apt-get` calls
* 126:  d8abffa68b0d = 126:  8ed8cd1ad378 azure-pipeline: drop the code to write to/read from a file share
* 127:  678a6f60c33a = 127:  caa96895e123 azure-pipeline: use partial clone/parallel checkout to initialize minimal-sdk
* 128:  907dee9eecde = 128:  a35011493049 azure-pipeline: downcase the job name of the `Linux32` job
* 142:  6c5915182716 = 129:  a1c00e28df2b bswap.h: add support for built-in bswap functions
* 129:  227d3664a1a2 = 130:  adc21db75255 azure-pipeline: run static-analysis on jammy
* 130:  9c39bf8873b0 <   -:  ------------ win32/pthread: avoid name clashes with winpthread
* 131:  ce57e9dfe964 <   -:  ------------ git-compat-util: avoid redeclaring _DEFAULT_SOURCE
* 132:  bf85ce4b01cf <   -:  ------------ Import the source code of mimalloc
* 133:  3cdcee16566f <   -:  ------------ mimalloc: allow running in Windows Nano Server containers
* 134:  b773e722fe8b <   -:  ------------ mimalloc: adjust for building inside Git
* 135:  ee710ee42d74 <   -:  ------------ mimalloc: avoid `%z` format
* 136:  a6af047c595e <   -:  ------------ mimalloc: avoid having to link to `psapi` just for mimalloc
* 137:  e8bf98e3a254 <   -:  ------------ mimalloc: avoid having to link to `bcrypt` just for mimalloc
* 139:  7405e25bd8d2 <   -:  ------------ mimalloc: make MIMALLOC_SHOW_STATS work with redirected `stderr`
* 140:  8951c39ada6e = 131:  1880cc8ac3e8 MinGW: link as terminal server aware
* 141:  247b10bfc75a <   -:  ------------ mingw: use mimalloc
* 144:  0ce752404377 = 132:  15b487adc74c Fix Windows version resources
* 143:  d46dd39b7b27 = 133:  4a37349a333a config.mak.uname: add support for clangarm64
* 145:  5dd7d765a470 = 134:  31274a9ec2f0 ci: create clangarm64-build.yml
* 167:  bd960da38212 = 135:  359516f1c3ec status: fix for old-style submodules with commondir
* 168:  8d7f3dc722ef = 136:  4970d0d3f94a Win32: make FILETIME conversion functions public
* 169:  6a084f6c64d9 = 137:  a84d412f7d8c Win32: dirent.c: Move opendir down
* 170:  458b9027711b = 138:  a5433ec1e990 mingw: make the dirent implementation pluggable
* 171:  025130fb4515 = 139:  b551ecd58ec9 Win32: make the lstat implementation pluggable
* 172:  f498642bdca9 = 140:  5613f9744697 add infrastructure for read-only file system level caches
* 173:  9a9ef74cc5d7 = 141:  ca6230fc64ef mingw: add a cache below mingw's lstat and dirent implementations
* 174:  c78937148cff = 142:  9f07f8207e04 fscache: load directories only once
* 175:  10bc0ac76e49 = 143:  edd3a9697f79 fscache: add key for GIT_TRACE_FSCACHE
* 176:  ae0d457a824c = 144:  8b63ea48496c fscache: remember not-found directories
* 177:  625859aac40c = 145:  ef9f9fa7435c fscache: add a test for the dir-not-found optimization
* 178:  25642ca6e995 = 146:  251c3847d3d3 add: use preload-index and fscache for performance
* 179:  5abfb179697a = 147:  e83748b4f2b9 dir.c: make add_excludes aware of fscache during status
* 180:  96ac7d619dfa = 148:  7a5f0bf787ea fscache: make fscache_enabled() public
* 181:  178bf802e9a5 = 149:  36cf5ddaa49b dir.c: regression fix for add_excludes with fscache
* 182:  dd4482c83d49 = 150:  219cad8314a9 fetch-pack.c: enable fscache for stats under .git/objects
* 183:  e736803b45c7 = 151:  c0abae449b6e checkout.c: enable fscache for checkout again
* 184:  aa316c82f37e = 152:  61c6c743ec66 Enable the filesystem cache (fscache) in refresh_index().
* 185:  cc33eea5e7ec = 153:  8d75738fab2c fscache: use FindFirstFileExW to avoid retrieving the short name
* 186:  4503be003e38 = 154:  ea9419ed1b0f status: disable and free fscache at the end of the status command
* 187:  348b6bfcffc0 = 155:  4305bab2acd0 fscache: add GIT_TEST_FSCACHE support
* 188:  529fdf7f369d = 156:  84e8a145ac44 fscache: add fscache hit statistics
* 189:  28df33a876b1 = 157:  38e5aa44bff1 mem_pool: add GIT_TRACE_MEMPOOL support
* 190:  589dd9101032 = 158:  acb020960d69 fscache: fscache takes an initial size
* 191:  86a31e0900ab = 159:  8732ce55241c fscache: update fscache to be thread specific instead of global
* 192:  cb29c86465b4 = 160:  a5b5a2c80dbf fscache: teach fscache to use mempool
* 193:  23aeb81951df = 161:  f815cb82ee60 fscache: make fscache_enable() thread safe
* 194:  dee7495eb69b = 162:  47fe54b73dcc fscache: teach fscache to use NtQueryDirectoryFile
* 195:  954dd4ad0dc0 = 163:  28aa0f510da0 unpack-trees: enable fscache for sparse-checkout
* 196:  d79c547575b1 = 164:  a96ee106e047 fscache: remember the reparse tag for each entry
* 197:  8882fc7fb108 = 165:  5a9239552158 fscache: implement an FSCache-aware is_mount_point()
* 146:  4ac08573d49a = 166:  765d84105520 git-gui: provide question helper for retry fallback on Windows
* 198:  ddfc77583568 = 167:  ecf57a52a140 clean: make use of FSCache
* 147:  7aa73cf2ce09 = 168:  d03d928ffc00 git gui: set GIT_ASKPASS=git-gui--askpass if not set yet
* 152:  e2d5a38bd2a6 = 169:  e0d01241b7f8 gitk: Unicode file name support
* 148:  3982c6f96492 = 170:  84baf6a56b4c git-gui--askyesno: fix funny text wrapping
* 153:  ecb97500334c = 171:  4a7f027ca954 gitk: Use an external icon file on Windows
* 149:  404d76d38ac4 = 172:  9dc0acc5ea63 git-gui--askyesno: allow overriding the window title
* 154:  45c1b86b185a = 173:  2cd1144adb4c gitk: fix arrow keys in input fields with Tcl/Tk >= 8.6
* 150:  a49623a74632 = 174:  5518dc5fb29e respect core.hooksPath, falling back to .git/hooks
* 151:  c8cad2161aa4 = 175:  4dc776e6b182 git-gui--askyesno (mingw): use Git for Windows' icon, if available
* 155:  e4f4a34c0c3b = 176:  94831db50382 gitk: make the "list references" default window width wider
* 199:  700b0a400c7a = 177:  31b22bffa76f pack-objects (mingw): demonstrate a segmentation fault with large deltas
* 200:  1dd46b065349 = 178:  62baca8092ce mingw: support long paths
* 201:  684d8af6d2eb = 179:  10c4db7e7a04 Win32: fix 'lstat("dir/")' with long paths
* 209:  1c21b9891dce = 180:  9e8564b6dab3 compat/fsmonitor/fsm-*-win32: support long paths
* 202:  6f5966119050 = 181:  e2aca2efbc4a mingw: Support `git_terminal_prompt` with more terminals
* 203:  36a4872e677b = 182:  ba4b3eb3882d compat/terminal.c: only use the Windows console if bash 'read -r' fails
* 204:  da59309236d3 = 183:  49da6b2170d0 mingw (git_terminal_prompt): do fall back to CONIN$/CONOUT$ method
* 205:  860df6914672 = 184:  ed142967038f Unbreak interactive GPG prompt upon signing
* 206:  188e93e68686 = 185:  d67d63748e9b strbuf_readlink: don't call readlink twice if hint is the exact link size
* 207:  abe36dbf7c61 = 186:  a01b6eed1dd2 strbuf_readlink: support link targets that exceed PATH_MAX
* 208:  cea7f4c8eaaf = 187:  bfc421a20698 lockfile.c: use is_dir_sep() instead of hardcoded '/' checks
* 211:  2413b6cdb2e9 = 188:  a7eaa4cf6b97 Win32: don't call GetFileAttributes twice in mingw_lstat()
* 212:  559a3db51e15 = 189:  1e794457d28f Win32: implement stat() with symlink support
* 213:  09304ec72c70 = 190:  0417deec4fb2 Win32: remove separate do_lstat() function
* 210:  4bc3e07b6b02 = 191:  8a8ab79ae205 clean: suggest using `core.longPaths` if paths are too long to remove
* 214:  54e128ea64f7 = 192:  056f72932f8f Win32: let mingw_lstat() error early upon problems with reparse points
* 215:  0cfafc23bd92 = 193:  72c004d3c751 mingw: teach fscache and dirent about symlinks
* 216:  92750eb8612e = 194:  144d893c60ae Win32: lstat(): return adequate stat.st_size for symlinks
* 217:  89ccc035ac5e = 195:  cc8b3636cc91 Win32: factor out retry logic
* 218:  b668a81f860e = 196:  342b2e7694d5 Win32: change default of 'core.symlinks' to false
* 219:  2ce7fd0e0a5f = 197:  e97f14f6486f Win32: add symlink-specific error codes
* 220:  4d1b34bd52c3 = 198:  a955f55345cb Win32: mingw_unlink: support symlinks to directories
* 221:  fc30cf98f1a5 = 199:  0c502d482b05 Win32: mingw_rename: support renaming symlinks
* 222:  67176a55885f = 200:  2fb69ef4a6d3 Win32: mingw_chdir: change to symlink-resolved directory
* 223:  9d2e46b2f48c = 201:  ac271776d5e2 Win32: implement readlink()
* 224:  ea6c7dd78968 = 202:  591b4e654592 mingw: lstat: compute correct size for symlinks
* 225:  2bacac4dea3b = 203:  cf406a25675a Win32: implement basic symlink() functionality (file symlinks only)
* 226:  e1e6cd1e5bfc = 204:  87e8e1f34100 Win32: symlink: add support for symlinks to directories
* 227:  c579749a3ef6 = 205:  966126533fc5 mingw: try to create symlinks without elevated permissions
* 228:  08801bc08739 = 206:  a65bb7802695 mingw: emulate stat() a little more faithfully
* 229:  bfe212a7e335 = 207:  867057cae303 mingw: special-case index entries for symlinks with buggy size
* 235:  2fdad184a482 = 208:  5d0a37dcc486 mingw: introduce code to detect whether we're inside a Windows container
* 230:  9fa53dcdbcd1 = 209:  12a55ec291c6 Win32: symlink: move phantom symlink creation to a separate function
* 237:  cb11fdce7662 = 210:  457e3ebbf10a mingw: when running in a Windows container, try to rename() harder
* 231:  fdb4cad3b6d3 = 211:  6b49a75a5374 Introduce helper to create symlinks that knows about index_state
* 239:  48889b263691 = 212:  82c900d4eea3 mingw: move the file_attr_to_st_mode() function definition
* 232:  b4cb448c9150 = 213:  8e28f1a26fd7 mingw: allow to specify the symlink type in .gitattributes
* 241:  d5144ced0502 = 214:  ed318d0da086 mingw: Windows Docker volumes are *not* symbolic links
* 233:  a960df73bbd8 = 215:  e724f2121704 Win32: symlink: add test for `symlink` attribute
* 234:  b040e8e6c2b4 = 216:  4ac10dbc5a14 mingw: explicitly specify with which cmd to prefix the cmdline
* 236:  54662524a7d2 = 217:  1ec1f703f8f5 mingw: when path_lookup() failed, try BusyBox
* 238:  ac97db277a13 = 218:  a0eae163ff68 test-lib: avoid unnecessary Perl invocation
* 240:  21135897882a = 219:  e95626f826db tests: replace mingw_test_cmp with a helper in C
* 242:  bc3d3ab30d4d = 220:  9e11cb369fe6 test-tool: learn to act as a drop-in replacement for `iconv`
* 243:  0c909eb7310d = 221:  8a19962f3281 tests(mingw): if `iconv` is unavailable, use `test-helper --iconv`
* 244:  ab9f437f4b9f = 222:  bfddb75e24fa gitattributes: mark .png files as binary
* 245:  9f2babb53283 = 223:  9df89645edd7 tests: move test PNGs into t/lib-diff/
* 246:  93dda7755852 = 224:  aafffc23f6e7 tests: only override sort & find if there are usable ones in /usr/bin/
* 247:  f13b6461b343 = 225:  db9b000e54ff tests: use the correct path separator with BusyBox
* 248:  e498501f604a = 226:  785b2416f044 mingw: only use Bash-ism `builtin pwd -W` when available
* 249:  479577b10449 = 227:  4e5fe8428f77 tests (mingw): remove Bash-specific pwd option
* 250:  017d3e0ba7e6 = 228:  21f6d2ba0d8a test-lib: add BUSYBOX prerequisite
* 251:  7b339abf2543 = 229:  7827b28c69db t0021: use Windows path when appropriate
* 252:  4a33ff1ce782 = 230:  e356e9c224b2 t5003: use binary file from t/lib-diff/
* 253:  4f84df705792 = 231:  835e7875f16c t5532: workaround for BusyBox on Windows
* 254:  af59092a7e0f = 232:  57f7551985d0 t5605: special-case hardlink test for BusyBox-w32
* 255:  5be343fb1e58 = 233:  1242e7e81e68 t5813: allow for $PWD to be a Windows path
* 256:  388093df6f88 = 234:  bd542394c74d t9200: skip tests when $PWD contains a colon
* 259:  e412431e1bf5 = 235:  116b3bca2435 mingw: add a Makefile target to copy test artifacts
* 257:  7f006f116b17 = 236:  7934e4ee07de mingw: kill child processes in a gentler way
* 258:  49dc0b9428d5 = 237:  e6583654e079 mingw: do not call xutftowcs_path in mingw_mktemp
* 260:  31a7626d7b6f = 238:  649070530f74 mingw: really handle SIGINT
* 261:  048b5980f37b = 239:  c40770ef28aa Partially un-revert "editor: save and reset terminal after calling EDITOR"
* 156:  d45e3690f46b = 240:  f2ff01e0acfb reset: reinstate support for the deprecated --stdin option
* 157:  af2c4c0c1e6b = 241:  6ef8277acdfb Modify the Code of Conduct for Git for Windows
* 158:  b7298d9412d0 = 242:  aa12e6b8599e CONTRIBUTING.md: add guide for first-time contributors
* 159:  02f5296be28e = 243:  3f10eca8116f README.md: Add a Windows-specific preamble
* 160:  ff79eb4fe7a8 = 244:  444bc22b3dcb Add an issue template
* 161:  2bfa37880380 = 245:  48b313c15639 Modify the GitHub Pull Request template (to reflect Git for Windows)
* 162:  f14674668da1 = 246:  5dddc3b8aba9 .github: Add configuration for the Sentiment Bot
* 163:  eee11233e1d9 = 247:  c22f1936af7c Document how $HOME is set on Windows
* 164:  c1c71e2a0b1c = 248:  2d78bcaf7668 mingw: deprecate old-style runtime-prefix handling in interpolate_path()
* 165:  79395840cc8c = 249:  9608fb11e1a8 Add a GitHub workflow to monitor component updates
* 166:  2f345a0b1e39 = 250:  ec7f8a0f331b SECURITY.md: document Git for Windows' policies

</details>

### CODE REVIEW

**Comment by dscho** [comment]
Seems that we'll have to merge https://github.com/git-for-windows/git/pull/4245 first, then I have to re-do this PR branch.

**Review by derrickstolee — APPROVED** [review]
Approving, even though I had some commentary on the history. It's a very clean organization that doesn't need any changes if you don't want them.

**Comment by dscho** [comment]
> there were a few places where the history got a little twisted, such as this example around some `git-gui` changes

True, even if the `.git/hooks` change _is_ about Git GUI, too ;-)

> It also gets twisted around `Merge branch 'ready-for-upstream'`, but this is more understandable since the very-common-base is actually the first-parent of [95a2057](https://github.com/git-for-windows/git/commit/95a2057b9779cf0464f33ada5f8873b9df8c725b) (`4c1ff5bc6b5 (Merge branch 'jk/curl-avoid-deprecated-api', 2023-01-23)`). The only alternative I can think of to avoid this twist is to replace the merge with a no-op commit stating "earlier commits are ready for upstream" instead of merging them.

Oh, I totally meant for the part above `read-for-upstream` to be based on that merge commit (even if it is technically not correct that they are based on those, but for structuring purposes I'd prefer it). Will do that tomorrow!

**Comment by dscho** [comment]
> I totally meant for the part above `read-for-upstream` to be based on that merge commit (even if it is technically not correct that they are based on those, but for structuring purposes I'd prefer it).

@derrickstolee I now did that. Please have a look. While at it, I also moved the re-introduction of `core.useBuiltinFSMonitor` (now deprecated) up to the other two features I want to phase out: the `reset --stdin` support, and the old, non-portable runtime-prefix handling in `interpolate_path()` (superseded by the portable `%(prefix)/` handling).

**Review by derrickstolee — APPROVED** [review]
Looking good, thanks!

**Pull request merged**
