### PR TITLE
Revert "reset.c: enable fscache"

### PR DESCRIPTION
**Pull request by atetubou**
This reverts commit fcba80a2696c48fba77dd2ab3810092476e36fc2.
Usinsg fscache for reset broke git worktree, git stash. #1437 #1440 

Signed-off-by: Takuto Ikuta <tikuta@chromium.org>

### CODE REVIEW

**Comment by csware** [comment]
Suppose issue #1442 and #1438 and #1443 are also related.

**Comment by atetubou** [comment]
@csware Yes, those are similar issue.
Broken is caused by different commit, I made fix PR separately #1443 .

**Comment by dscho** [comment]
I re-did this patch with more information and marked up as a `fixup!` commit. The test suite is still running, but once it passes, I will release Git for Windows v2.16.1 (Cc: @shiftkey).

**Comment by dscho** [comment]
As mentioned a couple of minutes ago, I re-did this revert to include more information.

Please note that I am still very much interested in a speedup by introducing fscache into this code path! I just think we have to be a bit more careful how we update the stat data.

**Pull request closed without merging**
