### PR TITLE
Re-do the path interpolation support regarding RUNTIME_PREFIX

### PR DESCRIPTION
**Pull request by dscho**
For quite some time, Git for Windows supported config settings referring to a path that is relative to the location where Git is installed (the so-called "RUNTIME_PREFIX"). For example, setting `http.sslCAInfo` to `/ssl/certs/ca-bundle.crt` would make it expand automatically to `C:\Program Files\Git\mingw64\ssl\certs\ca-bundle.crt`.

When upstreaming this feature, it was decided that this was too limited (it only supported Windows, and since a leading slash indicates a valid absolute path on other platforms, could not be extended to span those platforms, too).

Instead, the value now needs to start with `%(prefix)/` to be expanded in that way.

Let's take those patches, but also reinstate Git for Windows' original, now deprecated behavior. For good measure, let's print a warning that this has been deprecated.

### CODE REVIEW

**Comment by Stanzilla** [comment]
@dscho does this influence the git config includes like the tripple slashes in `[includeIf "gitdir/i:///wsl$/Ubuntu/home/stan/projects/personal/**"]`?

**Comment by dscho** [comment]
> @dscho does this influence the git config includes like the tripple slashes in `[includeIf "gitdir/i:///wsl$/Ubuntu/home/stan/projects/personal/**"]`?

It should not. Does it?

**Comment by dscho** [comment]
I guess it does: it will probably complain, and the only solution might be to go from triple to double slashes (which should also work).

**Comment by Stanzilla** [comment]
@dscho Interesting, I'm asking because of this https://github.com/git-for-windows/git/issues/2563 so it is expected to now work with only two?

**Comment by dscho** [comment]
Darn it. I fear that it might not be possible to specify this in a backwards-compatible way... :-( didn't think of that.

**Comment by Stanzilla** [comment]
> Darn it. I fear that it might not be possible to specify this in a backwards-compatible way... :-( didn't think of that.

Okay let's say I migrate everything to the new version, how would the new format look like?

**Comment by dscho** [comment]
I _think_ that it should work with two slashes, but it might not...

Maybe going forward, we'll keep treating three slashes as if they were two, and make it work with two slashes at the point when we drop the "treat paths starting with a slash as relative to `git.exe`'s parent directory" patch.

**Pull request merged**
