### PR TITLE
DO NOT MERGE YET! Fixes required to build Git for Windows with MSys2

### PR DESCRIPTION
**Pull request by dscho**
This Pull Request, in conjunction with git-for-windows/msys2-runtime#1, makes Git for Windows compile with MSys2 and to pass the test suite.

### CODE REVIEW

**Comment by sschuberth** [comment]
FYI, it seems this merge started to break 7 more tests on our CI for the MSYS1-based Git SDK, see https://dscho.cloudapp.net/job/sdk-test-git/111/. Probably not a big issue with us going for MSYS2 now, but it still bothers me a bit and I wonder whether we could have made it so that tests work for both MSYS1 and MSYS2.

**Comment by dscho** [comment]
Booh! I will have a look next week.

**Comment by dscho** [comment]
Quick hunch: I think that (partially) reverting 3153820216f1ccc5e2a4b559d7d920a2167bd6e4 might fix it. Ideally, we would guard the `tr` post processing in something like

```bash
case "$(uname -r)" in
2.*)
    # MSys2's tr works well
    ;;
*)
    [...]
    ;;
esac
```

**Comment by dscho** [comment]
I have to admit that I have no clue so far about `t7400`. The test was virtually unchanged since 1.9.5.

And `t9020` should stop to [fail](https://dscho.cloudapp.net/job/sdk-test-git/ws/test-results/t9020-remote-svn.sh/*view*/) once merging `update-to-2.3.0` is merged given that all tests [are skipped with MinGW then](https://github.com/dscho/git/commit/6a8a24a7f8073508cf58b5967701a148b61219a1)...

**Comment by dscho** [comment]
Update: compiling the code as of #27 in my `msysGit` setup (with minor touch-ups – essentially separating MSys1 from MSys2 settings – that I will squash into the appropriate commits) lets `t5000`, `t7400` and `t9020` pass just fine.

**Comment by sschuberth** [comment]
I couldn't resist and did have a deeper look into why `t7400` fails with MSYS1. To start off with, the failure is totally unrelated to this PR as `t7400` already started to fail in [test build 106](https://dscho.cloudapp.net/job/sdk-test-git/106/) before this PR was even merged.

Anyway, again for the record: When using the same [Git-SDK artifact](https://dscho.cloudapp.net/job/sdk-test-installer/93/artifact/Git-SDK.tar.gz) and [Git artifact](https://dscho.cloudapp.net/job/sdk-build-git/2/artifact/git.tar.gz) as the test build I can reproduce the failure locally. However, when using the [previous Git artifact](https://dscho.cloudapp.net/job/sdk-build-git/1/artifact/git.tar.gz) with the same Git-SDK the failure disappears. Even just swapping the `git.exe` file makes the failure go away or reappear. So the failure is introduced by Git, not by the SDK. But both Git artifacts were built from the same SHA1 `8ffc0c2`! Further looking at [what triggered the build that created the failing Git artifact](https://dscho.cloudapp.net/job/sdk-build-git/2/) we see that it was "A change within the response URL invocation". Unfortunately the log for this is gone, but this means there was a package update in upstream MSYS.

So my hunch is that a part of the toolchain was changed in a way that it broke something related to UTF-8 encoding when building Git. At this point I'll stop as I'm confident this is not easy to fix.

**Pull request merged**
