### PR TITLE
Drop deprecated `git status --show-ignored-directory` option

### PR DESCRIPTION
**Pull request by dscho**
In the v2.15.x timeframe, that option was integrated into core Git, but with a different syntax: `--ignored=matching`. In Git for Windows, since we offered `--show-ignored-directory` in at least one official version, we reintroduced it as a backstop, deprecating it and intending to remove it soon.

The time has come.

### CODE REVIEW

**Comment by dscho** [comment]
@clboles Could you please make sure that this option is indeed not used any longer in any projects you maintain?

**Comment by jamill** [comment]
This option is still used by the version of Git that ships with Visual Studio 2017. As VFSForGit overrides the version of Git that Visual Studio uses to the one that VFSForGit installs, this will cause issue with VFSForGit and Visual Studio 2017 installed on the same machine.

We could look at moving this patch into only the Git for VFSForGit, as an option.

**Comment by dscho** [comment]
> As VFSForGit overrides the version of Git that Visual Studio uses to the one that VFSForGit installs, this will cause issue with VFSForGit and Visual Studio 2017 installed on the same machine.

True. But VFS for Git has this option deprecated for ages now, too... So all that would be needed is to make sure that Team Explorer does not use the deprecated option, but instead the one sanctioned by the core Git reviewers. @clboles ... this is in your court now...

**Comment by dscho** [comment]
For lurkers: We will have to wait with merging this PR for a while, until we can be sure that no users of those deprecated options are left.

**Comment by dscho** [comment]
> This option is still used by the version of Git that ships with Visual Studio 2017.

It's time, I think.

**Comment by dscho** [comment]
I will merge this soon, mainly as an excuse to get a new [snapshot](https://wingit.blob.core.windows.net/files/index.html). For the same reason, I will hold off from merging https://github.com/git-for-windows/git/pull/2068 for a bit, in case we need another snapshot soon.

**Pull request merged**
